begin;
select set_config('request.jwt.claim.sub',(select id::text from public.perfiles where activo and rol='administrador' limit 1),true);
create temporary table resultados_ciclos(caso text,resultado text);
grant all on resultados_ciclos to authenticated;
set local role authenticated;
do $$declare f uuid;p uuid;l uuid;c uuid;c2 uuid;m uuid;k uuid;liq uuid;t uuid;asset uuid;bank uuid;acc uuid;n numeric;ok boolean;r record;prov uuid;oc uuid;b uuid;c3 uuid;begin
 insert into public.fincas(nombre) values('__PRUEBA_CICLOS_'||gen_random_uuid()) returning id into f;
 insert into public.propiedades_finca(finca_id,nombre,modalidad,propietario,porcentaje_propietario) values(f,'César ejemplo','Porcentaje sobre ventas brutas','Dueño ejemplo',30) returning id into p;
 insert into public.lotes_finca(finca_id,propiedad_id,anio,nombre,producto) values(f,p,2026,'Lote ejemplo','Yuca') returning id into l;
 insert into public.ciclos_finca(lote_id,nombre,producto,fecha_siembra,porcentaje_propietario,propietario) values(l,'Cultivo 1','Yuca','2026-10-01',30,'Dueño ejemplo') returning id into c;
 insert into public.ciclos_finca(lote_id,nombre,producto,fecha_siembra) values(l,'Cultivo 2','Yuca','2026-10-01') returning id into c2;
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad) values(gen_random_uuid(),c,'2026-10-01','Cosecha','Yuca','Primera','kg',4600) returning id into m;
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad) values(gen_random_uuid(),c,'2026-10-01','Cosecha','Estacas','Estacas','Unidades',2000);
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad,cantidad_comercial,unidad_comercial,precio_unitario,comprador) values(gen_random_uuid(),c,'2026-10-01','Venta en campo','Yuca','Primera','kg',2300,50,'Quintales',10000,'Comprador ejemplo');
 select ventas_brutas_crc,dueno_crc into r from public.resumen_ciclos_finca where id=c;
 if r.ventas_brutas_crc<>500000 or r.dueno_crc<>150000 then raise exception 'El porcentaje no se calculó sobre la venta en campo';end if;
 insert into resultados_ciclos values('30% del bruto en campo','OK');
 insert into public.costos_finca(finca_id,lote_id,ciclo_id,fecha,categoria,monto) values(f,l,c,'2026-10-01','Planilla',100000);
 select dueno_crc into n from public.resumen_ciclos_finca where id=c;if n<>150000 then raise exception 'Los gastos redujeron la base del dueño';end if;
 insert into resultados_ciclos values('Gastos no reducen el porcentaje','OK');
 ok:=false;begin insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad,observaciones) values(gen_random_uuid(),c,'2026-10-01','Pérdida','Yuca','Primera','kg',3000,'Exceso');exception when others then ok:=true;end;if not ok then raise exception 'Permitió salida mayor al saldo';end if;
 select saldo into n from public.saldos_cosecha_finca where ciclo_id=c and producto='Yuca';if n<>2300 then raise exception 'Exceso modificó el inventario';end if;
 insert into resultados_ciclos values('Exceso se rechaza sin alterar stock','OK');
 select saldo into n from public.saldos_cosecha_finca where ciclo_id=c and producto='Estacas';if n<>2000 then raise exception 'Mezcló estacas con raíces';end if;
 insert into resultados_ciclos values('Estacas separadas de kilos de raíz','OK');
 insert into public.costos_finca(finca_id,fecha,categoria,monto) values(f,'2026-10-01','Caminos',200000) returning id into k;
 perform public.repartir_gasto_finca(k,jsonb_build_array(jsonb_build_object('ciclo_id',c,'monto',120000),jsonb_build_object('ciclo_id',c2,'monto',80000)));
 select costos_crc into n from public.resumen_ciclos_finca where id=c;if n<>220000 then raise exception 'Gasto compartido no cuadra';end if;
 ok:=false;begin perform public.repartir_gasto_finca(k,jsonb_build_array(jsonb_build_object('ciclo_id',c,'monto',220000)));exception when others then ok:=true;end;if not ok then raise exception 'Reparto mayor permitido';end if;
 select sum(monto) into n from public.repartos_costos_finca where costo_id=k;if n<>200000 then raise exception 'Fallo destruyó reparto anterior';end if;
 insert into resultados_ciclos values('Reparto atómico sin duplicar el gasto','OK');
 liq:=public.liquidar_dueno_finca(c,'2026-10-01');perform public.liquidar_dueno_finca(c,'2026-10-01');
 select count(*) into n from public.cuentas_manuales where liquidacion_dueno_id=liq and tipo='pagar';if n<>1 then raise exception 'Liquidación duplicada';end if;
 select monto into n from public.cuentas_manuales where liquidacion_dueno_id=liq and tipo='pagar';if n<>150000 then raise exception 'Deuda dueño no cuadra';end if;
 insert into resultados_ciclos values('Liquidación repetida genera una sola deuda','OK');
 insert into public.cuentas_bancarias(banco,moneda,saldo_inicial,empresa) values('__PRUEBA_AGRO','CRC',1000000,'agro_solano') returning id into bank;
 select id into acc from public.cuentas_manuales where liquidacion_dueno_id=liq and tipo='pagar';
 perform public.registrar_movimiento_bancario(bank,'2026-10-01','egreso',150000,'Pago dueño','TEST',jsonb_build_array(jsonb_build_object('origen','cuenta_manual_pagar','origen_id',acc,'monto',150000)));
 update public.ciclos_finca set porcentaje_propietario=25 where id=c;perform public.liquidar_dueno_finca(c,'2026-10-01');
 select monto into n from public.cuentas_manuales where liquidacion_dueno_id=liq and tipo='cobrar';if n<>25000 then raise exception 'Reintegro no generado';end if;
 insert into resultados_ciclos values('Corrección 30 a 25% conserva pago y genera reintegro','OK');
 ok:=false;begin perform public.cambiar_estado_ciclo_finca(c,true,'Intento con remanente');exception when others then ok:=true;end;if not ok then raise exception 'Cerró con existencia';end if;
 insert into resultados_ciclos values('No cierra con producto sin destino','OK');
 m:=public.arrastrar_cosecha_finca(gen_random_uuid(),c,c2,'Yuca','Primera','kg',2300,100000,'2026-10-01','Remanente para siguiente cultivo');
 select saldo into n from public.saldos_cosecha_finca where ciclo_id=c2 and producto='Yuca';if n<>2300 then raise exception 'Arrastre perdió cantidad';end if;
 select sum(costos_crc) into n from public.resumen_ciclos_finca where id in(c,c2);if n<>300000 then raise exception 'Arrastre duplicó o perdió costo';end if;
 insert into resultados_ciclos values('Arrastre conserva producto e inversión total','OK');
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad,observaciones) values(gen_random_uuid(),c,'2026-10-01','Uso como semilla','Estacas','Estacas','Unidades',2000,'Semilla propia');
 perform public.cambiar_estado_ciclo_finca(c,true,'Cosecha terminada');
 ok:=false;begin insert into public.costos_finca(finca_id,lote_id,ciclo_id,fecha,categoria,monto) values(f,l,c,'2026-10-01','Otro',1);exception when others then ok:=true;end;if not ok then raise exception 'Modificó cultivo cerrado';end if;
 insert into resultados_ciclos values('Cierre conserva resultado y bloquea costos posteriores','OK');
 perform public.cambiar_estado_ciclo_finca(c,false,'Corregir costo');select count(*) into n from public.cierres_ciclo_finca where ciclo_id=c;if n<>2 then raise exception 'Perdió historial de cierres';end if;
 insert into resultados_ciclos values('Reapertura con motivo conserva cierre anterior','OK');
 insert into public.activos_finca(finca_id,tipo,nombre,costo_unitario_crc,valor_actual_unitario_crc) values(f,'Tractor','Tractor ejemplo',12000000,10000000) returning id,tractor_operativo_id into asset,t;
 if t is null then raise exception 'No creó identidad de tractor';end if;
 select count(*) into n from public.activos_finca where tractor_operativo_id=t;if n<>1 then raise exception 'Duplicó valoración de tractor';end if;
 insert into public.actividades_tractor(finca_id,tractor_id,fecha,tipo,descripcion,litros,monto,horometro) values(f,t,'2026-10-01','Combustible','Diesel',30,21000,100);
 select count(*) into n from public.costos_finca where actividad_tractor_id in(select id from public.actividades_tractor where tractor_id=t);if n<>1 then raise exception 'Costo tractor duplicado';end if;
 insert into resultados_ciclos values('Tractor: una identidad, una valoración y un gasto','OK');
 insert into public.ciclos_finca(lote_id,nombre,producto,fecha_siembra,porcentaje_propietario,propietario) values(l,'Cultivo exportadora','Yuca','2026-10-01',38,'Dueño ejemplo') returning id into c3;
 insert into public.proveedores(nombre,tipo) values('__PRUEBA_AGRO_'||gen_random_uuid(),'Propio') returning id into prov;
 insert into public.ordenes_compra(codigo,fecha,proveedor_id,tipo_compra,producto,finca_lote_id,rebaja_planilla_flete,precio_europa,precio_eeuu,precio_campo) values('__TEST_OC_'||gen_random_uuid(),'2026-10-01',prov,'Cosecha propia','Yuca',l,200000,10000,5000,10000) returning id into oc;
 insert into public.boletas_entrada(codigo,orden_compra_id,proveedor_id,producto) values('__TEST_B_PEND_'||gen_random_uuid(),oc,prov,'Yuca');
 insert into public.boletas_entrada(codigo,orden_compra_id,proveedor_id,producto,finalizada_en,monto_cxp) values('__TEST_B_'||gen_random_uuid(),oc,prov,'Yuca',now(),1000000) returning id into b;
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad) values(gen_random_uuid(),c3,'2026-10-01','Cosecha','Yuca','Primera','kg',4600);
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad,orden_compra_id) values(gen_random_uuid(),c3,'2026-10-01','Entrega a exportadora','Yuca','Primera','kg',2300,oc);
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad,orden_compra_id) values(gen_random_uuid(),c3,'2026-10-01','Entrega a exportadora','Yuca','Primera','kg',2300,oc);
 select ventas_brutas_crc,dueno_crc into r from public.resumen_ciclos_finca where id=c3;if r.ventas_brutas_crc<>1000000 or r.dueno_crc<>380000 then raise exception 'Entregas duplicadas o rebajos redujeron bruto: %',to_jsonb(r);end if;
 select monto into n from public.cxp_operativa where origen='compra_campo' and origen_id=oc;if n<>800000 then raise exception 'Se alteró el neto por pagar de exportadora';end if;
 insert into resultados_ciclos values('38% de campo antes de rebajos; dos entregas cuentan una sola venta','OK');
 select id into m from public.movimientos_cosecha_finca where ciclo_id=c and tipo='Venta en campo';
 update public.movimientos_cosecha_finca set precio_unitario=12000,motivo_correccion='Corregir precio pactado' where id=m;
 select monto into n from public.cuentas_manuales where movimiento_cosecha_id=m;if n<>600000 then raise exception 'Corrección no actualizó cobro';end if;
 select count(*) into n from public.correcciones_cosecha_finca where movimiento_id=m;if n<>1 then raise exception 'No conservó precio anterior';end if;
 ok:=false;begin update public.movimientos_cosecha_finca set cantidad=2760,cantidad_comercial=60,motivo_correccion='Intento sin existencia' where id=m;exception when others then ok:=true;end;if not ok then raise exception 'Corrección sobregiró stock';end if;
 insert into resultados_ciclos values('Corregir precio actualiza cobro, conserva historial y no permite stock negativo','OK');
 ok:=false;begin perform public.cambiar_estado_ciclo_finca(c3,true,'Prueba de cierre pendiente');exception when others then ok:=true;end;if not ok then raise exception 'Cerró compra incompleta';end if;
 insert into resultados_ciclos values('Cierre espera la liquidación completa de cosecha propia','OK');
 update public.boletas_entrada set finalizada_en=now(),monto_cxp=0 where orden_compra_id=oc and finalizada_en is null;
 perform public.cambiar_estado_ciclo_finca(c3,true,'Todas las boletas liquidadas');
 ok:=false;begin update public.boletas_entrada set monto_cxp=2000000 where id=b;exception when others then ok:=true;end;if not ok then raise exception 'Una boleta cambió un cultivo cerrado';end if;
 insert into resultados_ciclos values('Cierre agrícola protege las boletas y su venta en campo','OK');
 
 
end$$;
select * from resultados_ciclos;
rollback;
