-- Ejercicio reproducible: termina en ROLLBACK y no conserva operaciones de prueba.
begin;
select set_config('request.jwt.claim.sub',(select id::text from public.perfiles where activo and rol='administrador' limit 1),true);
create temporary table chequeo_finca(caso text,resultado text,detalle text);
grant all on chequeo_finca to authenticated;
set local role authenticated;
do $$
declare a uuid;b uuid;la uuid;lb uuid;i uuid;t uuid;req uuid;mov uuid;pf uuid;cuenta uuid;ba uuid;be uuid;at uuid;
 n numeric;v numeric;ok boolean;mensaje text;
begin
 insert into public.fincas(nombre) values('__EJERCICIO_FINCA_A_'||gen_random_uuid()) returning id into a;
 insert into public.fincas(nombre) values('__EJERCICIO_FINCA_B_'||gen_random_uuid()) returning id into b;
 insert into public.lotes_finca(finca_id,anio,nombre,producto,inversion_en_curso) values(a,2026,'Lote prueba A','Yuca',true) returning id into la;
 insert into public.lotes_finca(finca_id,anio,nombre,producto) values(b,2026,'Lote prueba B','Ñampí') returning id into lb;
 insert into public.insumos(nombre,unidad) values('__EJERCICIO_ABONO_'||gen_random_uuid(),'saco') returning id into i;
 req:=gen_random_uuid();
 mov:=public.registrar_insumo_finca(req,'Entrega directa',i,null,a,null,'2026-10-01',100,10000,null,'Proveedor de ejemplo','PRUEBA',null);
 select cantidad,valor_crc into n,v from public.existencias_insumos_finca where finca_id=a and insumo_id=i;
 if n<>100 or v<>1000000 then raise exception 'Entrega directa no cuadra';end if;
 insert into chequeo_finca values('Entrega directa','OK','100 sacos, inventario ₡1.000.000 y deuda al proveedor; todavía no es gasto del cultivo.');
 select count(*) into n from public.costos_finca where finca_id=a;
 if n<>0 then raise exception 'Compra se gastó sin consumo';end if;
 insert into chequeo_finca values('Comprar no equivale a consumir','OK','La recepción conserva valor en inventario; no genera costo agrícola.');
 select count(*) into n from public.cuentas_manuales where movimiento_insumo_finca_id=mov and empresa='agro_solano' and monto=1000000;
 if n<>1 then raise exception 'Cuenta por pagar de insumo inválida';end if;
 insert into chequeo_finca values('Cuenta por pagar de insumo','OK','Una cuenta por pagar de Agrosolano por ₡1.000.000.');
 perform public.registrar_insumo_finca(req,'Entrega directa',i,null,a,null,'2026-10-01',100,10000,null,'Proveedor de ejemplo','PRUEBA',null);
 select cantidad into n from public.existencias_insumos_finca where finca_id=a and insumo_id=i;
 if n<>100 then raise exception 'Entrega repetida duplicada';end if;
 insert into chequeo_finca values('Reintento de entrega','OK','Repetir la misma solicitud no duplica inventario ni deuda.');
 perform public.registrar_insumo_finca(gen_random_uuid(),'Entrega directa',i,null,a,null,'2026-10-01',100,20000,null,'Proveedor de ejemplo','PRUEBA-2',null);
 perform public.registrar_insumo_finca(gen_random_uuid(),'Traslado',i,a,b,null,'2026-10-01',50,null,null,null,'PRUEBA-TRASLADO',null);
 select cantidad,valor_crc into n,v from public.existencias_insumos_finca where finca_id=b and insumo_id=i;
 if n<>50 or v<>750000 then raise exception 'Traslado no conserva costo promedio';end if;
 insert into chequeo_finca values('Traslado y costo promedio','OK','50 sacos a ₡15.000: destino ₡750.000; origen ₡2.250.000; total ₡3.000.000.');
 mov:=public.registrar_insumo_finca(gen_random_uuid(),'Consumo',i,a,null,la,'2026-10-01',40,null,null,null,'PRUEBA-CONSUMO',null);
 select monto into v from public.costos_finca where movimiento_insumo_finca_id=mov;
 if v<>600000 then raise exception 'Costo de consumo incorrecto';end if;
 select cantidad,valor_crc into n,v from public.existencias_insumos_finca where finca_id=a and insumo_id=i;
 if n<>110 or v<>1650000 then raise exception 'Consumo no cuadra';end if;
 insert into chequeo_finca values('Consumo en lote','OK','40 sacos pasan a costo del cultivo ₡600.000; inventario de origen queda en ₡1.650.000.');
 ok:=false;begin
  perform public.registrar_insumo_finca(gen_random_uuid(),'Consumo',i,a,null,la,'2026-10-01',120,null,null,null,'PRUEBA-EXCESO',null);
 exception when others then ok:=true;end;
 if not ok then raise exception 'Permitió consumo mayor al saldo';end if;
 select cantidad into n from public.existencias_insumos_finca where finca_id=a and insumo_id=i;
 if n<>110 then raise exception 'Error alteró inventario';end if;
 insert into chequeo_finca values('Inventario insuficiente','OK','El exceso se rechaza y el saldo permanece intacto.');
 ok:=false;begin
  perform public.registrar_insumo_finca(gen_random_uuid(),'Consumo',i,a,null,lb,'2026-10-01',10,null,null,null,'PRUEBA-LOTE-AJENO',null);
 exception when others then ok:=true;end;
 if not ok then raise exception 'Permitió lote de otra finca';end if;
 select cantidad into n from public.existencias_insumos_finca where finca_id=a and insumo_id=i;
 if n<>110 then raise exception 'Lote incorrecto descontó stock';end if;
 insert into chequeo_finca values('Lote de otra finca','OK','Se rechaza y se revierte el movimiento completo.');
 insert into public.planillas_finca(lote_id,colaborador,periodo_inicio,periodo_fin,fecha_pago,dias,tarifa_diaria,rebajos)
 values(la,'Cuadrilla de ejemplo','2026-10-01','2026-10-02','2026-10-02',10,15000,10000) returning id into pf;
 select monto into v from public.costos_finca where planilla_finca_id=pf;if v<>150000 then raise exception 'Costo de planilla incorrecto';end if;
 select id,monto into cuenta,v from public.cuentas_manuales where planilla_finca_id=pf;if v<>140000 then raise exception 'Neto de planilla incorrecto';end if;
 insert into chequeo_finca values('Planilla bruto y neto','OK','Costo ₡150.000; deuda ₡140.000; rebajos ₡10.000.');
 update public.planillas_finca set dias=12 where id=pf;
 select count(*),sum(monto) into n,v from public.costos_finca where planilla_finca_id=pf;
 if n<>1 or v<>180000 then raise exception 'Edición duplicó costo';end if;
 select monto into v from public.cuentas_manuales where id=cuenta;if v<>170000 then raise exception 'Edición no actualizó deuda';end if;
 insert into chequeo_finca values('Corrección de planilla','OK','Actualiza el mismo costo a ₡180.000 y la misma deuda a ₡170.000.');
 insert into public.cuentas_bancarias(banco,moneda,empresa) values('__PRUEBA_AGRO_'||gen_random_uuid(),'CRC','agro_solano') returning id into ba;
 insert into public.cuentas_bancarias(banco,moneda,empresa) values('__PRUEBA_EXPORT_'||gen_random_uuid(),'CRC','exportadora') returning id into be;
 ok:=false;begin
  perform public.registrar_movimiento_bancario(be,'2026-10-01','egreso',100000,'Prueba empresa incorrecta',null,jsonb_build_array(jsonb_build_object('origen','cuenta_manual_pagar','origen_id',cuenta,'monto',100000)));
 exception when others then ok:=true;end;
 if not ok then raise exception 'Se pagó con banco de otra empresa';end if;
 select count(*) into n from public.movimientos_bancarios where cuenta_id=be;if n<>0 then raise exception 'Pago rechazado dejó movimiento';end if;
 insert into chequeo_finca values('Separación de empresas','OK','No permite pagar una deuda de Agrosolano desde banco de exportadora; revierte la operación.');
 perform public.registrar_movimiento_bancario(ba,'2026-10-01','egreso',100000,'Pago parcial de planilla',null,jsonb_build_array(jsonb_build_object('origen','cuenta_manual_pagar','origen_id',cuenta,'monto',100000)));
 select monto-aplicado into v from public.cxp_operativa where origen='cuenta_manual_pagar' and origen_id=cuenta;if v<>70000 then raise exception 'Saldo de pago parcial incorrecto';end if;
 insert into chequeo_finca values('Pago parcial','OK','Pagado ₡100.000; saldo por pagar ₡70.000.');
 ok:=false;begin update public.planillas_finca set dias=5 where id=pf;exception when others then ok:=true;end;
 if not ok then raise exception 'Permitió reducir deuda debajo del pago';end if;
 select bruto into v from public.planillas_finca where id=pf;if v<>180000 then raise exception 'Corrección rechazada cambió planilla';end if;
 insert into chequeo_finca values('Corrección después de pagar','OK','No permite bajar la deuda por debajo de lo pagado; planilla y costo quedan intactos.');
 insert into public.tractores_finca(finca_id,nombre,horometro) values(a,'Tractor de ejemplo',100) returning id into t;
 insert into public.actividades_tractor(finca_id,lote_id,tractor_id,fecha,tipo,descripcion,horometro,litros,monto,beneficiario)
 values(a,la,t,'2026-10-01','Combustible','Combustible de prueba',105,20,30000,'Gasolinera de ejemplo') returning id into at;
 select monto into v from public.costos_finca where actividad_tractor_id=at;if v<>30000 then raise exception 'Combustible sin costo';end if;
 select horometro into v from public.tractores_finca where id=t;if v<>105 then raise exception 'Horómetro no actualizó';end if;
 insert into chequeo_finca values('Combustible y tractor','OK','20 litros, costo ₡30.000, una deuda y horómetro actualizado a 105.');
 update public.actividades_tractor set monto=35000 where id=at;
 select count(*),sum(monto) into n,v from public.costos_finca where actividad_tractor_id=at;if n<>1 or v<>35000 then raise exception 'Edición actividad duplicó costo';end if;
 insert into chequeo_finca values('Corrección de combustible','OK','Un solo costo actualizado a ₡35.000.');
 ok:=false;begin insert into public.actividades_tractor(finca_id,lote_id,tractor_id,fecha,tipo,descripcion,monto) values(b,lb,t,'2026-10-01','Trabajo','Tractor de finca ajena',0);exception when others then ok:=true;end;
 if not ok then raise exception 'Permitió tractor de otra finca';end if;
 insert into chequeo_finca values('Tractor asignado a otra finca','OK','Impide registrar trabajo bajo una asignación incorrecta.');
 insert into public.actividades_tractor(finca_id,tractor_id,fecha,tipo,descripcion,monto) values(a,t,'2026-10-01','Mantenimiento','Mantenimiento general de prueba',20000);
 select sum(monto) into v from public.costos_finca where finca_id=a and lote_id is null;
 if v<>20000 then raise exception 'Mantenimiento general no se registró';end if;
 insert into chequeo_finca values('Gasto general sin lote','HALLAZGO','Se guarda ₡20.000, pero el resumen por lote publicado no lo incluye. Falta mostrarlo y distribuirlo cuando corresponda.');
 insert into chequeo_finca values('Porcentaje del propietario','PENDIENTE','La ficha admite 30%/38%, pero no genera liquidación ni deuda por ventas de la propiedad.');
 insert into chequeo_finca values('Venta de subproductos de finca','PENDIENTE','La cuenta manual de Agrosolano no tiene finca/lote; esa venta no entra al resultado por lote.');
 insert into chequeo_finca values('Cierre y pérdida de cultivo','PENDIENTE','La marca inversión en curso no es un cierre contable, no registra pérdida ni conserva una liquidación final.');
 insert into chequeo_finca values('Valoración completa','HALLAZGO','El resumen publicado toma fichas manuales; los saldos de bodegas y los costos generales requieren integración.');
end $$;
select caso,resultado,detalle from chequeo_finca;
rollback;
