import React, {useEffect,useState} from 'react'
import {Plus,X} from 'lucide-react'
import {supabase} from './supabase'
import {costaRicaToday} from './weekly-model'

const blank=()=>({marca:'',descripcion:'',presentacion_kg:'',existencia:'0',minimo_alerta:'0',activo:true})
const newEntry=()=>({cantidad:'',fecha:costaRicaToday(),proveedor:'',moneda:'USD',precio:'',referencia:'',observaciones:''})
export default function CartonInventory({role}){
  const office=['administrador','oficina'].includes(role)
  const [cartons,setCartons]=useState([]);const [reserved,setReserved]=useState({});const [movements,setMovements]=useState([]);const [costs,setCosts]=useState([])
  const [editing,setEditing]=useState(null);const [receiving,setReceiving]=useState(null);const [existingCost,setExistingCost]=useState(false);const [form,setForm]=useState(blank);const [entry,setEntry]=useState(newEntry);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const [correction,setCorrection]=useState(null),[adjustments,setAdjustments]=useState([])
  const reload=()=>{Promise.all([supabase.from('inventario_cartones').select('*').order('marca'),supabase.from('ordenes_venta_lineas').select('carton_id,cantidad_cajas,ordenes_venta(estado)').not('carton_id','is',null),supabase.from('movimientos_cartones').select('carton_id,cantidad,creado_en,observaciones').order('creado_en',{ascending:false}).limit(100),office?supabase.from('costos_cartones').select('id,carton_id,cantidad,precio_unitario,moneda,simulado,fecha,proveedor_nombre,movimiento_id,referencia').limit(1000):Promise.resolve({data:[],error:null}),office?supabase.from('ajustes_precios_operativos').select('registro_id,antes,despues,motivo,registrado_en').eq('tipo','carton').order('registrado_en',{ascending:false}).limit(200):Promise.resolve({data:[],error:null})]).then(([a,b,c,d,e])=>{if(a.error||b.error||c.error||d.error||e.error){setError('No se pudo cargar el inventario y sus costos.');return}setCartons(a.data||[]);setMovements(c.data||[]);setCosts(d.data||[]);setAdjustments(e.data||[]);const counts={};for(const line of b.data||[]){if(line.ordenes_venta?.estado==='Anulada')continue;counts[line.carton_id]=(counts[line.carton_id]||0)+line.cantidad_cajas}setReserved(counts)})}
  useEffect(reload,[])
  const open=carton=>{setEditing(carton?.id||'new');setForm(carton?{...carton,presentacion_kg:carton.presentacion_kg??'',existencia:String(carton.existencia),minimo_alerta:String(carton.minimo_alerta)}:blank());setError('')}
  const save=async()=>{
    const stock=Number(form.existencia),min=Number(form.minimo_alerta),weight=form.presentacion_kg===''?null:Number(form.presentacion_kg)
    if(!form.marca.trim()||!form.descripcion.trim()||!Number.isInteger(min)||min<0||(editing==='new'&&(!Number.isInteger(stock)||stock<0))||(weight!==null&&(!Number.isFinite(weight)||weight<=0))){setError('Complete marca y descripción. Existencia y mínimo deben ser cantidades enteras no negativas.');return}
    setSaving(true);setError('')
    const payload={marca:form.marca.trim(),descripcion:form.descripcion.trim(),presentacion_kg:weight,minimo_alerta:min,activo:form.activo}
    if(editing==='new')payload.existencia=stock
    const {error:saveError}=editing==='new'?await supabase.from('inventario_cartones').insert(payload):await supabase.from('inventario_cartones').update(payload).eq('id',editing).select('id').single()
    setSaving(false);if(saveError){setError(`No se pudo guardar el cartón: ${saveError.message}`);return}setEditing(null);reload()
  }
  const receive=async()=>{
    const quantity=Number(entry.cantidad)
    if(!Number.isInteger(quantity)||quantity<=0){setError('Escriba la cantidad de cartones que ingresó (número entero mayor que cero).');return}
    if(office&&(!entry.fecha||!entry.proveedor.trim()||entry.precio===''||!Number.isFinite(Number(entry.precio))||Number(entry.precio)<0)){setError('Complete fecha, proveedor y precio por cartón. Si aún no conoce el precio, escriba 0 y marque la referencia como pendiente.');return}
    if(existingCost&&quantity>receiving.existencia-costs.filter(x=>x.carton_id===receiving.id&&Number(x.precio_unitario)>0).reduce((sum,x)=>sum+Number(x.cantidad),0)){setError('La cantidad con costo nuevo supera los cartones existentes que aún no tienen costo registrado.');return}
    setSaving(true);setError('')
    const simulated=entry.referencia.toUpperCase().includes('SIMULADO')||entry.proveedor.toUpperCase().includes('SIMULADO')
    const {error:entryError}=existingCost?await supabase.from('costos_cartones').insert({carton_id:receiving.id,fecha:entry.fecha,cantidad:quantity,proveedor_nombre:entry.proveedor.trim(),moneda:entry.moneda,precio_unitario:Number(entry.precio),referencia:entry.referencia.trim()||null,simulado:simulated}):await supabase.rpc(office?'registrar_compra_cartones':'registrar_entrada_cartones',office?{p_carton_id:receiving.id,p_cantidad:quantity,p_fecha:entry.fecha,p_proveedor:entry.proveedor.trim(),p_moneda:entry.moneda,p_precio:Number(entry.precio),p_referencia:entry.referencia.trim()||null,p_simulado:simulated}:{p_carton_id:receiving.id,p_cantidad:quantity,p_observaciones:entry.observaciones.trim()||null})
    setSaving(false);if(entryError){setError(`No se pudo registrar el cartón: ${entryError.message}`);return}setReceiving(null);setExistingCost(false);setEntry(newEntry());reload()
  }
  const correct=async()=>{
    const price=Number(correction.precio),quantity=Number(correction.cantidad)
    if(!Number.isFinite(price)||price<0||!Number.isInteger(quantity)||quantity<=0||correction.motivo.trim().length<8){setError('Revise precio, cantidad y motivo de al menos 8 caracteres.');return}
    setSaving(true);setError('')
    const {error:e}=await supabase.rpc('corregir_costo_carton',{p_costo_id:correction.id,p_precio:price,p_cantidad:quantity,p_motivo:correction.motivo.trim()})
    setSaving(false);if(e){setError(e.message);return}setCorrection(null);reload()
  }
  return <><div className="modulebar"><div><p>Registre las marcas, ingrese cartones y vea cuántos quedan después de las órdenes. {office?'Cada nueva compra con precio genera una cuenta por pagar al proveedor.':''}</p></div><button className="primary" onClick={()=>open(null)}><Plus size={18}/>Nueva marca</button></div><div className="carton-list">{cartons.length?cartons.map(c=>{const held=reserved[c.id]||0,available=c.existencia-held,last=movements.find(m=>m.carton_id===c.id);return <article key={c.id}><div><b>{c.marca}</b><span>{c.descripcion}{c.presentacion_kg?` · ${c.presentacion_kg} kg`:''}</span>{last&&<small>Última entrada: +{last.cantidad.toLocaleString('es-CR')} · {new Date(last.creado_en).toLocaleDateString('es-CR')}</small>}{office&&costs.filter(x=>x.carton_id===c.id).map(x=><div key={x.id} className="carton-cost-row"><small>{x.fecha} · {x.cantidad} cartones × {new Intl.NumberFormat('es-CR',{style:'currency',currency:x.moneda}).format(Number(x.precio_unitario))} · {x.proveedor_nombre}{x.simulado?' · SIMULADO':''}</small><button type="button" onClick={()=>{setCorrection({id:x.id,precio:String(x.precio_unitario),cantidad:String(x.cantidad),fixedQuantity:!!x.movimiento_id,motivo:''});setError('')}}>Editar precio/cantidad</button>{adjustments.filter(a=>a.registro_id===x.id).map((a,i)=><small key={i}>Ajuste: {a.antes.cantidad} × {a.antes.precio} → {a.despues.cantidad} × {a.despues.precio} · {a.motivo}</small>)}</div>)}</div><div><strong>{c.existencia.toLocaleString('es-CR')}</strong><small>en existencia</small></div><div><strong>{held.toLocaleString('es-CR')}</strong><small>reservados por órdenes</small></div><div className={available<=c.minimo_alerta?'low':''}><strong>{available.toLocaleString('es-CR')}</strong><small>{available<0?'Faltan cartones':available<=c.minimo_alerta?'Nivel bajo':'disponibles'}</small></div><div className="carton-actions"><button onClick={()=>{setReceiving(c);setExistingCost(false);setEntry(newEntry());setError('')}}>Ingresar cartones</button>{office&&c.existencia>costs.filter(x=>x.carton_id===c.id&&Number(x.precio_unitario)>0).reduce((sum,x)=>sum+Number(x.cantidad),0)&&<button onClick={()=>{setReceiving(c);setExistingCost(true);setEntry(newEntry());setError('')}}>Completar costo de existencias</button>}<button onClick={()=>open(c)}>Editar marca</button></div></article>}):<div className="empty"><h3>Sin marcas registradas</h3><p>Agregue la primera marca y su existencia para vincularla a una orden de venta.</p></div>}</div>
  {editing&&<div className="modalwrap"><div className="modal carton-modal"><div className="modalhead"><div><span>{editing==='new'?'NUEVO REGISTRO':'EDITAR REGISTRO'}</span><h2>Ficha del cartón</h2></div><button onClick={()=>setEditing(null)} aria-label="Cerrar"><X/></button></div><div className="formgrid"><label>Marca *<input value={form.marca} onChange={e=>setForm({...form,marca:e.target.value})} placeholder="Marielita"/></label><label>Descripción / presentación *<input value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} placeholder="Tapa rosada"/></label><label>Peso indicado (kg)<input type="number" min="0.01" step="0.01" value={form.presentacion_kg} onChange={e=>setForm({...form,presentacion_kg:e.target.value})}/></label>{editing==='new'&&<label>Existencia inicial (cartones)<input type="number" min="0" step="1" value={form.existencia} onChange={e=>setForm({...form,existencia:e.target.value})}/></label>}<label>Mínimo para alerta<input type="number" min="0" step="1" value={form.minimo_alerta} onChange={e=>setForm({...form,minimo_alerta:e.target.value})}/></label><label className="checklabel"><input type="checkbox" checked={form.activo} onChange={e=>setForm({...form,activo:e.target.checked})}/>Disponible para nuevas órdenes</label></div>{error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={()=>setEditing(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar marca'}</button></div></div></div>}
  {correction&&<div className="modalwrap"><div className="modal carton-modal"><div className="modalhead"><div><span>CORRECCIÓN DE CARTÓN</span><h2>Precio y cantidad con costo</h2></div><button onClick={()=>setCorrection(null)} aria-label="Cerrar"><X/></button></div><p>Esta corrección actualiza el costo del corte y la cuenta por pagar. La cantidad física recibida no se cambia aquí.</p><div className="formgrid"><label>Precio por cartón<input type="number" min="0" step="0.01" value={correction.precio} onChange={e=>setCorrection({...correction,precio:e.target.value})}/></label><label>Cartones con este costo<input type="number" min="1" step="1" disabled={correction.fixedQuantity} value={correction.cantidad} onChange={e=>setCorrection({...correction,cantidad:e.target.value})}/></label><label className="wide">Motivo de la corrección *<input value={correction.motivo} onChange={e=>setCorrection({...correction,motivo:e.target.value})} placeholder="Ejemplo: corrección de factura"/></label></div>{error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={()=>setCorrection(null)}>Cancelar</button><button className="primary" disabled={saving} onClick={correct}>Guardar corrección</button></div></div></div>}
  {receiving&&<div className="modalwrap"><div className="modal carton-modal"><div className="modalhead"><div><span>ENTRADA DE INVENTARIO</span><h2>{existingCost?"Completar costo · ":"Ingresar cartones · "}{receiving.marca}</h2></div><button onClick={()=>setReceiving(null)} aria-label="Cerrar"><X/></button></div><div className="formgrid"><label>{existingCost?"Cantidad existente sin costo *":"Cantidad de cartones que ingresan *"}<input type="number" min="1" step="1" inputMode="numeric" value={entry.cantidad} onChange={e=>setEntry({...entry,cantidad:e.target.value})} placeholder="Ejemplo: 500"/></label>{office?<><label>Fecha de ingreso *<input type="date" value={entry.fecha} onChange={e=>setEntry({...entry,fecha:e.target.value})}/></label><label className="wide">Proveedor *<input value={entry.proveedor} onChange={e=>setEntry({...entry,proveedor:e.target.value})}/></label><label>Moneda<select value={entry.moneda} onChange={e=>setEntry({...entry,moneda:e.target.value})}><option>USD</option><option>CRC</option></select></label><label>Precio por cartón *<input type="number" min="0" step="0.01" value={entry.precio} onChange={e=>setEntry({...entry,precio:e.target.value})}/></label><label className="wide">Factura / referencia<input value={entry.referencia} onChange={e=>setEntry({...entry,referencia:e.target.value})}/></label><p className="wide">Total a pagar: {new Intl.NumberFormat('es-CR',{style:'currency',currency:entry.moneda}).format(Number(entry.cantidad||0)*Number(entry.precio||0))}. Use “SIMULADO” en la referencia para datos de prueba.</p></>:<label className="wide">Observación<input value={entry.observaciones} onChange={e=>setEntry({...entry,observaciones:e.target.value})}/></label>}</div><p className="sale-help">Existencia actual: {receiving.existencia.toLocaleString('es-CR')} cartones. {existingCost?"Solo se registra el costo; la existencia no cambia.":"La nueva entrada se suma a esa cantidad."}</p>{error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={()=>setReceiving(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={receive} disabled={saving}>{saving?'Guardando…':existingCost?'Guardar costo':'Sumar al inventario'}</button></div></div></div>}
  {!editing&&!receiving&&error&&<div className="formerror">{error}</div>}</>
}
