import React, {useEffect,useState} from 'react'
import {Plus,X} from 'lucide-react'
import {supabase} from './supabase'

const blank=()=>({marca:'',descripcion:'',presentacion_kg:'',existencia:'0',minimo_alerta:'0',activo:true})
export default function CartonInventory(){
  const [cartons,setCartons]=useState([]);const [reserved,setReserved]=useState({});const [movements,setMovements]=useState([])
  const [editing,setEditing]=useState(null);const [receiving,setReceiving]=useState(null);const [form,setForm]=useState(blank);const [entry,setEntry]=useState({cantidad:'',observaciones:''});const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const reload=()=>{Promise.all([supabase.from('inventario_cartones').select('*').order('marca'),supabase.from('ordenes_venta_lineas').select('carton_id,cantidad_cajas').not('carton_id','is',null),supabase.from('movimientos_cartones').select('carton_id,cantidad,creado_en,observaciones').order('creado_en',{ascending:false}).limit(100)]).then(([a,b,c])=>{if(a.error||b.error||c.error){setError('No se pudo cargar el inventario de cartones.');return}setCartons(a.data||[]);setMovements(c.data||[]);const counts={};for(const line of b.data||[])counts[line.carton_id]=(counts[line.carton_id]||0)+line.cantidad_cajas;setReserved(counts)})}
  useEffect(reload,[])
  const open=carton=>{setEditing(carton?.id||'new');setForm(carton?{...carton,presentacion_kg:carton.presentacion_kg??'',existencia:String(carton.existencia),minimo_alerta:String(carton.minimo_alerta)}:blank());setError('')}
  const save=async()=>{
    const stock=Number(form.existencia),min=Number(form.minimo_alerta),weight=form.presentacion_kg===''?null:Number(form.presentacion_kg)
    if(!form.marca.trim()||!form.descripcion.trim()||!Number.isInteger(min)||min<0||(editing==='new'&&(!Number.isInteger(stock)||stock<0))||(weight!==null&&(!Number.isFinite(weight)||weight<=0))){setError('Complete marca y descripción. Existencia y mínimo deben ser cantidades enteras no negativas.');return}
    setSaving(true);setError('')
    const payload={marca:form.marca.trim(),descripcion:form.descripcion.trim(),presentacion_kg:weight,minimo_alerta:min,activo:form.activo}
    if(editing==='new')payload.existencia=stock
    const {error:saveError}=editing==='new'?await supabase.from('inventario_cartones').insert(payload):await supabase.from('inventario_cartones').update(payload).eq('id',editing).select('id').single()
    setSaving(false);if(saveError){setError(`No se pudo guardar el cartón: ${saveError.message}`);return}setEditing(null);reload()
  }
  const receive=async()=>{
    const quantity=Number(entry.cantidad)
    if(!Number.isInteger(quantity)||quantity<=0){setError('Escriba la cantidad de cartones que ingresó (número entero mayor que cero).');return}
    setSaving(true);setError('')
    const {error:entryError}=await supabase.rpc('registrar_entrada_cartones',{p_carton_id:receiving.id,p_cantidad:quantity,p_observaciones:entry.observaciones.trim()||null})
    setSaving(false);if(entryError){setError(`No se pudo ingresar el cartón: ${entryError.message}`);return}setReceiving(null);setEntry({cantidad:'',observaciones:''});reload()
  }
  return <><div className="modulebar"><div><p>Registre las marcas, ingrese cartones y vea cuántos quedan después de las órdenes.</p></div><button className="primary" onClick={()=>open(null)}><Plus size={18}/>Nueva marca</button></div><div className="carton-list">{cartons.length?cartons.map(c=>{const held=reserved[c.id]||0,available=c.existencia-held,last=movements.find(m=>m.carton_id===c.id);return <article key={c.id}><div><b>{c.marca}</b><span>{c.descripcion}{c.presentacion_kg?` · ${c.presentacion_kg} kg`:''}</span>{last&&<small>Última entrada: +{last.cantidad.toLocaleString('es-CR')} · {new Date(last.creado_en).toLocaleDateString('es-CR')}</small>}</div><div><strong>{c.existencia.toLocaleString('es-CR')}</strong><small>en existencia</small></div><div><strong>{held.toLocaleString('es-CR')}</strong><small>reservados por órdenes</small></div><div className={available<=c.minimo_alerta?'low':''}><strong>{available.toLocaleString('es-CR')}</strong><small>{available<0?'Faltan cartones':available<=c.minimo_alerta?'Nivel bajo':'disponibles'}</small></div><div className="carton-actions"><button onClick={()=>{setReceiving(c);setEntry({cantidad:'',observaciones:''});setError('')}}>Ingresar cartones</button><button onClick={()=>open(c)}>Editar marca</button></div></article>}):<div className="empty"><h3>Sin marcas registradas</h3><p>Agregue la primera marca y su existencia para vincularla a una orden de venta.</p></div>}</div>
  {editing&&<div className="modalwrap"><div className="modal carton-modal"><div className="modalhead"><div><span>{editing==='new'?'NUEVO REGISTRO':'EDITAR REGISTRO'}</span><h2>Ficha del cartón</h2></div><button onClick={()=>setEditing(null)} aria-label="Cerrar"><X/></button></div><div className="formgrid"><label>Marca *<input value={form.marca} onChange={e=>setForm({...form,marca:e.target.value})} placeholder="Marielita"/></label><label>Descripción / presentación *<input value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} placeholder="Tapa rosada"/></label><label>Peso indicado (kg)<input type="number" min="0.01" step="0.01" value={form.presentacion_kg} onChange={e=>setForm({...form,presentacion_kg:e.target.value})}/></label>{editing==='new'&&<label>Existencia inicial (cartones)<input type="number" min="0" step="1" value={form.existencia} onChange={e=>setForm({...form,existencia:e.target.value})}/></label>}<label>Mínimo para alerta<input type="number" min="0" step="1" value={form.minimo_alerta} onChange={e=>setForm({...form,minimo_alerta:e.target.value})}/></label><label className="checklabel"><input type="checkbox" checked={form.activo} onChange={e=>setForm({...form,activo:e.target.checked})}/>Disponible para nuevas órdenes</label></div>{error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={()=>setEditing(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar marca'}</button></div></div></div>}
  {receiving&&<div className="modalwrap"><div className="modal carton-modal"><div className="modalhead"><div><span>ENTRADA DE INVENTARIO</span><h2>{receiving.marca} · {receiving.descripcion}</h2></div><button onClick={()=>setReceiving(null)} aria-label="Cerrar"><X/></button></div><div className="formgrid"><label>Cantidad de cartones que ingresan *<input type="number" min="1" step="1" inputMode="numeric" value={entry.cantidad} onChange={e=>setEntry({...entry,cantidad:e.target.value})} placeholder="Ejemplo: 500"/></label><label className="wide">Observación (opcional)<input value={entry.observaciones} onChange={e=>setEntry({...entry,observaciones:e.target.value})} placeholder="Compra, proveedor o referencia"/></label></div><p className="sale-help">Existencia actual: {receiving.existencia.toLocaleString('es-CR')} cartones. La nueva entrada se suma a esa cantidad.</p>{error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={()=>setReceiving(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={receive} disabled={saving}>{saving?'Guardando…':'Sumar al inventario'}</button></div></div></div>}
  {!editing&&!receiving&&error&&<div className="formerror">{error}</div>}</>
}
