import React,{useState} from 'react'
import {cash} from './finance'
import {auditDate,exampleDefaults,runFarmExample,auditedChecks,farmPriorities} from './farm-audit-model'
export default function FarmExample(){
 const [open,setOpen]=useState(false),[input,setInput]=useState({...exampleDefaults})
 const change=(key,value)=>setInput(x=>({...x,[key]:value}))
 const preset=mode=>setInput({...exampleDefaults,mode,ownerPercent:mode==='Mecanizada'?38:30,tractorValue:mode==='Mecanizada'?0:12000000,implementValue:mode==='Mecanizada'?0:2000000})
 const result=runFarmExample(input)
 const fields=[['harvestKg','Cosecha prevista (kg)'],['europaQq','Europa (quintales de 46 kg)'],['usaQq','EEUU (quintales de 46 kg)'],['secondBoxes','Segunda (cajas)'],['secondBoxKg','Kg por caja de segunda'],['rejectSacks','Rechazo (sacos)'],['rejectSackKg','Kg por saco de rechazo'],['wasteKg','Desperdicio normal (kg)'],['seedUnits','Semilla/estacas vendidas (unidades)'],['europaPrice','Precio Europa (₡/quintal)'],['usaPrice','Precio EEUU (₡/quintal)'],['secondPrice','Precio segunda (₡/caja)'],['rejectPrice','Precio rechazo (₡/saco)'],['seedPrice','Precio semilla (₡/unidad)'],['operatingCosts','Costos agrícolas totales (₡)'],['mechanization','Mecanización incluida en los costos (₡)'],['rental','Alquiler del período (₡)'],['ownerPercent','Porcentaje del propietario (%)'],['tractorValue','Valor actual de tractores propios (₡)'],['implementValue','Valor actual de implementos propios (₡)'],['stockValue','Insumos disponibles al cierre (₡)']]
 return <section className="panel farm-panel farm-example"><div className="panelhead"><div><h3>Ejercicio y chequeo de finca</h3><p>Ejemplo ilustrativo editable. Los importes son supuestos y no cambian sus bancos, inventarios ni cuentas.</p></div><button className="primary" onClick={()=>setOpen(v=>!v)}>{open?'Cerrar ejercicio':'Abrir ejemplo completo'}</button></div>
 {open&&<><div className="finance-links">{[['Porcentaje','César · 30%'],['Mecanizada','Víctor · 38% y tierra mecanizada'],['Alquilada','Ejemplo alquilada'],['Propia','Ejemplo propia']].map(([mode,label])=><button key={mode} onClick={()=>preset(mode)}>{label}</button>)}</div><div className="formgrid"><label>Pérdida adicional antes de vender (%)<input type="number" min="0" max="100" step="1" value={input.lossPercent} onChange={e=>change('lossPercent',e.target.value)}/></label><label>Porcentaje cobrado (%)<input type="number" min="0" max="100" step="1" value={input.paidPercent} onChange={e=>change('paidPercent',e.target.value)}/></label></div><details><summary>Editar cosecha, precios, costos e inversión</summary><div className="formgrid">{fields.map(([k,label])=><label key={k}>{label}<input type="number" min="0" step="0.01" value={input[k]} onChange={e=>change(k,e.target.value)}/></label>)}</div></details>
 {result.errors.length?<div className="formerror" role="alert">{result.errors.map(e=><p key={e}>{e}</p>)}</div>:<div aria-live="polite"><p><b>{input.mode==='Mecanizada'?`Acuerdo del ${input.ownerPercent}% con mecanización aportada por el dueño`:input.mode==='Porcentaje'?`Acuerdo del ${input.ownerPercent}% sobre ventas brutas`:input.mode==='Alquilada'?'Alquiler del período':'Propiedad propia'}</b></p><div className="farm-metrics"><span>Ventas brutas <b>{cash(result.revenue)}</b></span><span>Participación del dueño <b>{cash(result.owner)}</b></span><span>Costos + alquiler <b>{cash(result.costs+result.rent)}</b></span><span>Resultado provisional <b>{cash(result.net)}</b></span></div>
 <details open><summary>Productos, subproductos y balance de cosecha</summary>{result.lines.map(l=><div className="farm-line" key={l.name}><span>{l.name} · {l.quantity.toLocaleString('es-CR',{maximumFractionDigits:3})} {l.unit} × {cash(l.price)}</span><b>{cash(l.revenue)}</b></div>)}<p>Raíces vendidas: {result.rootSalesKg.toLocaleString('es-CR')} kg · Desperdicio normal: {result.normalWasteKg.toLocaleString('es-CR')} kg · Pérdida adicional: {result.lostKg.toLocaleString('es-CR')} kg · Total: {Number(input.harvestKg).toLocaleString('es-CR')} kg.</p><p>Las estacas son un producto separado de las raíces. Las segundas y rechazos de este ejemplo se venden directamente en finca y no reutilizan kilos entregados a la exportadora.</p></details>
 <div className="farm-metrics"><span>Cobrado <b>{cash(result.collected)}</b></span><span>Por cobrar <b>{cash(result.receivable)}</b></span><span>Activos + bodega + cultivo, antes de cosechar <b>{cash(result.beforeHarvest)}</b></span><span>Activos + bodega, después del cierre <b>{cash(result.afterClosedFixedAndStock)}</b></span></div><p>Después del cierre, la cuenta por cobrar se muestra por separado. La utilidad no equivale al efectivo disponible; faltan pagos y cobros según sus fechas.</p>
 <details><summary>Pasos del ejemplo completo</summary><ol><li>Recibir insumos: inventario y deuda al proveedor, sin gastar todavía el cultivo.</li><li>Trasladar entre bodegas: conservar cantidad y valor, sin generar una segunda compra.</li><li>Consumir por lote: bajar existencia y registrar el costo agrícola una vez.</li><li>Registrar planilla, combustible y mantenimiento; asignar los gastos compartidos.</li><li>Cosechar y clasificar; cuadrar todos los kilos, incluido desperdicio.</li><li>Entregar primera a la exportadora y registrar ventas directas separadas de subproductos.</li><li>Calcular el porcentaje del propietario sobre las ventas brutas de su propiedad.</li><li>Aplicar cobros y pagos; conservar los saldos pendientes.</li><li>Cerrar el cultivo y conservar resultado, pérdidas y cantidades remanentes.</li></ol><p>Los pasos de liquidación del propietario, ventas directas de finca y cierre formal muestran el comportamiento que falta implementar; aquí se calculan como simulación.</p></details></div>}
 <details open><summary>Chequeo realizado · {auditDate}</summary><p>16 controles ejecutados en base de datos con rol de administrador. La prueba termina en reversión y no conserva operaciones ficticias. Los cálculos del ejemplo son pruebas separadas; no sustituyen una prueba completa en pantalla.</p>{auditedChecks.map(([name,status,detail])=><article className="farm-lot" key={name}><b>{status} · {name}</b><p>{detail}</p></article>)}</details>
 <details><summary>Qué agregar y qué simplificar</summary>{farmPriorities.map(([priority,name,detail])=><article className="farm-lot" key={name}><b>{priority} · {name}</b><p>{detail}</p></article>)}</details>
 </>}
 </section>
}
