import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
import {cash} from './finance'
import {costaRicaToday} from './weekly-model'
const blank=()=>({lote_id:'',colaborador:'',periodo_inicio:costaRicaToday(),periodo_fin:costaRicaToday(),fecha_pago:costaRicaToday(),dias:'1',tarifa_diaria:'',rebajos:'0',observaciones:''})
export default function FarmPayroll({go}){
 const [form,setForm]=useState(blank),[editing,setEditing]=useState(null),[rows,setRows]=useState([]),[lots,setLots]=useState([]),[workers,setWorkers]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{const results=await Promise.all([supabase.from('planillas_finca').select('*').order('periodo_inicio',{ascending:false}),supabase.from('lotes_finca').select('id,nombre,anio,fincas(nombre)').order('anio',{ascending:false}),supabase.from('trabajadores').select('nombre').eq('activo',true).order('nombre')]);const failed=results.find(r=>r.error);if(failed){setError(failed.error.message);return}setRows(results[0].data);setLots(results[1].data);setWorkers(results[2].data);setError('')}
 useEffect(()=>{load()},[])
 const change=(key,value)=>setForm(f=>({...f,[key]:value}))
 const gross=Number(form.dias)*Number(form.tarifa_diaria),net=gross-Number(form.rebajos)
 const save=async()=>{if(!form.lote_id||!form.colaborador.trim()||!form.periodo_inicio||form.periodo_fin<form.periodo_inicio||!form.fecha_pago||!Number.isFinite(gross)||Number(form.dias)<=0||Number(form.tarifa_diaria)<=0||Number(form.rebajos)<0||net<=0){setError('Complete finca y lote, colaborador, período, fecha de pago, días y tarifa. El neto debe ser positivo.');return}setBusy(true);setError('');const payload={...form,colaborador:form.colaborador.trim(),dias:Number(form.dias),tarifa_diaria:Number(form.tarifa_diaria),rebajos:Number(form.rebajos)};const result=editing?await supabase.from('planillas_finca').update(payload).eq('id',editing).select('id').single():await supabase.from('planillas_finca').insert(payload).select('id').single();setBusy(false);if(result.error){setError(result.error.message);return}setEditing(null);setForm(blank());load()}
 const lotLabel=id=>{const lot=lots.find(l=>l.id===id);return lot?`${lot.fincas?.nombre} · ${lot.nombre} · ${lot.anio}`:'Lote'}
 return <><div className="modulebar"><p>Agrosolano · Cada registro asigna el costo bruto a su lote y genera una cuenta por pagar por el neto. Registre el pago desde los bancos de Agrosolano.</p><button onClick={()=>go('Cuentas por pagar')}>Ver cuentas por pagar</button></div>{error&&<p className="formerror" role="alert">{error}</p>}<section className="panel"><h3>{editing?'Editar planilla de finca':'Nueva planilla de finca'}</h3><div className="formgrid"><label>Finca y lote<select value={form.lote_id} onChange={e=>change('lote_id',e.target.value)}><option value="">Seleccione</option>{lots.map(l=><option key={l.id} value={l.id}>{lotLabel(l.id)}</option>)}</select></label><label>Colaborador o responsable de cuadrilla<input list="colaboradores-finca" value={form.colaborador} onChange={e=>change('colaborador',e.target.value)}/><datalist id="colaboradores-finca">{workers.map(w=><option key={w.nombre} value={w.nombre}/>)}</datalist></label>{[['periodo_inicio','Desde'],['periodo_fin','Hasta'],['fecha_pago','Fecha prevista de pago']].map(([key,label])=><label key={key}>{label}<input type="date" value={form[key]} onChange={e=>change(key,e.target.value)}/></label>)}{[['dias','Días trabajados'],['tarifa_diaria','Tarifa diaria (₡)'],['rebajos','Rebajos (₡)']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="0.01" value={form[key]} onChange={e=>change(key,e.target.value)}/></label>)}<label className="wide">Trabajo y observaciones<input value={form.observaciones} onChange={e=>change('observaciones',e.target.value)}/></label></div><p>Bruto: <b>{cash(gross)}</b> · Neto por pagar: <b>{cash(net)}</b></p><button className="primary" disabled={busy} onClick={save}>{busy?'Guardando…':'Guardar planilla y cuenta por pagar'}</button>{editing&&<button onClick={()=>{setEditing(null);setForm(blank())}}>Cancelar</button>}</section><section className="workers-panel"><h3>Planillas registradas por finca y lote</h3>{rows.map(row=><article key={row.id}><div><b>{row.colaborador} · {lotLabel(row.lote_id)}</b><span>{row.periodo_inicio} a {row.periodo_fin} · {row.dias} días · {row.observaciones}</span><span>Bruto {cash(row.bruto)} · Rebajos {cash(row.rebajos)} · Pago previsto {row.fecha_pago}</span></div><strong>{cash(row.neto)}</strong><button onClick={()=>{setEditing(row.id);setForm(Object.fromEntries(Object.keys(blank()).map(k=>[k,row[k]??''])));setError('')}}>Editar</button></article>)}{!rows.length&&<p>Sin planillas de finca registradas.</p>}</section></>
}
