import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
import {cash} from './finance'
export default function FarmTractorActivity({asset,lots,onChange}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tractor,setTractor]=useState(null)
 const load=async()=>{const [a,b]=await Promise.all([supabase.from('actividades_tractor').select('*').eq('tractor_id',asset.tractor_operativo_id).order('fecha',{ascending:false}),supabase.from('tractores_finca').select('*').eq('id',asset.tractor_operativo_id).single()]);if(a.error||b.error)setError((a.error||b.error).message);else{setRows(a.data||[]);setTractor(b.data);setError('')}}
 useEffect(()=>{load()},[asset.tractor_operativo_id,asset.finca_id])
 const create=()=>setForm({finca_id:asset.finca_id,tractor_id:asset.tractor_operativo_id,lote_id:'',fecha:new Date().toLocaleDateString('en-CA',{timeZone:'America/Costa_Rica'}),tipo:'Combustible',descripcion:'',horometro:tractor?.horometro||'',litros:'',monto:'',beneficiario:'',fecha_pago:'',referencia:''})
 const save=async()=>{if(!form.descripcion.trim()||!form.fecha||(form.tipo==='Combustible'&&Number(form.litros)<=0)){setError('Complete fecha, detalle y litros positivos para combustible.');return}const p=Object.fromEntries(['finca_id','tractor_id','lote_id','fecha','tipo','descripcion','horometro','litros','monto','beneficiario','fecha_pago','referencia'].map(k=>[k,form[k]===''?null:form[k]]));p.monto=Number(p.monto||0);for(const k of ['horometro','litros'])if(p[k]!=null)p[k]=Number(p[k]);if(p.tipo!=='Combustible')p.litros=null;setBusy(true);const r=await(form.id?supabase.from('actividades_tractor').update(p).eq('id',form.id):supabase.from('actividades_tractor').insert(p)).select('id').single();setBusy(false);if(r.error){setError(r.error.message);return}setForm(null);load();onChange()}
 return <details><summary>Combustible y mantenimiento · Horómetro {tractor?.horometro??'Pendiente'} h</summary>{error&&<p className="formerror">{error}</p>}<button onClick={create}>Registrar trabajo o mantenimiento</button>{form&&<div className="formgrid"><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}>{['Combustible','Mantenimiento','Llantas','Trabajo'].map(v=><option key={v}>{v}</option>)}</select></label><label>Lote (opcional)<select value={form.lote_id||''} onChange={e=>setForm({...form,lote_id:e.target.value})}><option value="">General de la finca</option>{lots.filter(l=>l.finca_id===form.finca_id).map(l=><option key={l.id} value={l.id}>{l.nombre}</option>)}</select></label>{[['fecha','Fecha','date'],['descripcion','Detalle','text'],['horometro','Horómetro (horas)','number'],...(form.tipo==='Combustible'?[['litros','Litros','number']]:[]),['monto','Costo (CRC)','number'],['beneficiario','Proveedor o beneficiario (genera cuenta por pagar)','text'],['fecha_pago','Vencimiento del pago','date'],['referencia','Referencia','text']].map(([k,label,type])=><label key={k}>{label}<input type={type} min={type==='number'?0:undefined} step="0.01" value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button disabled={busy} onClick={save}>Guardar actividad</button><button onClick={()=>setForm(null)}>Cancelar</button></div>}<p>La actividad genera un solo costo; asígnelo al cultivo o repártalo si el trabajo fue compartido. El combustible se registra en litros. La ficha conserva el historial al trasladar el tractor.</p>{rows.map(r=><div className="farm-line" key={r.id}><span>{r.fecha} · {r.tipo} · {r.descripcion}{r.litros?` · ${r.litros} litros`:''} · {r.horometro??'—'} h</span><b>{cash(r.monto)}</b><button onClick={()=>setForm({...r})}>Editar actividad</button></div>)}</details>
}
