import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
import {cash} from './finance'
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Costa_Rica'})
const blankMove=()=>({solicitud:crypto.randomUUID(),fecha:today(),tipo:'Cosecha',producto:'',calidad:'Primera',unidad:'kg',cantidad:'',cantidad_comercial:'',unidad_comercial:'Quintales',precio_unitario:'',moneda:'CRC',tipo_cambio:440,comprador:'',orden_compra_id:'',observaciones:'',motivo_correccion:''})
const num=x=>Number(x||0)
export default function FarmCycles({farms,lots,costs,onChange}){
 const [rows,setRows]=useState([]),[stocks,setStocks]=useState([]),[moves,setMoves]=useState([]),[orders,setOrders]=useState([]),[properties,setProperties]=useState([]),[accounts,setAccounts]=useState([]),[applications,setApplications]=useState([]),[liqs,setLiqs]=useState([]),[closures,setClosures]=useState([]),[shares,setShares]=useState([])
 const [selected,setSelected]=useState(''),[cycle,setCycle]=useState(null),[move,setMove]=useState(null),[carry,setCarry]=useState(null),[allocation,setAllocation]=useState(null),[expense,setExpense]=useState(null),[closing,setClosing]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{
  const tables=[['resumen_ciclos_finca',setRows],['saldos_cosecha_finca',setStocks],['movimientos_cosecha_finca',setMoves],['propiedades_finca',setProperties],['liquidaciones_dueno_finca',setLiqs],['cierres_ciclo_finca',setClosures],['repartos_costos_finca',setShares]]
  const result=await Promise.all(tables.map(async([t,set])=>{const r=await supabase.from(t).select('*');if(!r.error)set(r.data||[]);return r.error}))
  const extra=await Promise.all([supabase.from('ordenes_compra').select('id,codigo,finca_lote_id,ciclo_finca_id,estado').eq('tipo_compra','Cosecha propia').neq('estado','Anulada'),supabase.from('cuentas_manuales').select('id,tipo,monto,moneda,contraparte,liquidacion_dueno_id,movimiento_cosecha_id').eq('empresa','agro_solano'),supabase.from('aplicaciones_bancarias').select('origen,origen_id,monto').in('origen',['cuenta_manual_pagar','cuenta_manual_cobrar'])])
  if(!extra[0].error)setOrders(extra[0].data||[]);if(!extra[1].error)setAccounts(extra[1].data||[]);if(!extra[2].error)setApplications(extra[2].data||[])
  const e=result.find(Boolean)||extra.find(r=>r.error)?.error;if(e)setError(e.message)
 }
 useEffect(()=>{load()},[costs])
 const current=rows.find(c=>c.id===selected),open=current?.estado==='Abierto',stock=stocks.filter(s=>s.ciclo_id===selected),history=moves.filter(m=>m.ciclo_id===selected).sort((a,b)=>b.fecha.localeCompare(a.fecha)||b.creado_en.localeCompare(a.creado_en))
 const run=async(fn,success)=>{setBusy(true);setError('');setMessage('');try{const r=await fn();if(r.error)throw r.error;await load();await onChange();setMessage(success);return true}catch(e){setError(e.message||String(e));return false}finally{setBusy(false)}}
 const cycleForm=(r=null)=>setCycle(r?{...r}:{lote_id:'',nombre:'',producto:'Yuca',fecha_siembra:today(),fecha_cosecha_estimada:'',area_ha:'',porcentaje_propietario:0,propietario:'',observaciones:''})
 const setLot=value=>{const l=lots.find(l=>l.id===value),p=properties.find(p=>p.id===l?.propiedad_id);setCycle({...cycle,lote_id:value,producto:l?.producto||'Yuca',porcentaje_propietario:p?.porcentaje_propietario||0,propietario:p?.propietario||''})}
 const saveCycle=async()=>{if(!cycle.lote_id||!cycle.nombre.trim()||!cycle.producto.trim()||!cycle.fecha_siembra){setError('Complete lote, nombre del cultivo, producto y fecha de siembra.');return}
  const p=Object.fromEntries(['lote_id','nombre','producto','fecha_siembra','fecha_cosecha_estimada','area_ha','porcentaje_propietario','propietario','observaciones'].map(k=>[k,cycle[k]===''?null:cycle[k]]));p.porcentaje_propietario=num(p.porcentaje_propietario);if(p.area_ha)p.area_ha=Number(p.area_ha)
  if(await run(()=>cycle.id?supabase.from('ciclos_finca').update(p).eq('id',cycle.id).select('id').single():supabase.from('ciclos_finca').insert(p).select('id').single(),'Cultivo guardado.'))setCycle(null)
 }
 const saveMove=async()=>{
  if(!move.producto.trim()||!move.calidad.trim()||num(move.cantidad)<=0){setError('Complete producto, calidad y cantidad positiva.');return}
  if(move.tipo==='Venta en campo'&&(!move.comprador.trim()||num(move.precio_unitario)<=0||num(move.cantidad_comercial)<=0)){setError('Complete comprador, cantidad facturada y precio positivo.');return}
  const payload={...Object.fromEntries(Object.keys(blankMove()).map(k=>[k,move[k]??null])),ciclo_id:selected,cantidad:num(move.cantidad),cantidad_comercial:move.tipo==='Venta en campo'?num(move.cantidad_comercial):null,precio_unitario:move.tipo==='Venta en campo'?num(move.precio_unitario):null,tipo_cambio:move.moneda==='CRC'?1:num(move.tipo_cambio),orden_compra_id:move.tipo==='Entrega a exportadora'?move.orden_compra_id||null:null,comprador:move.tipo==='Venta en campo'?move.comprador.trim():null}
  if(await run(async()=>{if(move.id)return supabase.from('movimientos_cosecha_finca').update(payload).eq('id',move.id).select('id').single();const found=await supabase.from('movimientos_cosecha_finca').select('id').eq('solicitud',move.solicitud).maybeSingle();if(found.error||found.data)return found;return supabase.from('movimientos_cosecha_finca').insert(payload).select('id').single()},'Movimiento guardado. La venta en campo aparece en Cuentas por cobrar de Agrosolano.'))setMove(null)
 }
 const costRows=costs.filter(k=>k.ciclo_id===selected),pending=costs.filter(k=>k.lote_id===current?.lote_id&&!k.ciclo_id),general=costs.filter(k=>k.finca_id===current?.finca_id&&!k.lote_id&&!k.ciclo_id)
 const paid=a=>applications.filter(p=>p.origen_id===a.id&&p.origen===`cuenta_manual_${a.tipo}`).reduce((s,p)=>s+num(p.monto),0)
 const linkedAccounts=accounts.filter(a=>a.liquidacion_dueno_id===liqs.find(l=>l.ciclo_id===selected)?.id||history.some(m=>m.id===a.movimiento_cosecha_id))
 const totalShare=costId=>shares.filter(r=>r.costo_id===costId).reduce((s,r)=>s+num(r.monto),0)
 return <section className="panel farm-panel"><div className="panelhead"><div><h3>Cultivos, cosechas y liquidación</h3><p>Cada siembra tiene su propio ciclo. El dueño recibe el porcentaje pactado de la venta bruta en campo, antes de gastos.</p></div><button onClick={()=>cycleForm()}>Nuevo cultivo</button><button disabled={busy} onClick={load}>Actualizar</button></div>
 {error&&<p className="formerror" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {cycle&&<div className="formgrid"><label>Lote<select disabled={Boolean(cycle.id)} value={cycle.lote_id} onChange={e=>setLot(e.target.value)}><option value="">Seleccione</option>{lots.map(l=><option key={l.id} value={l.id}>{farms.find(f=>f.id===l.finca_id)?.nombre} · {properties.find(p=>p.id===l.propiedad_id)?.nombre} · {l.nombre}</option>)}</select></label>{[['nombre','Nombre del cultivo','text'],['producto','Producto','text'],['fecha_siembra','Fecha de siembra','date'],['fecha_cosecha_estimada','Cosecha estimada','date'],['area_ha','Área (hectáreas)','number'],['porcentaje_propietario','Dueño: porcentaje de venta bruta EN CAMPO','number'],['propietario','Nombre del dueño','text'],['observaciones','Observaciones','text']].map(([k,label,type])=><label key={k}>{label}<input type={type} step="0.001" min={type==='number'?0:undefined} max={k==='porcentaje_propietario'?100:undefined} value={cycle[k]??''} onChange={e=>setCycle({...cycle,[k]:e.target.value})}/></label>)}<button className="primary" disabled={busy} onClick={saveCycle}>Guardar cultivo</button><button onClick={()=>setCycle(null)}>Cancelar</button></div>}
 <label>Seleccione el cultivo<select value={selected} onChange={e=>{setSelected(e.target.value);setMove(null);setCarry(null);setClosing(null);setAllocation(null);setError('');setMessage('')}}><option value="">Seleccione para ver su control completo</option>{rows.sort((a,b)=>b.fecha_siembra.localeCompare(a.fecha_siembra)).map(c=><option key={c.id} value={c.id}>{farms.find(f=>f.id===c.finca_id)?.nombre} · {c.lote_nombre} · {c.nombre} · {c.estado}</option>)}</select></label>
 {!rows.length&&<p>Cree un cultivo para comenzar. Los gastos y compras anteriores se conservan; usted decide cuáles corresponden a este cultivo.</p>}
 {current&&<><h4>{current.nombre} · {current.producto} · {current.estado}</h4><div className="farm-metrics"><span>Venta bruta en campo <b>{cash(current.ventas_brutas_crc)}</b></span><span>Dueño ({current.porcentaje_propietario}%) <b>{cash(current.dueno_crc)}</b></span><span>Gastos del cultivo <b>{cash(current.costos_crc)}</b></span><span>Resultado <b>{cash(num(current.ventas_brutas_crc)-num(current.dueno_crc)-num(current.costos_crc))}</b></span></div><p>Este resultado se calcula por ventas, aunque todavía no se hayan cobrado. {current.compras_pendientes>0?`${current.compras_pendientes} compras pendientes de liquidar; resultado provisional.`:''}</p>
 <div className="panelhead">{open&&<><button onClick={()=>cycleForm(current)}>Editar cultivo y porcentaje</button><button onClick={()=>setMove({...blankMove(),producto:current.producto})}>Registrar cosecha o salida</button><button onClick={()=>setExpense({fecha:today(),categoria:'Planilla',descripcion:'',monto:'',general:false})}>Registrar gasto</button><button disabled={busy||num(current.porcentaje_propietario)===0} onClick={()=>run(()=>supabase.rpc('liquidar_dueno_finca',{p_ciclo:selected,p_fecha:today()}),'Liquidación actualizada. Pague al dueño desde Bancos de Agrosolano; no vuelva a registrar este monto como gasto manual.')}>Generar / actualizar liquidación del dueño</button></>}<button onClick={()=>setClosing({motivo:''})}>{open?'Cerrar cultivo':'Reabrir cultivo'}</button></div>
 {move&&<div className="formgrid"><label>Movimiento<select disabled={Boolean(move.id)} value={move.tipo} onChange={e=>setMove({...move,tipo:e.target.value})}>{['Cosecha','Venta en campo','Entrega a exportadora','Pérdida','Uso como semilla'].map(v=><option key={v}>{v}</option>)}</select></label><label>Fecha<input type="date" value={move.fecha} onChange={e=>setMove({...move,fecha:e.target.value})}/></label><label>Producto<input disabled={Boolean(move.id)} value={move.producto} onChange={e=>setMove({...move,producto:e.target.value})} placeholder="Yuca, estacas…"/></label><label>Calidad<input disabled={Boolean(move.id)} list="calidades-finca" value={move.calidad} onChange={e=>setMove({...move,calidad:e.target.value})}/><datalist id="calidades-finca">{['Primera','Europa','Estados Unidos','Segunda gruesa','Segunda menuda','Rechazo','Estacas'].map(v=><option key={v}>{v}</option>)}</datalist></label><label>Cantidad física<input type="number" min="0.001" step="0.001" value={move.cantidad} onChange={e=>setMove({...move,cantidad:e.target.value})}/></label><label>Unidad física<select disabled={Boolean(move.id)} value={move.unidad} onChange={e=>setMove({...move,unidad:e.target.value})}><option>kg</option><option>Unidades</option></select></label>
 {!move.id&&move.tipo!=='Cosecha'&&<label className="wide">Elegir existencia<select value="" onChange={e=>{const s=stock[Number(e.target.value)];if(s)setMove({...move,producto:s.producto,calidad:s.calidad,unidad:s.unidad,cantidad:s.saldo})}}><option value="">Seleccione un producto disponible</option>{stock.map((s,i)=>s.saldo>0&&<option key={i} value={i}>{s.producto} · {s.calidad} · {s.saldo} {s.unidad}</option>)}</select></label>}
 {move.tipo==='Venta en campo'&&<><label>Comprador<input value={move.comprador} onChange={e=>setMove({...move,comprador:e.target.value})}/></label><label>Cantidad facturada<input type="number" step="0.001" min="0.001" value={move.cantidad_comercial} onChange={e=>setMove({...move,cantidad_comercial:e.target.value})}/></label><label>Unidad facturada<select value={move.unidad_comercial} onChange={e=>setMove({...move,unidad_comercial:e.target.value})}>{['Quintales','Cajas','Sacos','kg','Unidades'].map(v=><option key={v}>{v}</option>)}</select></label><label>Precio por unidad<input type="number" step="0.01" min="0.01" value={move.precio_unitario} onChange={e=>setMove({...move,precio_unitario:e.target.value})}/></label><label>Moneda<select value={move.moneda} onChange={e=>setMove({...move,moneda:e.target.value})}><option>CRC</option><option>USD</option></select></label>{move.moneda==='USD'&&<label>Tipo de cambio de la venta<input type="number" min="0.0001" step="0.0001" value={move.tipo_cambio} onChange={e=>setMove({...move,tipo_cambio:e.target.value})}/></label>}<p className="wide">Total: {cash(num(move.cantidad_comercial)*num(move.precio_unitario),move.moneda)}. La cantidad física rebaja el inventario; la cantidad facturada permite cajas o sacos con su peso real. Un quintal equivale a 46 kg.</p></>}
 {move.tipo==='Entrega a exportadora'&&<><label className="wide">Orden de compra de cosecha propia<select disabled={Boolean(move.id)} value={move.orden_compra_id} onChange={e=>setMove({...move,orden_compra_id:e.target.value})}><option value="">Seleccione</option>{orders.filter(o=>o.finca_lote_id===current.lote_id&&(!o.ciclo_finca_id||o.ciclo_finca_id===selected)).map(o=><option key={o.id} value={o.id}>{o.codigo}</option>)}</select></label><p className="wide">El valor se toma de las boletas liquidadas en campo antes de rebajos. La orden se cuenta una sola vez, aunque tenga varias entregas. Registre en Órdenes de compra la compra de cosecha propia de este lote.</p></>}
 {move.id&&<label className="wide">Motivo de la corrección<input value={move.motivo_correccion||''} onChange={e=>setMove({...move,motivo_correccion:e.target.value})}/></label>}<label className="wide">Observaciones / motivo<input value={move.observaciones} onChange={e=>setMove({...move,observaciones:e.target.value})}/></label><button disabled={busy} className="primary" onClick={saveMove}>Guardar movimiento</button><button onClick={()=>setMove(null)}>Cancelar</button></div>}
 {expense&&<div className="formgrid"><label>Fecha<input type="date" value={expense.fecha} onChange={e=>setExpense({...expense,fecha:e.target.value})}/></label><label>Tipo de gasto<select value={expense.categoria} onChange={e=>setExpense({...expense,categoria:e.target.value})}>{['Planilla','Insumos','Combustible','Maquinaria','Alquiler','Cercas','Caminos','Flete','Otro'].map(v=><option key={v}>{v}</option>)}</select></label><label>Monto en CRC<input type="number" step="0.01" min="0.01" value={expense.monto} onChange={e=>setExpense({...expense,monto:e.target.value})}/></label><label>Detalle<input value={expense.descripcion} onChange={e=>setExpense({...expense,descripcion:e.target.value})}/></label><label><input type="checkbox" checked={expense.general} onChange={e=>setExpense({...expense,general:e.target.checked})}/> Gasto compartido de esta administración (repartir después)</label><p>Este registro anota un costo. Los pagos se registran desde Finanzas. Si el insumo, la planilla o el tractor ya generó el gasto, asígnelo abajo para que se cuente una sola vez.</p><button disabled={busy} onClick={async()=>{if(num(expense.monto)<=0){setError('Indique un monto positivo.');return}if(await run(()=>supabase.from('costos_finca').insert({finca_id:current.finca_id,lote_id:expense.general?null:current.lote_id,ciclo_id:expense.general?null:selected,fecha:expense.fecha,categoria:expense.categoria,descripcion:expense.descripcion,monto:num(expense.monto)}),'Gasto guardado.'))setExpense(null)}}>Guardar gasto</button><button onClick={()=>setExpense(null)}>Cancelar</button></div>}
 <details open><summary>Producto disponible, pérdidas y arrastres</summary>{stock.length?stock.map((s,i)=><div className="farm-line" key={i}><span>{s.producto} · {s.calidad} · Cosechado {s.cosechado} {s.unidad} · Pérdida {s.perdido} {s.unidad}</span><b>Disponible {s.saldo} {s.unidad}</b>{open&&s.saldo>0&&<button onClick={()=>setCarry({...s,solicitud:crypto.randomUUID(),destino:'',cantidad:s.saldo,costo:0,motivo:''})}>Arrastrar a otro cultivo</button>}</div>):<p>Sin cosechas registradas.</p>}
 {carry&&<div className="formgrid"><p>{carry.producto} · {carry.calidad}: disponible {carry.saldo} {carry.unidad}</p><label>Cultivo destino<select value={carry.destino} onChange={e=>setCarry({...carry,destino:e.target.value})}><option value="">Seleccione</option>{rows.filter(c=>c.id!==selected&&c.estado==='Abierto'&&c.finca_id===current.finca_id).map(c=><option key={c.id} value={c.id}>{c.lote_nombre} · {c.nombre}</option>)}</select></label><label>Cantidad a arrastrar<input type="number" min="0.001" step="0.001" max={carry.saldo} value={carry.cantidad} onChange={e=>setCarry({...carry,cantidad:e.target.value})}/></label><label>Costo agrícola que acompaña el arrastre (CRC)<input type="number" min="0" step="0.01" max={current.costos_crc} value={carry.costo} onChange={e=>setCarry({...carry,costo:e.target.value})}/></label><label>Motivo<input value={carry.motivo} onChange={e=>setCarry({...carry,motivo:e.target.value})}/></label><p>El costo pasa del cultivo origen al destino. No es venta ni vuelve a generar deuda; ambas partes conservan el historial.</p><button disabled={busy} onClick={async()=>{if(await run(()=>supabase.rpc('arrastrar_cosecha_finca',{p_solicitud:carry.solicitud,p_origen:selected,p_destino:carry.destino||null,p_producto:carry.producto,p_calidad:carry.calidad,p_unidad:carry.unidad,p_cantidad:num(carry.cantidad),p_costo:num(carry.costo),p_fecha:today(),p_motivo:carry.motivo}),'Producto y costo arrastrados sin duplicar inversión.'))setCarry(null)}}>Guardar arrastre</button><button onClick={()=>setCarry(null)}>Cancelar</button></div>}</details>
 <details><summary>Gastos del cultivo y gastos por asignar</summary>{costRows.map(k=><div className="farm-line" key={k.id}><span>{k.fecha} · {k.categoria} · {k.descripcion}</span><b>{cash(k.monto)}</b>{open&&<button disabled={busy} onClick={()=>run(()=>supabase.from('costos_finca').update({ciclo_id:null}).eq('id',k.id).select('id').single(),'Gasto separado del cultivo; se conserva su registro de origen.')}>Quitar del cultivo</button>}</div>)}{pending.map(k=><div className="farm-line" key={k.id}><span>Pendiente · {k.fecha} · {k.categoria} · {k.descripcion} · {cash(k.monto)}</span>{open&&<button disabled={busy} onClick={()=>run(()=>supabase.from('costos_finca').update({ciclo_id:selected}).eq('id',k.id).select('id').single(),'Gasto asignado sin duplicarlo.')}>Asignar a este cultivo</button>}</div>)}
 {shares.filter(r=>r.ciclo_id===selected).map(r=><div className="farm-line" key={r.costo_id}><span>Gasto compartido: {costs.find(k=>k.id===r.costo_id)?.descripcion}</span><b>{cash(r.monto)}</b></div>)}{general.map(k=><div className="farm-line" key={k.id}><span>General · {k.fecha} · {k.categoria} · {k.descripcion} · {cash(k.monto)} · por repartir {cash(num(k.monto)-totalShare(k.id))}</span>{open&&<button onClick={()=>setAllocation({costo:k,partes:Object.fromEntries(rows.filter(c=>c.finca_id===current.finca_id&&c.estado==='Abierto').map(c=>[c.id,shares.find(r=>r.costo_id===k.id&&r.ciclo_id===c.id)?.monto||'']))})}>Repartir entre cultivos</button>}</div>)}
 {allocation&&<div className="formgrid"><p>Gasto original: {cash(allocation.costo.monto)}. Repartido: {cash(Object.values(allocation.partes).reduce((s,v)=>s+num(v),0))}.</p><button onClick={()=>{const cs=rows.filter(c=>Object.hasOwn(allocation.partes,c.id)),area=cs.reduce((s,c)=>s+num(c.area_ha),0);if(!area){setError('Anote las hectáreas de los cultivos para repartir por área.');return}let remaining=Math.round(num(allocation.costo.monto)*100);const parts=Object.fromEntries(cs.map((c,i)=>{const cents=i===cs.length-1?remaining:Math.round(num(allocation.costo.monto)*100*num(c.area_ha)/area);remaining-=cents;return[c.id,cents/100]}));setAllocation({...allocation,partes:parts})}}>Distribuir por hectáreas</button>{Object.keys(allocation.partes).map(id=><label key={id}>{rows.find(c=>c.id===id)?.nombre} (CRC)<input type="number" min="0" step="0.01" value={allocation.partes[id]} onChange={e=>setAllocation({...allocation,partes:{...allocation.partes,[id]:e.target.value}})}/></label>)}<button disabled={busy} onClick={async()=>{if(await run(()=>supabase.rpc('repartir_gasto_finca',{p_costo:allocation.costo.id,p_partes:Object.entries(allocation.partes).filter(([,v])=>num(v)>0).map(([ciclo_id,v])=>({ciclo_id,monto:num(v)}))}),'Reparto guardado; el gasto original se registra una sola vez.'))setAllocation(null)}}>Guardar reparto</button><button onClick={()=>setAllocation(null)}>Cancelar</button></div>}</details>
 <details open><summary>Liquidación del dueño y cuentas pendientes</summary>{liqs.some(l=>l.ciclo_id===selected&&(num(l.ventas_brutas_crc)!==num(current.ventas_brutas_crc)||num(l.porcentaje)!==num(current.porcentaje_propietario)))&&<p className="formerror">La liquidación necesita actualizarse después de los cambios de ventas o porcentaje.</p>}<p>Base: {cash(current.ventas_brutas_crc)} × {current.porcentaje_propietario}% = {cash(current.dueno_crc)}. No se descuenta ningún gasto para calcular la participación. El resultado del cultivo resta esta participación una sola vez.</p>{linkedAccounts.map(a=><div className="farm-line" key={a.id}><span>{a.tipo==='pagar'?'Por pagar al dueño':'Por cobrar'} · {a.contraparte} · Total {cash(a.monto,a.moneda)} · Aplicado {cash(paid(a),a.moneda)}</span><b>Saldo {cash(num(a.monto)-paid(a),a.moneda)}</b></div>)}<p>Los cobros y pagos se hacen en Finanzas → Agrosolano → Bancos. Si una liquidación corregida queda por debajo de lo pagado, se genera un reintegro por cobrar al dueño.</p></details>
 {closing&&<div className="formgrid"><label>Motivo de {open?'cierre':'reapertura'}<input value={closing.motivo} onChange={e=>setClosing({motivo:e.target.value})}/></label><p>El cierre conserva una fotografía del resultado, bloquea cambios del cultivo y mantiene pendientes sus cobros y pagos. Para corregir, reabra con motivo.</p><button disabled={busy} onClick={async()=>{if(await run(()=>supabase.rpc('cambiar_estado_ciclo_finca',{p_ciclo:selected,p_cerrar:open,p_motivo:closing.motivo}),open?'Cultivo cerrado. Sus cobros y pagos pendientes siguen en Finanzas.':'Cultivo reabierto; el cierre anterior se conserva.'))setClosing(null)}}>{open?'Cerrar cultivo':'Reabrir cultivo'}</button><button onClick={()=>setClosing(null)}>Cancelar</button></div>}
 <details><summary>Historial de cosechas y cierres</summary>{history.map(m=><div className="farm-line" key={m.id}><span>{m.fecha} · {m.tipo} · {m.producto} · {m.calidad} · {m.observaciones}</span><b>{m.cantidad} {m.unidad}{m.tipo==='Venta en campo'?` · ${cash(num(m.cantidad_comercial)*num(m.precio_unitario),m.moneda)}`:''}</b>{open&&!m.tipo.startsWith('Arrastre')&&<button onClick={()=>setMove({...blankMove(),...Object.fromEntries(Object.entries(m).map(([k,v])=>[k,v??''])),motivo_correccion:''})}>Corregir con motivo</button>}</div>)}{closures.filter(c=>c.ciclo_id===selected).sort((a,b)=>b.fecha.localeCompare(a.fecha)).map(c=><details key={c.id}><summary>{c.accion} · {new Date(c.fecha).toLocaleString('es-CR')} · {c.motivo}</summary><p>Venta en campo {cash(c.resumen.ventas_brutas_crc)} · Dueño {cash(c.resumen.dueno_crc)} · Gastos {cash(c.resumen.costos_crc)} · Resultado {cash(num(c.resumen.ventas_brutas_crc)-num(c.resumen.dueno_crc)-num(c.resumen.costos_crc))}</p></details>)}</details>
 </>}
 </section>
}
