import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
import {cash} from './finance'
import {farmInvestment} from './farm-investment'
const blank=()=>({finca_id:'',tipo:'Implemento agrícola',nombre:'',codigo:'',marca:'',modelo:'',estado:'Bueno',pertenencia:'Propio',cantidad:1,unidad:'Unidad',costo_unitario_crc:'',valor_actual_unitario_crc:'',fecha_adquisicion:'',fecha_valoracion:new Date().toLocaleDateString('en-CA',{timeZone:'America/Costa_Rica'}),caballaje:'',llantas:'',ultimo_mantenimiento:'',proximo_mantenimiento:'',frecuencia_mantenimiento:'',observaciones:''})
export default function FarmAssets({farms,lots,costs,orders,reload}){
 const [assets,setAssets]=useState([]),[stocks,setStocks]=useState(null),[stockError,setStockError]=useState(''),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('')
 const load=async()=>{const [a,b]=await Promise.all([supabase.from('activos_finca').select('*').order('nombre'),supabase.from('existencias_insumos_finca').select('finca_id,insumo_id,cantidad,valor_crc,insumos(nombre,unidad)')]);if(a.error)setError(a.error.message);else{setAssets(a.data||[]);setError('')}if(b.error){setStocks(null);setStockError('La bodega por movimientos no está disponible. El total usa las fichas manuales de insumos y requiere revisión.')}else{setStocks(b.data||[]);setStockError('')}}
 useEffect(()=>{load()},[])
 const change=(key,value)=>setForm(f=>({...f,[key]:value}))
 const save=async()=>{
  if(!form.finca_id||!form.nombre.trim()||!form.fecha_valoracion||!form.unidad.trim()){setError('Complete administración, nombre, unidad y fecha de valoración.');return}
  const payload=Object.fromEntries(Object.keys(blank()).map(k=>[k,form[k]===''?null:form[k]]))
  for(const key of ['cantidad','costo_unitario_crc','valor_actual_unitario_crc','caballaje']){if(payload[key]!=null){payload[key]=Number(payload[key]);if(!Number.isFinite(payload[key])||payload[key]<0){setError('Las cantidades y valores deben ser números positivos o cero.');return}}}
  payload.nombre=form.nombre.trim();payload.unidad=form.unidad.trim();if(form.tipo!=='Insumo disponible'){payload.cantidad=1;payload.unidad='Unidad'}
  setBusy(true);setError('');const query=form.id?supabase.from('activos_finca').update(payload).eq('id',form.id):supabase.from('activos_finca').insert(payload);const {error:e}=await query.select('id').single();setBusy(false);if(e){setError(e.message);return}setForm(null);load()
 }
 const markLot=async(lot,value)=>{setBusy(true);const {error:e}=await supabase.from('lotes_finca').update({inversion_en_curso:value}).eq('id',lot.id).select('id').single();setBusy(false);if(e)setError(e.message);else reload()}
 const markCost=async(cost,value)=>{setBusy(true);const {error:e}=await supabase.from('costos_finca').update({incluir_en_inversion:value}).eq('id',cost.id).select('id').single();setBusy(false);if(e)setError(e.message);else reload()}
 const assignCost=async(cost,lotId)=>{if(!lotId)return;setBusy(true);const {error:e}=await (cost.actividad_tractor_id?supabase.from('actividades_tractor').update({lote_id:lotId}).eq('id',cost.actividad_tractor_id):supabase.from('costos_finca').update({lote_id:lotId}).eq('id',cost.id)).select('id').single();setBusy(false);if(e)setError(e.message);else reload()}
 const visible=farms.filter(f=>(f.activa!==false||assets.some(a=>a.finca_id===f.id))&&(!filter||f.id===filter))
 return <section className="panel farm-panel"><div className="panelhead"><div><h3>Maquinaria, implementos e inversión</h3><p>Tractores e implementos por finca, con costo de adquisición y valor actual. Los insumos disponibles se valoran con su existencia actual.</p></div><button onClick={()=>{setForm(blank());setError('')}}>Agregar ficha</button><button onClick={()=>{load();reload()}}>Actualizar saldos</button></div>{error&&<p className="formerror" role="alert">{error}</p>}
 {stockError&&<p className="formerror">{stockError}</p>}
 <label>Administración<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas</option>{farms.filter(f=>f.activa!==false).map(f=><option key={f.id} value={f.id}>{f.nombre}</option>)}</select></label>
 {form&&<div className="formgrid"><label>Administración<select value={form.finca_id} onChange={e=>change('finca_id',e.target.value)}><option value="">Seleccione</option>{farms.filter(f=>f.activa!==false||f.id===form.finca_id).map(f=><option key={f.id} value={f.id}>{f.nombre}</option>)}</select></label>
 {[['tipo','Tipo',stocks===null||form.tipo==='Insumo disponible'?['Tractor','Implemento agrícola','Insumo disponible']:['Tractor','Implemento agrícola']],['estado','Estado',['Bueno','Regular','En reparación','Fuera de servicio','Retirado']],['pertenencia','Pertenencia',['Propio','Alquilado','De tercero']]].map(([k,label,options])=><label key={k}>{label}<select value={form[k]} onChange={e=>change(k,e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select></label>)}
 {[['nombre','Nombre'],['codigo','Código o serie'],['marca','Marca'],['modelo','Modelo']].map(([k,label])=><label key={k}>{label}<input value={form[k]} onChange={e=>change(k,e.target.value)}/></label>)}
 {form.tipo==='Insumo disponible'&&<><label>Existencia disponible<input type="number" min="0" step="0.001" value={form.cantidad} onChange={e=>change('cantidad',e.target.value)}/></label><label>Unidad<input value={form.unidad} onChange={e=>change('unidad',e.target.value)} placeholder="Kg, litros, sacos…"/></label><p className="wide">Actualice la existencia al usar o recibir insumos. Registre el insumo aplicado como costo del lote y rebájelo aquí para que se cuente una sola vez.</p></>}
 <label>{form.tipo==='Insumo disponible'?'Costo por unidad (₡)':'Costo de adquisición (₡)'}<input type="number" min="0" step="0.01" value={form.costo_unitario_crc} onChange={e=>change('costo_unitario_crc',e.target.value)} placeholder="Pendiente"/></label>
 <label>{form.tipo==='Insumo disponible'?'Valor actual por unidad (₡)':'Valor actual (₡)'}<input type="number" min="0" step="0.01" value={form.valor_actual_unitario_crc} onChange={e=>change('valor_actual_unitario_crc',e.target.value)} placeholder="Pendiente"/></label>
 {[['fecha_adquisicion','Fecha de adquisición'],['fecha_valoracion','Fecha de valoración']].map(([k,label])=><label key={k}>{label}<input type="date" value={form[k]} onChange={e=>change(k,e.target.value)}/></label>)}
 {form.tipo!=='Insumo disponible'&&<>{form.tipo==='Tractor'&&<><label>Caballaje (HP)<input type="number" min="0" step="0.01" value={form.caballaje} onChange={e=>change('caballaje',e.target.value)}/></label><label>Llantas: medidas, estado y cambios<input value={form.llantas} onChange={e=>change('llantas',e.target.value)}/></label></>}{[['ultimo_mantenimiento','Último mantenimiento'],['proximo_mantenimiento','Próximo mantenimiento']].map(([k,label])=><label key={k}>{label}<input type="date" value={form[k]} onChange={e=>change(k,e.target.value)}/></label>)}<label>Frecuencia de mantenimiento<input value={form.frecuencia_mantenimiento} onChange={e=>change('frecuencia_mantenimiento',e.target.value)} placeholder="Horas de uso o intervalo"/></label></>}
 <label className="wide">Observaciones y mantenimiento<textarea value={form.observaciones} onChange={e=>change('observaciones',e.target.value)}/></label><button className="primary" disabled={busy} onClick={save}>Guardar ficha</button><button disabled={busy} onClick={()=>setForm(null)}>Cancelar</button></div>}
 {visible.map(f=>{const result=farmInvestment(f.id,assets,lots,costs,orders,stocks),local=assets.filter(a=>a.finca_id===f.id);return <details key={f.id} open><summary><b>{f.nombre} · Inversión registrada {cash(result.total)}</b></summary><div className="farm-metrics"><span>Tractores <b>{cash(result.tractors)}</b></span><span>Implementos <b>{cash(result.implementsValue)}</b></span><span>Insumos disponibles <b>{cash(result.supplies)}</b></span><span>Cultivos en curso <b>{cash(result.cultivation)}</b></span></div><p>{local.filter(a=>a.tipo==='Tractor'&&a.estado!=='Retirado').length} tractores · {local.filter(a=>a.tipo==='Implemento agrícola'&&a.estado!=='Retirado').length} implementos · {result.activeLots} lotes en curso{result.pending?` · ${result.pending} fichas sin valor actual; total incompleto`:''}</p>
 {stocks!==null&&<details><summary>Existencias de la bodega · {cash(result.supplies)}</summary>{stocks.filter(s=>s.finca_id===f.id).map(s=><div className="farm-line" key={s.insumo_id}><span>{s.insumos?.nombre||'Insumo'} · {Number(s.cantidad).toLocaleString('es-CR')} {s.insumos?.unidad}</span><b>{cash(s.valor_crc)}</b></div>)}{!stocks.some(s=>s.finca_id===f.id)&&<p>Sin existencias registradas por movimientos.</p>}{result.legacySupplies>0&&<p>Hay {result.legacySupplies} fichas manuales de insumos. Se conservan como referencia y no se suman al valor de esta bodega.</p>}</details>}
 {result.unallocatedCount>0&&<details open><summary>Gastos generales pendientes de asignación: {cash(result.unallocatedCosts)}</summary><p>Se muestran aparte. Asigne al lote cuando corresponda; todavía no forman parte de la inversión de un cultivo.</p>{costs.filter(c=>c.finca_id===f.id&&!c.lote_id).map(c=><div className="formgrid" key={c.id}><span>{c.fecha} · {c.categoria} · {c.descripcion} · {cash(c.monto)}</span><label>Asignar este gasto a un lote<select value="" disabled={busy} onChange={e=>assignCost(c,e.target.value)}><option value="">Sin asignar</option>{lots.filter(l=>l.finca_id===f.id).map(l=><option key={l.id} value={l.id}>{l.anio} · {l.nombre}</option>)}</select></label></div>)}</details>}
 {local.map(a=><article className="farm-lot" key={a.id}><div className="panelhead"><h4>{a.nombre} · {a.tipo}</h4><button onClick={()=>setForm({...blank(),...Object.fromEntries(Object.entries(a).map(([k,v])=>[k,v??'']))})}>Editar / trasladar</button></div><p>{a.estado} · {a.pertenencia} · {a.marca} {a.modelo}{a.caballaje?` · ${a.caballaje} HP`:''}</p><p>{a.cantidad} {a.unidad} · Costo {a.costo_unitario_crc==null?'pendiente':cash(Number(a.cantidad)*Number(a.costo_unitario_crc))} · Valor actual {a.valor_actual_unitario_crc==null?'pendiente':cash(Number(a.cantidad)*Number(a.valor_actual_unitario_crc))} · Valoración {a.fecha_valoracion}</p>{a.llantas&&<p>Llantas: {a.llantas}</p>}{a.tipo!=='Insumo disponible'&&<p>Mantenimiento: {a.ultimo_mantenimiento||'Pendiente'} · Próximo: {a.proximo_mantenimiento||'Pendiente'} · {a.frecuencia_mantenimiento}</p>}{a.observaciones&&<p>{a.observaciones}</p>}</article>)}
 <details><summary>Lotes y gastos que forman la inversión en curso</summary>{lots.filter(l=>l.finca_id===f.id).map(l=><div key={l.id}><label><input type="checkbox" disabled={busy} checked={l.inversion_en_curso===true} onChange={e=>markLot(l,e.target.checked)}/> {l.anio} · {l.nombre}: cultivo en curso</label>{l.inversion_en_curso&&costs.filter(c=>c.lote_id===l.id).map(c=><label key={c.id}><input type="checkbox" disabled={busy} checked={c.incluir_en_inversion!==false} onChange={e=>markCost(c,e.target.checked)}/> {c.fecha} · {c.categoria} · {c.descripcion} · {cash(c.monto)}</label>)}</div>)}</details></details>})}
 <p>Total provisional: valor actual de activos propios e insumos disponibles de la bodega, más costos de los lotes marcados en curso, incluida arranca y flete de sus compras. Excluya gastos ya recuperados o compras de activos ya incluidos en sus fichas. Los bienes de terceros y retirados no suman. El terreno y los alquileres futuros pendientes no suman.</p>
 </section>
}
