import React from 'react'
import {X} from 'lucide-react'
const money=(n,c='CRC')=>new Intl.NumberFormat('es-CR',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(n)||0)
const Field=({label,children})=><label>{label}{children}</label>
const Select=({value,onChange,items,placeholder})=><select value={value} onChange={e=>onChange(e.target.value)}><option value="">{placeholder}</option>{items.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select>
const Input=({value,onChange,...rest})=><input {...rest} value={value} onChange={e=>onChange(e.target.value)}/>
export default function FinanceExtra({type,form,setForm,save,close,saving,error,data,accounts}){
  if(!type||!form)return null
  const set=(key,value)=>setForm(old=>({...old,[key]:value}))
  const banks=accounts.filter(a=>a.moneda==='CRC')
  const agro=data.accounts.filter(a=>a.empresa==='agro_solano'&&a.moneda==='CRC')
  const purchases=data.purchases.map(o=>({id:o.id,label:`${o.codigo} · ${o.productor_nombre||data.providers.find(p=>p.id===o.proveedor_id)?.nombre||'Productor'}${o.adelanto?` · adelanto previsto ${money(o.adelanto)}`:''}`}))
  const own=data.purchases.filter(o=>data.providers.find(p=>p.id===o.proveedor_id)?.tipo==='Propio'&&data.payables.some(d=>d.origen==='compra_campo'&&d.origen_id===o.id&&Number(d.monto)>Number(d.aplicado))).map(o=>({id:o.id,label:`${o.codigo} · ${o.productor_nombre||'Agro Solano'}`}))
  const title={credit:'Nota de crédito',manual:`Cuenta manual por ${form.tipo}`,advance:'Adelanto a productor',transfer:'Pago entre exportadora y Agro Solano',account:'Nueva cuenta de Agro Solano'}[type]
  return <div className="modalwrap"><div className="modal plant-form finance-modal"><div className="modalhead"><h2>{title}</h2><button type="button" onClick={close} aria-label="Cerrar"><X/></button></div>
    {type==='credit'&&<><p className="plant-help">{form.target.codigo} · {form.target.contraparte}. Saldo sin cobrar: {money(Number(form.target.monto)-Number(form.target.aplicado),form.target.moneda)}. La nota reduce el cobro y se refleja como pérdida comercial.</p><div className="formgrid"><Field label="Fecha"><Input type="date" value={form.fecha} onChange={v=>set('fecha',v)}/></Field><Field label={`Importe (${form.target.moneda})`}><Input type="number" min="0.01" step="0.01" value={form.monto} onChange={v=>set('monto',v)}/></Field><Field label="Motivo *"><Input value={form.motivo} onChange={v=>set('motivo',v)} placeholder="Producto dañado, calidad…"/></Field><Field label="Referencia de nota"><Input value={form.referencia} onChange={v=>set('referencia',v)}/></Field></div></>}
    {type==='manual'&&<div className="formgrid"><Field label="Fecha"><Input type="date" value={form.fecha} onChange={v=>set('fecha',v)}/></Field><Field label="Vencimiento"><Input type="date" value={form.fecha_vencimiento} onChange={v=>set('fecha_vencimiento',v)}/></Field><Field label={form.tipo==='cobrar'?'Cliente registrado':'Proveedor registrado'}><Select value={form.tipo==='cobrar'?form.cliente_id:form.proveedor_id} onChange={v=>{const selected=(form.tipo==='cobrar'?data.clients:data.providers).find(x=>x.id===v);setForm(old=>({...old,[form.tipo==='cobrar'?'cliente_id':'proveedor_id']:v,contraparte:selected?.nombre||old.contraparte}))}} placeholder="Escribir nombre directamente" items={(form.tipo==='cobrar'?data.clients:data.providers).map(x=>({id:x.id,label:x.nombre}))}/></Field><Field label="Contraparte *"><Input value={form.contraparte} onChange={v=>set('contraparte',v)}/></Field><Field label="Moneda"><select value={form.moneda} onChange={e=>set('moneda',e.target.value)}><option>CRC</option><option>USD</option></select></Field><Field label="Monto *"><Input type="number" min="0.01" step="0.01" value={form.monto} onChange={v=>set('monto',v)}/></Field><Field label="Concepto *"><Input value={form.concepto} onChange={v=>set('concepto',v)}/></Field><Field label="Factura o referencia"><Input value={form.referencia} onChange={v=>set('referencia',v)}/></Field></div>}
    {type==='advance'&&<><p className="plant-help">Solo los adelantos realmente pagados se restan de la compra; cualquier exceso liquidado aparece por cobrar al productor.</p><div className="formgrid"><Field label="Orden de compra"><Select value={form.orden_id} onChange={v=>set('orden_id',v)} items={purchases} placeholder="Seleccione compra"/></Field><Field label="Cuenta de salida en colones"><Select value={form.cuenta_id} onChange={v=>set('cuenta_id',v)} items={banks.map(a=>({id:a.id,label:a.banco}))} placeholder="Seleccione cuenta"/></Field><Field label="Fecha"><Input type="date" value={form.fecha} onChange={v=>set('fecha',v)}/></Field><Field label="Monto (₡)"><Input type="number" min="0.01" step="0.01" value={form.monto} onChange={v=>set('monto',v)}/></Field><Field label="Referencia"><Input value={form.referencia} onChange={v=>set('referencia',v)}/></Field></div></>}
    {type==='transfer'&&<><p className="plant-help">El pago reduce la cuenta por pagar de la exportadora y entra a la cuenta de Agro Solano en una sola operación.</p><div className="formgrid"><Field label="Compra propia"><Select value={form.orden_id} onChange={v=>set('orden_id',v)} items={own} placeholder="Seleccione orden"/></Field><Field label="Cuenta de la exportadora"><Select value={form.origen_id} onChange={v=>set('origen_id',v)} items={banks.map(a=>({id:a.id,label:a.banco}))} placeholder="Seleccione cuenta"/></Field><Field label="Cuenta de Agro Solano"><Select value={form.destino_id} onChange={v=>set('destino_id',v)} items={agro.map(a=>({id:a.id,label:a.banco}))} placeholder="Seleccione cuenta"/></Field><Field label="Fecha"><Input type="date" value={form.fecha} onChange={v=>set('fecha',v)}/></Field><Field label="Monto (₡)"><Input type="number" min="0.01" step="0.01" value={form.monto} onChange={v=>set('monto',v)}/></Field><Field label="Referencia"><Input value={form.referencia} onChange={v=>set('referencia',v)}/></Field></div></>}
    {type==='account'&&<div className="formgrid"><Field label="Nombre de banco o caja"><Input value={form.banco} onChange={v=>set('banco',v)}/></Field><Field label="Moneda"><select value={form.moneda} onChange={e=>set('moneda',e.target.value)}><option>CRC</option><option>USD</option></select></Field><Field label="Tipo"><select value={form.tipo_cuenta} onChange={e=>set('tipo_cuenta',e.target.value)}><option value="banco">Banco</option><option value="efectivo">Efectivo</option></select></Field></div>}
    {error&&<div className="formerror" role="alert">{error}</div>}<div className="modalactions"><button type="button" onClick={close} disabled={saving}>Cancelar</button><button type="button" className="primary" disabled={saving} onClick={save}>{saving?'Guardando…':'Guardar'}</button></div>
  </div></div>
}
