import React,{useEffect,useState} from 'react'
import {Plus,X} from 'lucide-react'
import {supabase} from './supabase'

export const cash=(value,currency='CRC')=>new Intl.NumberFormat('es-CR',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value)||0)
const parse=value=>Number(String(value??'').replace(',','.'))
const today=()=>{const d=new Date(),pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
const blank=()=>({cuenta_id:'',fecha:today(),tipo:'ingreso',monto:'',concepto:'',referencia:'',aplicaciones:[]})
const key=row=>`${row.origen}:${row.origen_id}`
const documentConcept=(row,type)=>row.origen==='venta_local'?`Cobro de venta de segunda · ${row.contraparte} · ${row.codigo}`:type==='ingreso'?`Cobro de ${row.contraparte} · ${row.codigo}`:`Pago a ${row.contraparte} · ${row.codigo}`
export function useFinance(){
  const [data,setData]=useState({accounts:[],moves:[],receivables:[],payables:[],applications:[]}),[error,setError]=useState(''),[loading,setLoading]=useState(true)
  const reload=async()=>{
    const requests=[supabase.from('cuentas_bancarias').select('*').order('banco'),supabase.from('movimientos_bancarios').select('*').order('fecha',{ascending:false}).limit(500),supabase.from('cxc_operativa').select('*').order('fecha',{ascending:false}),supabase.from('cxp_operativa').select('*').order('fecha',{ascending:false}),supabase.from('aplicaciones_bancarias').select('*').order('creado_en',{ascending:false}).limit(1000),supabase.from('saldos_movimientos_bancarios').select('*')]
    const [a,b,c,d,e,f]=await Promise.all(requests)
    setLoading(false)
    if(a.error||b.error||c.error||d.error||e.error||f.error){setError(`No se pudieron cargar las finanzas: ${(a.error||b.error||c.error||d.error||e.error||f.error).message}`);return}
    const balances=Object.fromEntries((f.data||[]).map(row=>[row.cuenta_id,row]))
    setError('');setData({accounts:(a.data||[]).map(row=>({...row,neto_movimientos:balances[row.id]?.neto||0,movimientos:balances[row.id]?.movimientos||0})),moves:b.data||[],receivables:c.data||[],payables:d.data||[],applications:e.data||[]})
  }
  useEffect(()=>{reload()},[])
  return {data,error,loading,reload}
}
export default function Finance({section,go}){
  const {data,error,loading,reload}=useFinance(),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[initial,setInitial]=useState(null),[saving,setSaving]=useState(false),[formError,setFormError]=useState('')
  const [showHistory,setShowHistory]=useState(false)
  const [selectedBank,setSelectedBank]=useState(null)
  const availableDocs=form.tipo==='ingreso'?data.receivables:data.payables
  const docs=availableDocs.filter(row=>row.moneda===data.accounts.find(a=>a.id===form.cuenta_id)?.moneda&&Number(row.monto)-Number(row.aplicado)>0&&row.etapa!=='Faltan precios')
  const open=account=>{setForm({...blank(),cuenta_id:account?.id||data.accounts[0]?.id||''});setEditing('movement');setFormError('')}
  const saveInitial=async()=>{
    const amount=parse(initial.value)
    if(!Number.isFinite(amount)){setFormError('Indique un saldo inicial válido.');return}
    setSaving(true);const {error:e}=await supabase.from('cuentas_bancarias').update({saldo_inicial:amount,saldo_confirmado:true}).eq('id',initial.id).select('id').single();setSaving(false)
    if(e){setFormError(e.message);return}setInitial(null);setFormError('');reload()
  }
  const saveMove=async()=>{
    const amount=parse(form.monto)
    if(!form.cuenta_id||!form.fecha||!form.concepto.trim()||!Number.isFinite(amount)||amount<=0||Math.round(amount*100)!==amount*100){setFormError('Seleccione cuenta y complete fecha, concepto y monto positivo.');return}
    const apps=form.aplicaciones.map(x=>({...x,monto:parse(x.monto)}))
    if(apps.some(x=>!Number.isFinite(x.monto)||x.monto<=0)||apps.reduce((sum,x)=>sum+x.monto,0)>amount+0.001){setFormError('Revise las aplicaciones: su suma no puede superar el movimiento.');return}
    setSaving(true);setFormError('')
    const {error:e}=await supabase.rpc('registrar_movimiento_bancario',{p_cuenta_id:form.cuenta_id,p_fecha:form.fecha,p_tipo:form.tipo,p_monto:amount,p_concepto:form.concepto.trim(),p_referencia:form.referencia.trim()||null,p_aplicaciones:apps})
    setSaving(false);if(e){setFormError(`No se pudo registrar: ${e.message}`);return}setEditing(null);reload()
  }
  const toggleDoc=row=>setForm(f=>{
    const current=f.aplicaciones.filter(x=>!(x.origen===row.origen&&x.origen_id===row.origen_id))
    const selected=current.length<f.aplicaciones.length?current:[...current,{origen:row.origen,origen_id:row.origen_id,monto:String(Math.round((Number(row.monto)-Number(row.aplicado))*100)/100)}]
    const selectedDocs=selected.map(x=>availableDocs.find(d=>key(d)===key(x))).filter(Boolean)
    const autoConcept=selectedDocs.length===1?documentConcept(selectedDocs[0],f.tipo):selectedDocs.length>1?`${f.tipo==='ingreso'?'Cobro':'Pago'} de ${selectedDocs.length} documentos`:''
    return {...f,aplicaciones:selected,monto:selected.length?String(Math.round(selected.reduce((sum,x)=>sum+parse(x.monto),0)*100)/100):'',concepto:selected.length?autoConcept:''}
  })
  const updateApplication=(row,value)=>setForm(f=>{const before=f.aplicaciones.reduce((sum,x)=>sum+(parse(x.monto)||0),0),applications=f.aplicaciones.map(x=>x.origen===row.origen&&x.origen_id===row.origen_id?{...x,monto:value}:x);return {...f,aplicaciones:applications,monto:!f.monto||Math.abs(parse(f.monto)-before)<0.001?String(Math.round(applications.reduce((sum,x)=>sum+(parse(x.monto)||0),0)*100)/100):f.monto}})
  if(loading)return <div className="empty">Cargando finanzas…</div>
  if(error)return <div className="formerror">{error}</div>
  const kind=section==='Cuentas por cobrar'?'receivables':section==='Cuentas por pagar'?'payables':null
  const settled=row=>Number(row.monto)>0&&Math.round((Number(row.monto)-Number(row.aplicado))*100)<=0
  const listed=kind?data[kind].filter(row=>settled(row)===showHistory):[]
  const settledDate=row=>{const ids=new Set(data.applications.filter(a=>a.origen===row.origen&&a.origen_id===row.origen_id).map(a=>a.movimiento_id));return data.moves.filter(m=>ids.has(m.id)).map(m=>m.fecha).sort().at(-1)}
  const bankMoves=data.moves.filter(m=>!selectedBank||m.cuenta_id===selectedBank)
  const bankContent=<><div className="bank-note">Cada banco y moneda tiene su propia cuenta. Los movimientos aparecen aquí aunque todavía falte registrar el saldo inicial del banco.</div><div className="finance-summary">{data.accounts.map(a=>{const net=Number(a.neto_movimientos);return <article key={a.id} className={selectedBank===a.id?'bank-selected':''}><span>{a.banco} · {a.moneda}</span><strong>{cash(a.saldo_confirmado?Number(a.saldo_inicial)+net:net,a.moneda)}</strong><small>{a.saldo_confirmado?'Saldo calculado · incluye saldo inicial y movimientos':'Neto de movimientos registrados · saldo inicial pendiente'}</small><div><button onClick={()=>{setInitial({id:a.id,value:String(a.saldo_inicial),name:a.banco,currency:a.moneda});setFormError('')}}>Saldo inicial</button><button onClick={()=>setSelectedBank(a.id)}>Ver movimientos ({a.movimientos})</button><button onClick={()=>open(a)}>Nuevo movimiento</button></div></article>})}</div><div className="workers-panel"><div className="bank-ledger-head"><h3>{selectedBank?`Movimientos · ${data.accounts.find(a=>a.id===selectedBank)?.banco} · ${data.accounts.find(a=>a.id===selectedBank)?.moneda}`:'Todos los movimientos bancarios'}</h3>{selectedBank&&<button type="button" onClick={()=>setSelectedBank(null)}>Ver todos</button>}</div>{bankMoves.map(m=>{const a=data.accounts.find(x=>x.id===m.cuenta_id),links=data.applications.filter(x=>x.movimiento_id===m.id);return <article key={m.id}><div><b>{m.fecha} · {m.concepto}</b><span>{a?.banco} · {a?.moneda}{m.referencia?` · ${m.referencia}`:''} · {links.length} aplicación(es)</span></div><strong className={m.tipo==='egreso'?'finance-out':''}>{m.tipo==='egreso'?'-':'+'}{cash(m.monto,a?.moneda||'CRC')}</strong></article>})}{!bankMoves.length&&<p>No hay movimientos en esta cuenta.</p>}</div></>
  const financeContent=<><div className="finance-summary">{['CRC','USD'].map(currency=><React.Fragment key={currency}><article><span>Por cobrar · {currency}</span><strong>{cash(data.receivables.reduce((sum,r)=>sum+(r.moneda===currency?Math.max(0,Number(r.monto)-Number(r.aplicado)):0),0),currency)}</strong></article><article><span>Por pagar · {currency}</span><strong>{cash(data.payables.reduce((sum,r)=>sum+(r.moneda===currency?Math.max(0,Number(r.monto)-Number(r.aplicado)):0),0),currency)}</strong></article></React.Fragment>)}</div><div className="workers-panel"><h3>Resumen de operaciones</h3><p>{data.moves.length} movimientos bancarios registrados · {data.receivables.filter(r=>!settled(r)).length} cuentas por cobrar pendientes · {data.payables.filter(r=>!settled(r)).length} cuentas por pagar pendientes.</p><div className="finance-links"><button onClick={()=>go('Cuentas por cobrar')}>Ver cuentas por cobrar</button><button onClick={()=>go('Cuentas por pagar')}>Ver cuentas por pagar</button><button className="primary" onClick={()=>go('Bancos')}>Ver saldos y movimientos bancarios</button></div></div></>
  return <><div className="modulebar"><p>{kind?'Las cuentas se generan al finalizar boletas o pedidos. Los cobros y pagos completos quedan en el historial.':'Registre los saldos iniciales y cada depósito o pago real. Un movimiento puede aplicarse a varios pedidos o compras.'}</p>{kind&&<button type="button" onClick={reload}>Actualizar cuentas</button>}{!kind&&<button className="primary" onClick={()=>open()}><Plus size={18}/>Nuevo movimiento</button>}</div>
    {kind?<><div className="finance-summary">{['CRC','USD'].map(currency=><article key={currency}><span>Saldo pendiente {currency}</span><strong>{cash(data[kind].filter(r=>r.moneda===currency&&!settled(r)).reduce((sum,r)=>sum+Math.max(0,Number(r.monto)-Number(r.aplicado)),0),currency)}</strong></article>)}</div><div className="load-selector finance-tabs"><button type="button" className={!showHistory?'primary':''} onClick={()=>setShowHistory(false)}>Pendientes ({data[kind].filter(r=>!settled(r)).length})</button><button type="button" className={showHistory?'primary':''} onClick={()=>setShowHistory(true)}>{kind==='receivables'?'Historial de cobradas':'Historial de pagadas'} ({data[kind].filter(settled).length})</button></div><div className="workers-panel"><h3>{showHistory?(kind==='receivables'?'Cobros completos':'Pagos completos'):section}</h3>{listed.map(r=><article key={key(r)}><div><b>{r.codigo} · {r.contraparte}</b><span>{r.fecha} · {r.etapa} · Total {cash(r.monto,r.moneda)} · Aplicado {cash(r.aplicado,r.moneda)}{showHistory&&settledDate(r)?` · ${kind==='receivables'?'Cobrado':'Pagado'} el ${settledDate(r)}`:''}</span></div><strong>{showHistory?'Saldo 0':cash(Math.max(0,Number(r.monto)-Number(r.aplicado)),r.moneda)}</strong></article>)}{!listed.length&&<p>{showHistory?'Todavía no hay cuentas totalmente liquidadas.':'No hay cuentas pendientes.'}</p>}</div><button className="primary" onClick={()=>go('Bancos')}>Registrar cobro o pago en Bancos</button></>:section==='Bancos'?bankContent:financeContent}
    {initial&&<div className="modalwrap"><div className="modal carton-modal"><div className="modalhead"><h2>Saldo inicial · {initial.name} ({initial.currency})</h2><button onClick={()=>setInitial(null)}><X/></button></div><div className="formgrid"><label className="wide">Saldo confirmado por el banco<input type="number" step="0.01" inputMode="decimal" value={initial.value} onChange={e=>setInitial({...initial,value:e.target.value})}/></label></div><p className="plant-help">Registre aquí el saldo con que comienza el control. Los movimientos posteriores se suman o restan automáticamente.</p>{formError&&<div className="formerror">{formError}</div>}<div className="modalactions"><button onClick={()=>setInitial(null)}>Cancelar</button><button className="primary" disabled={saving} onClick={saveInitial}>Guardar saldo</button></div></div></div>}
    {editing&&<div className="modalwrap"><div className="modal plant-form finance-modal"><div className="modalhead"><div><span>BANCO</span><h2>Registrar {form.tipo==='ingreso'?'depósito o cobro':'pago o egreso'}</h2></div><button onClick={()=>setEditing(null)}><X/></button></div>{formError&&<div className="formerror" role="alert">{formError}</div>}<div className="formgrid"><label>Cuenta<select value={form.cuenta_id} onChange={e=>setForm({...form,cuenta_id:e.target.value,aplicaciones:[],monto:form.aplicaciones.length?'':form.monto,concepto:form.aplicaciones.length?'':form.concepto})}>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.banco} · {a.moneda}</option>)}</select></label><label>Tipo<select value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value,aplicaciones:[],monto:form.aplicaciones.length?'':form.monto,concepto:form.aplicaciones.length?'':form.concepto})}><option value="ingreso">Ingreso / depósito</option><option value="egreso">Egreso / pago</option></select></label><label>Fecha<input type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></label><label>Monto<input type="number" min="0.01" step="0.01" inputMode="decimal" value={form.monto} onChange={e=>setForm({...form,monto:e.target.value})}/></label><label className="wide">Concepto<input value={form.concepto} onChange={e=>setForm({...form,concepto:e.target.value})} placeholder="Ejemplo: depósito de cliente"/></label><label className="wide">Referencia bancaria<input value={form.referencia} onChange={e=>setForm({...form,referencia:e.target.value})}/></label></div><section className="finance-docs"><h3>Aplicar a {form.tipo==='ingreso'?'cuentas por cobrar':'cuentas por pagar'} (opcional)</h3><p>Al escoger un documento se completan el monto pendiente y el concepto. Puede ajustar el monto para registrar un abono parcial.</p>{docs.map(row=>{const selected=form.aplicaciones.find(x=>x.origen===row.origen&&x.origen_id===row.origen_id);return <div key={key(row)}><label><input type="checkbox" checked={!!selected} onChange={()=>toggleDoc(row)}/>{row.codigo} · {row.contraparte} · saldo {cash(Number(row.monto)-Number(row.aplicado),row.moneda)}</label>{selected&&<input aria-label={`Aplicar a ${row.codigo}`} type="number" min="0.01" step="0.01" inputMode="decimal" value={selected.monto} onChange={e=>updateApplication(row,e.target.value)}/>}</div>})}{!docs.length&&<p>No hay documentos con saldo en la moneda de esta cuenta.</p>}</section><div className="modalactions"><button disabled={saving} onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" disabled={saving} onClick={saveMove}>{saving?'Guardando…':'Registrar movimiento'}</button></div></div></div>}</>
}
