import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Menu, X, Plus, LogOut, LayoutDashboard, ShoppingCart, Truck, Users, PackageCheck, CircleDollarSign } from 'lucide-react'
import { supabase } from './supabase'
import './styles.css'
import './forms.css'

const today = () => new Intl.DateTimeFormat('en-CA',{timeZone:'America/Costa_Rica',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const products=['Yuca','Ñampí','Cabeza de ñampí','Camote','Caña de azúcar','Jengibre','Malanga lila','Malanga blanca','Malanga taro','Ñame','Chayote','Ayote','Cúrcuma','Papa china']
const places=['El Concho','La Unión','Copevega','El Tanque','La Fortuna','Agua Azul','Muelle','Guápiles','Upala','Los Chiles','Caño Negro','Zona Norte']
const currencies=['CRC','USD','EUR']
const spec=(key,label,type='text',extra={})=>({key,label,type,...extra})
const configs={
 Proveedores:{table:'proveedores',icon:Users,fields:[spec('nombre','Nombre completo','text',{required:true}),spec('telefono','Teléfono','tel'),spec('residencia','Residencia'),spec('zona','Zona','select',{options:places}),spec('tipo','Tipo','select',{options:['Agricultor','Intermediario','Propio']})],columns:['nombre','telefono','zona','tipo']},
 Clientes:{table:'clientes',icon:Users,fields:[spec('nombre','Nombre del cliente','text',{required:true}),spec('pais','País'),spec('mercado','Mercado','select',{options:['Europa','Estados Unidos','Canadá','Local','Otro']}),spec('contacto','Contacto'),spec('condiciones','Condiciones')],columns:['nombre','pais','mercado','contacto']},
 'Órdenes de compra':{table:'ordenes_compra',icon:ShoppingCart,prefix:'OC',fields:[spec('fecha','Fecha','date',{required:true}),spec('proveedor_id','Proveedor','relation',{source:'proveedores',required:true}),spec('producto','Producto','select',{options:products,required:true}),spec('lugar','Finca o lugar','select',{options:places}),spec('tipo_compra','Tipo de compra','select',{options:['A rendimiento','En pie','Cosecha propia','Puesto en camión']}),spec('moneda','Moneda','select',{options:currencies,required:true}),spec('precio_europa','Precio Europa por quintal (46 kg)','number'),spec('precio_eeuu','Precio EE. UU. por quintal (46 kg)','number'),spec('precio_rechazo','Precio rechazo por quintal (46 kg)','number'),spec('estado','Estado','select',{options:['Pendiente','En proceso','Completada','Cancelada']}),spec('observaciones','Observaciones','textarea')],columns:['codigo','fecha','proveedor_id','producto','moneda','estado']},
 'Boletas de entrada':{table:'boletas_entrada',icon:Truck,prefix:'BE',fields:[spec('proveedor_id','Proveedor','relation',{source:'proveedores',required:true}),spec('orden_compra_id','Orden de compra','relation',{source:'ordenes_compra',office:true}),spec('producto','Producto','select',{options:products,required:true}),spec('finca_lugar','Finca o lugar','select',{options:places}),spec('chofer','Chofer'),spec('placa','Placa'),spec('condicion','Condición','select',{options:['Mojado','Seco']}),spec('tipo_recipiente','Recipiente','select',{options:['Cajas','Sacos']}),spec('cantidad_recipientes','Cantidad de cajas o sacos','number',{required:true,step:'1',min:1}),spec('promedio_peso','Peso promedio de la muestra (kg)','number',{required:true,step:'0.001',min:0.001}),spec('linea_proceso','Línea de proceso','select',{options:['1','2']}),spec('encargado','Encargado de planta','select',{options:['Andrés','Javier','Emilio']}),spec('observaciones','Observaciones','textarea')],columns:['codigo','fecha_hora','proveedor_id','producto','cantidad_recipientes','kg_estimados']},
 'Órdenes de venta':{table:'ordenes_venta',icon:PackageCheck,prefix:'OV',fields:[spec('fecha','Fecha','date',{required:true}),spec('cliente_id','Cliente','relation',{source:'clientes',required:true}),spec('mercado','Mercado','select',{options:['Europa','Estados Unidos','Canadá','Local','Otro']}),spec('contenedor','Contenedor'),spec('moneda','Moneda','select',{options:currencies,required:true}),spec('estado','Estado','select',{options:['Borrador','Preparando','Despachada','Cancelada']}),spec('observaciones','Observaciones','textarea')],columns:['codigo','fecha','cliente_id','mercado','moneda','estado']},
 'Tipos de cambio':{table:'tipos_cambio',icon:CircleDollarSign,fields:[spec('fecha','Fecha','date',{required:true}),spec('moneda','Moneda','select',{options:['USD','EUR'],required:true}),spec('compra','Compra: colones por unidad','number',{required:true,min:0.0001,step:'0.0001'}),spec('venta','Venta: colones por unidad','number',{required:true,min:0.0001,step:'0.0001'})],columns:['fecha','moneda','compra','venta']}
}
const labelFor=key=>({codigo:'Código',fecha_hora:'Fecha de ingreso',kg_estimados:'Kg estimados',proveedor_id:'Proveedor',cliente_id:'Cliente',cantidad_recipientes:'Cantidad',moneda:'Moneda',fecha:'Fecha',nombre:'Nombre',telefono:'Teléfono',zona:'Zona',tipo:'Tipo',pais:'País',mercado:'Mercado',contacto:'Contacto',producto:'Producto',estado:'Estado',compra:'Compra',venta:'Venta'}[key]||key)
const prettyError=e=>e?.code==='23505'?'Ya existe un registro con ese código o fecha y moneda. Revíselo antes de guardar.':e?.code==='42501'?'Su usuario no tiene permiso para esta operación.':e?.message||'No se pudo completar la operación. Inténtelo de nuevo.'

function Login(){
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const result=sent?await supabase.auth.verifyOtp({email,token:code.trim(),type:'email'}):await supabase.auth.signInWithOtp({email});if(result.error)throw result.error;setSent(true)}catch(err){setError(prettyError(err))}finally{setBusy(false)}}
 return <main className="login"><form className="panel loginpanel" onSubmit={submit}><div className="brandmark">HN</div><h1>Gestión y Control</h1><p>Raíces y Tubérculos Huetar Norte S.A.</p><h2>Ingresar</h2><label>Correo electrónico<input type="email" autoComplete="email" required value={email} disabled={sent||busy} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<><p>Revise su correo. Ingrese el código recibido; si el mensaje incluye un enlace, también puede abrirlo.</p><label>Código de verificación<input autoComplete="one-time-code" inputMode="numeric" required value={code} onChange={e=>setCode(e.target.value)}/></label></>}{error&&<p role="alert" className="formerror">{error}</p>}<button className="primary" disabled={busy}>{busy?'Espere…':sent?'Verificar e ingresar':'Enviar código a mi correo'}</button>{sent&&<button type="button" onClick={()=>{setSent(false);setCode('')}}>Cambiar correo o reenviar</button>}<p className="muted">Solo los usuarios autorizados pueden consultar y registrar operaciones.</p></form></main>
}

function App(){
 const [session,setSession]=useState(undefined),[profile,setProfile]=useState(undefined),[authError,setAuthError]=useState(''),[section,setSection]=useState('Resumen'),[open,setOpen]=useState(false),[revision,setRevision]=useState(0)
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data,error})=>{if(alive){setSession(data.session);if(error)setAuthError(prettyError(error))}});const {data}=supabase.auth.onAuthStateChange((_event,current)=>{if(alive){setSession(current);setProfile(undefined)}});return()=>{alive=false;data.subscription.unsubscribe()}},[])
 useEffect(()=>{let alive=true;if(!session)return;setAuthError('');supabase.from('perfiles').select('id,nombre,rol,activo').eq('id',session.user.id).maybeSingle().then(({data,error})=>{if(alive){setProfile(data);if(error)setAuthError(prettyError(error))}});return()=>{alive=false}},[session,revision])
 async function logout(){const {error}=await supabase.auth.signOut();if(error)setAuthError(prettyError(error));else{setSession(null);setProfile(undefined)}}
 if(session===undefined)return <p role="status" className="loading">Comprobando sesión…</p>
 if(!session)return <Login/>
 if(profile===undefined&&!authError)return <p role="status" className="loading">Comprobando permisos…</p>
 if(!profile?.activo)return <main className="login"><section className="panel loginpanel"><h1>Acceso pendiente de activación</h1><p>Su correo está verificado. Falta asignarle un perfil de trabajo.</p><p>{session.user.email}</p>{authError&&<p role="alert">{authError}</p>}<button className="primary" onClick={()=>setRevision(r=>r+1)}>Comprobar activación</button><button onClick={logout}>Cerrar sesión</button></section></main>
 const office=['administrador','oficina'].includes(profile.rol)
 const names=Object.keys(configs).filter(n=>office||['Proveedores','Clientes','Boletas de entrada'].includes(n)&&profile.rol==='planta')
 const go=n=>{setSection(n);setOpen(false)}
 return <div className="app"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark">HN</div><div><b>Gestión y Control</b><span>Huetar Norte S.A.</span></div><button className="close" aria-label="Cerrar menú" onClick={()=>setOpen(false)}><X/></button></div><nav><button className={section==='Resumen'?'active':''} onClick={()=>go('Resumen')}><LayoutDashboard size={19}/>Resumen</button>{names.map(n=>{const Icon=configs[n].icon;return <button key={n} className={section===n?'active':''} onClick={()=>go(n)}><Icon size={19}/>{n}</button>})}</nav><div className="sidefoot"><p>{profile.nombre} · {profile.rol}</p><button onClick={logout}><LogOut size={19}/>Cerrar sesión</button></div></aside>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}<main><header><button className="menubtn" aria-label="Abrir menú" onClick={()=>setOpen(true)}><Menu/></button><div><span className="eyebrow">RAÍCES Y TUBÉRCULOS HUETAR NORTE S.A.</span><h1>{section}</h1></div></header><div className="content">{authError&&<p role="alert" className="formerror">{authError}</p>}{section==='Resumen'?<Dashboard office={office} go={go}/>:names.includes(section)&&<Module key={section} name={section} profile={profile} office={office}/>}</div></main></div>
}

function Dashboard({office,go}){
 const [counts,setCounts]=useState({}),[rates,setRates]=useState([]),[error,setError]=useState('')
 useEffect(()=>{let alive=true;async function load(){const tables=office?['proveedores','clientes','ordenes_compra','boletas_entrada','ordenes_venta']:['proveedores','clientes','boletas_entrada'];const results=await Promise.all(tables.map(async t=>{const r=await supabase.from(t).select('id',{count:'exact',head:true});if(r.error)throw r.error;return [t,r.count]}));if(alive)setCounts(Object.fromEntries(results));if(office){const {data,error}=await supabase.from('tipos_cambio').select('*').eq('fecha',today());if(error)throw error;if(alive)setRates(data)}}load().catch(e=>alive&&setError(prettyError(e)));return()=>{alive=false}},[office])
 return <><section className="hero"><div><span>{today()}</span><h2>Resumen de operaciones</h2><p>Registros guardados en Supabase.</p></div></section>{error&&<p role="alert" className="formerror">{error}</p>}<div className="stats">{Object.entries(counts).map(([k,v])=><article className="stat" key={k}><span>{Object.keys(configs).find(n=>configs[n].table===k)}</span><b>{v}</b><small>Registros guardados</small></article>)}</div>{office&&<section className="panel ratepanel"><h3>Tipo de cambio del día</h3>{rates.length?rates.map(r=><p key={r.id}><b>{r.moneda}</b> · Compra ₡{r.compra} · Venta ₡{r.venta}</p>):<p>No se ha registrado el tipo de cambio de hoy.</p>}<button className="primary" onClick={()=>go('Tipos de cambio')}>Registrar o actualizar</button><p className="muted">Los precios de las órdenes conservan la moneda original. La conversión de reportes financieros está pendiente.</p></section>}<section className="panel ratepanel"><h3>Desarrollo pendiente</h3><p>Producción y rendimientos, finanzas, conciliación bancaria y trabajadores todavía no están conectados en esta versión. Los importes de demostración fueron retirados.</p></section></>
}

function Module({name,profile,office}){
 const config=configs[name],canEdit=office||name==='Boletas de entrada'
 const [rows,setRows]=useState([]),[lookups,setLookups]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[linesOrder,setLinesOrder]=useState(null)
 async function refresh(){setLoading(true);setError('');try{const sources=[...new Set(config.fields.filter(f=>f.source&&(!f.office||office)).map(f=>f.source))];const {data,error}=await supabase.from(config.table).select('*').order(config.table==='tipos_cambio'?'fecha':'creado_en',{ascending:false});if(error)throw error;const entries=await Promise.all(sources.map(async s=>{const {data,error}=await supabase.from(s).select(s==='ordenes_compra'?'id,codigo':'id,nombre');if(error)throw error;return [s,data]}));setRows(data);setLookups(Object.fromEntries(entries))}catch(e){setError(prettyError(e))}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[])
 const relation=(key,value)=>{const f=config.fields.find(f=>f.key===key);const r=lookups[f?.source]?.find(r=>r.id===value);return r?.nombre||r?.codigo||value||'—'}
 const filtered=rows.filter(r=>config.columns.map(k=>relation(k,r[k])).join(' ').toLocaleLowerCase('es').includes(search.toLocaleLowerCase('es')))
 return <><div className="modulebar"><p>{rows.length} registros</p>{canEdit&&<button className="primary" onClick={()=>setEditing({})}><Plus size={18}/>Nuevo registro</button>}</div>{message&&<p role="status" className="success">{message}</p>}{error&&<div className="formerror" role="alert">{error}<button onClick={refresh}>Reintentar</button></div>}<section className="panel tablepanel"><div className="filters"><label>Buscar<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Código, nombre o estado"/></label></div>{loading?<p className="loading" role="status">Cargando registros…</p>:filtered.length?<div className="tableoverflow"><table className="datagrid"><thead><tr>{config.columns.map(k=><th key={k}>{labelFor(k)}</th>)}<th>Acciones</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{config.columns.map(k=><td key={k}>{k==='fecha_hora'?new Date(r[k]).toLocaleString('es-CR',{timeZone:'America/Costa_Rica'}):relation(k,r[k])}</td>)}<td>{canEdit&&<button onClick={()=>setEditing(r)}>Editar</button>}{name==='Órdenes de venta'&&<button onClick={()=>setLinesOrder(r)}>Productos y cajas</button>}</td></tr>)}</tbody></table></div>:<div className="empty"><h3>{search?'Sin coincidencias':'Sin registros todavía'}</h3><p>{search?'Cambie la búsqueda.':'Los registros aparecerán aquí después de guardarlos.'}</p></div>}</section>{editing&&<RecordForm config={config} name={name} record={editing} lookups={lookups} profile={profile} office={office} close={()=>setEditing(null)} saved={()=>{setEditing(null);setMessage('Registro guardado en Supabase.');refresh()}}/>}{linesOrder&&<OrderLines order={linesOrder} close={()=>setLinesOrder(null)}/>}</>
}

function RecordForm({config,name,record,lookups,profile,office,close,saved}){
 const initial=Object.fromEntries(config.fields.map(f=>[f.key,record[f.key]??(f.type==='date'?today():f.key==='moneda'?(name==='Órdenes de compra'?'CRC':'USD'):'')]))
 const [values,setValues]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const payload={};for(const f of config.fields){if(f.office&&!office)continue;const value=values[f.key];payload[f.key]=value===''?null:f.type==='number'||f.key==='linea_proceso'?Number(value):value}
 if(!record.id&&config.prefix)payload.codigo=config.prefix+'-'+crypto.randomUUID().slice(0,12).toUpperCase()
 if(name==='Órdenes de compra'&&!record.id)payload.creado_por=profile.id
 if(name==='Boletas de entrada')payload.kg_estimados=Math.round(payload.cantidad_recipientes*payload.promedio_peso*1000)/1000
 const q=record.id?supabase.from(config.table).update(payload).eq('id',record.id):supabase.from(config.table).insert(payload)
 const {data,error}=await q.select('id').single();if(error)throw error;if(!data)throw new Error('No se confirmó el guardado.');saved()
 }catch(err){setError(prettyError(err))}finally{setBusy(false)}}
 return <div className="modalwrap"><form className="modal realform" onSubmit={save} role="dialog" aria-modal="true" aria-label={name}><div className="modalhead"><h2>{record.id?'Editar':'Nuevo'} · {name}</h2><button type="button" disabled={busy} aria-label="Cerrar formulario" onClick={close}><X/></button></div><div className="formgrid">{config.fields.filter(f=>!f.office||office).map(f=><label key={f.key} className={f.type==='textarea'?'wide':''}>{f.label}{f.required?' *':''}{f.type==='select'||f.type==='relation'?<select value={values[f.key]} required={f.required} disabled={busy} onChange={e=>setValues({...values,[f.key]:e.target.value})}><option value="">Seleccione…</option>{f.type==='relation'?(lookups[f.source]||[]).map(r=><option key={r.id} value={r.id}>{r.nombre||r.codigo}</option>):f.options.map(o=><option key={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea rows="3" value={values[f.key]} disabled={busy} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:<input type={f.type} required={f.required} value={values[f.key]} min={f.type==='number'?(f.min??0):undefined} step={f.type==='number'?(f.step||'0.01'):undefined} disabled={busy} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>}</label>)}{name==='Boletas de entrada'&&<p className="wide">Ingreso estimado: <strong>{((Number(values.cantidad_recipientes)||0)*(Number(values.promedio_peso)||0)).toLocaleString('es-CR',{maximumFractionDigits:3})} kg</strong></p>}</div>{error&&<p className="formerror" role="alert">{error}</p>}<div className="modalactions"><button type="button" disabled={busy} onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar registro'}</button></div></form></div>
}

function OrderLines({order,close}){
 const fresh={producto:'Yuca',presentacion_kg:'18',paletas:'',cajas_por_paleta:'',cantidad_cajas:'',precio_caja:''}
 const [rows,setRows]=useState([]),[v,setV]=useState(fresh),[editingId,setEditingId]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 async function load(){const {data,error}=await supabase.from('ordenes_venta_lineas').select('*').eq('orden_venta_id',order.id);if(error)throw error;setRows(data)}
 useEffect(()=>{load().catch(e=>setError(prettyError(e)))},[])
 async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{const payload={orden_venta_id:order.id,producto:v.producto};for(const k of ['presentacion_kg','paletas','cajas_por_paleta','cantidad_cajas','precio_caja'])payload[k]=v[k]===''?null:Number(v[k]);const query=editingId?supabase.from('ordenes_venta_lineas').update(payload).eq('id',editingId).eq('orden_venta_id',order.id):supabase.from('ordenes_venta_lineas').insert(payload);const {error}=await query.select('id').single();if(error)throw error;await load();setV(fresh);setEditingId(null);setMessage('Línea guardada en Supabase.')}catch(e){setError(prettyError(e))}finally{setBusy(false)}}
 return <div className="modalwrap"><section className="modal realform" role="dialog" aria-modal="true" aria-label="Productos de la orden"><div className="modalhead"><h2>{order.codigo} · Productos</h2><button aria-label="Cerrar productos" disabled={busy} onClick={close}><X/></button></div><p>Precios en {order.moneda}. Cada presentación se guarda en una línea independiente.</p><div className="tableoverflow"><table className="datagrid"><thead><tr><th>Producto</th><th>Kg/caja</th><th>Cajas</th><th>Precio/caja</th><th>Total</th><th>Acción</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.producto}</td><td>{r.presentacion_kg}</td><td>{r.cantidad_cajas}</td><td>{r.precio_caja}</td><td>{r.total}</td><td><button disabled={busy} onClick={()=>{setEditingId(r.id);setV(Object.fromEntries(Object.keys(fresh).map(k=>[k,r[k]??''])));setMessage('')}}>Editar</button></td></tr>)}</tbody></table></div><p><b>Total: {new Intl.NumberFormat('es-CR',{style:'currency',currency:order.moneda}).format(rows.reduce((s,r)=>s+Number(r.total),0))}</b></p><form onSubmit={save}><h3>{editingId?'Editar línea':'Agregar producto'}</h3><div className="formgrid"><label>Producto<select value={v.producto} disabled={busy} onChange={e=>setV({...v,producto:e.target.value})}>{products.map(p=><option key={p}>{p}</option>)}</select></label>{[['presentacion_kg','Kg por caja','0.01',0.01,true],['paletas','Paletas','1',1,false],['cajas_por_paleta','Cajas por paleta','1',1,false],['cantidad_cajas','Cantidad total de cajas','1',1,true],['precio_caja',`Precio por caja (${order.moneda})`,'0.01',0,true]].map(([k,l,step,min,required])=><label key={k}>{l}<input type="number" inputMode="decimal" min={min} step={step} required={required} value={v[k]} disabled={busy} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}</div><button type="button" disabled={busy||!v.paletas||!v.cajas_por_paleta} onClick={()=>setV({...v,cantidad_cajas:String(Number(v.paletas)*Number(v.cajas_por_paleta))})}>Calcular cajas desde paletas</button><p className="muted">Puede escribir cualquier cantidad entera de cajas, por ejemplo 156.</p>{error&&<p className="formerror" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}<div className="modalactions">{editingId&&<button type="button" disabled={busy} onClick={()=>{setEditingId(null);setV(fresh)}}>Cancelar edición</button>}<button className="primary" disabled={busy}>{busy?'Guardando…':editingId?'Guardar cambios':'Guardar línea'}</button></div></form></section></div>
}
createRoot(document.getElementById('root')).render(<App/>);
