import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
import {isoWeek} from './weekly-model'
const blank=()=>({nombre:'',cajas_18:'',fecha_prevista:'',notas:''})
export default function PersonalPlan({start,userId,progress}){
 const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[opened,setOpened]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 useEffect(()=>{let active=true;setLoading(true);setRows([]);setForm(blank());setEditing(null);setOpened(false);setError('');supabase.from('programacion_personal_arranque').select('*').eq('usuario_id',userId).eq('semana_inicio',start).order('creado_en').limit(1000).then(({data,error:e})=>{if(!active)return;setLoading(false);if(e)setError('No se pudo cargar tu programación personal.');else if(data.length>=1000)setError('Hay demasiadas anotaciones para mostrar un total completo.');else setRows(data)});return()=>{active=false}},[start,userId])
 const change=(key,value)=>setForm(f=>({...f,[key]:value}))
 const save=async e=>{e.preventDefault();const n=Number(form.cajas_18);if(!form.nombre.trim()||!Number.isInteger(n)||n<=0){setError('Anotá un nombre y una cantidad positiva de cajas de 18 kg.');return}const payload={nombre:form.nombre.trim(),cajas_18:n,fecha_prevista:form.fecha_prevista||null,notas:form.notas.trim()};setSaving(true);setError('');const result=editing?await supabase.from('programacion_personal_arranque').update(payload).eq('id',editing).eq('usuario_id',userId).eq('semana_inicio',start).select().single():await supabase.from('programacion_personal_arranque').insert({...payload,semana_inicio:start}).select().single();setSaving(false);if(result.error){setError(`No se pudo guardar: ${result.error.message}`);return}setRows(r=>editing?r.map(x=>x.id===editing?result.data:x):[...r,result.data]);setForm(blank());setEditing(null);setOpened(false)}
 const remove=async row=>{if(!window.confirm(`¿Borrar la anotación de ${row.nombre}?`))return;setSaving(true);setError('');const {data,error:e}=await supabase.from('programacion_personal_arranque').delete().eq('id',row.id).eq('usuario_id',userId).eq('semana_inicio',start).select('id').single();setSaving(false);if(e||!data){setError('No se pudo borrar la anotación.');return}setRows(r=>r.filter(x=>x.id!==row.id));if(editing===row.id){setForm(blank());setEditing(null);setOpened(false)}}

 const fmt=n=>Number(n||0).toLocaleString('es-CR')
 const dateAt=offset=>{const d=new Date(start+'T12:00:00');d.setDate(d.getDate()+offset);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
 const days=[['Domingo',dateAt(-1)],['Lunes',dateAt(0)],['Martes',dateAt(1)],['Miércoles',dateAt(2)],['Jueves',dateAt(3)],['Viernes',dateAt(4)],['Sábado',dateAt(5)]]
 const groups=[...days.map(([name,date])=>({name,date,items:rows.filter(r=>r.fecha_prevista===date)})),{name:'Sin día / otras fechas',date:'',items:rows.filter(r=>!days.some(([,d])=>d===r.fecha_prevista))}]
 const begin=(row,date)=>{setForm(row?{nombre:row.nombre,cajas_18:String(row.cajas_18),fecha_prevista:row.fecha_prevista||'',notas:row.notas||''}:{...blank(),fecha_prevista:date});setEditing(row?.id||null);setOpened(true);setError('')}
 const cancel=()=>{setOpened(false);setEditing(null);setForm(blank());setError('')}
 const editor=<tr style={{background:'#fff8df'}}><td><input aria-label="Nombre" autoFocus value={form.nombre} maxLength={150} required onChange={e=>change('nombre',e.target.value)} placeholder="Nombre" style={{width:'100%',minWidth:150}}/></td><td><input aria-label="Cantidad programada" value={form.cajas_18} type="number" min="1" step="1" required onChange={e=>change('cajas_18',e.target.value)} style={{width:100}}/></td><td><input aria-label="Fecha prevista" value={form.fecha_prevista} type="date" onChange={e=>change('fecha_prevista',e.target.value)}/></td><td><input aria-label="Notas" value={form.notas} maxLength={1000} onChange={e=>change('notas',e.target.value)} placeholder="Opcional"/></td><td><button type="submit" disabled={saving} className="primary">{saving?'Guardando…':'Guardar'}</button> <button type="button" disabled={saving} onClick={cancel}>Cancelar</button></td></tr>
 return <section className="panel personal-plan"><div className="panelhead"><div><h3>Mi programación personal · semana {isoWeek(start).week}</h3><p>Programación por día · cajas de 18 kg</p></div></div>
 {error&&<div className="formerror" role="alert">{error}</div>}
 {loading?<p>Cargando tus anotaciones…</p>:<>
 <div className="personal-plan-total">{progress&&<><span>Faltan para Europa: <b>{fmt(progress.pending)} cajas</b></span><span>Por programar: <b>{fmt(Math.max(0,progress.pending-rows.reduce((n,r)=>n+Number(r.cajas_18),0)))} cajas</b></span></>}<span>Total programado: <b>{fmt(rows.reduce((n,r)=>n+Number(r.cajas_18),0))} cajas</b></span></div>
 <form onSubmit={save}><div className="order-needs-scroll"><table style={{width:'100%',borderCollapse:'collapse'}}><thead style={{background:'#ed9800',color:'white'}}><tr><th>Nombre</th><th>Programado</th><th>Fecha</th><th>Notas</th><th></th></tr></thead>
 {groups.filter(g=>g.date||g.items.length||opened&&!days.some(([,d])=>d===form.fecha_prevista)).map(g=><tbody key={g.name}>
 <tr style={{background:'#fff3c4',borderTop:'12px solid white'}}><th colSpan="4" style={{textAlign:'left',padding:10}}>{g.name}</th><th style={{background:'#d6a500',color:'white',padding:10}}>Total: {fmt(g.items.reduce((n,r)=>n+Number(r.cajas_18),0))}</th></tr>
 {g.items.map(row=>editing===row.id&&opened?React.cloneElement(editor,{key:row.id}):<tr key={row.id}><td><button type="button" disabled={saving} onClick={()=>begin(row,g.date)} style={{background:'transparent',border:0,textAlign:'left',fontWeight:600}}>{row.nombre}</button></td><td><button type="button" disabled={saving} onClick={()=>begin(row,g.date)} style={{background:'transparent',border:0}}>{fmt(row.cajas_18)}</button></td><td>{row.fecha_prevista||'—'}</td><td>{row.notas||''}</td><td><button type="button" disabled={saving} onClick={()=>begin(row,g.date)}>Editar</button> <button type="button" disabled={saving} onClick={()=>remove(row)}>Borrar</button></td></tr>)}
 {opened&&!editing&&(g.date?form.fecha_prevista===g.date:!days.some(([,d])=>d===form.fecha_prevista))&&editor}
 <tr><td colSpan="5"><button type="button" disabled={saving||opened} onClick={()=>begin(null,g.date)} style={{width:'100%',textAlign:'left',background:'transparent',color:'#777'}}>+ Agregar fila {g.date?'para '+g.name.toLowerCase():''}</button></td></tr>
 </tbody>)}</table></div></form>
 </>}
 <p className="yuca-count-message">Solo vos ves y modificás este cuadro. Tocá un nombre o cantidad para editar. El faltante de Europa se actualiza desde el programa; las anotaciones las manejás vos.</p></section>
}

