import React,{useEffect,useState} from 'react'
import {X} from 'lucide-react'
import {supabase} from './supabase'

const local=v=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Costa_Rica',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)).replace(' ','T')
const instant=v=>new Date(`${v}:00-06:00`).toISOString()
const day=v=>local(v).slice(0,10)
export default function PlantAttendance(){
 const [workers,setWorkers]=useState([]),[rows,setRows]=useState([]),[query,setQuery]=useState(''),[form,setForm]=useState(null),[saving,setSaving]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 const reload=async()=>{setLoading(true);const [a,b]=await Promise.all([supabase.from('colaboradores_asistencia').select('id,nombre,puesto,activo').order('nombre').limit(1000),supabase.from('registro_asistencia_operacion').select('*').order('entrada',{ascending:false}).limit(1000)]);setLoading(false);if(a.error||b.error){setError(a.error?.message||b.error?.message);return}setWorkers(a.data||[]);setRows(b.data||[])}
 useEffect(()=>{reload()},[])
 const start=(w,open)=>{setError('');setForm({worker:w,row:open,at:local(new Date()),cuadrilla:open?.cuadrilla||'Diurna',descanso:'0',extras:'0',feriado:false,observaciones:open?.observaciones||''})}
 const save=async()=>{setSaving(true);setError('');try{if(!form.at)throw Error('Indique fecha y hora.');const at=instant(form.at);if(form.row&&new Date(at)<=new Date(form.row.entrada))throw Error('La salida debe ser posterior a la entrada.');const result=form.row?await supabase.rpc('anotar_salida_planta',{p_asistencia_id:form.row.id,p_salida:at,p_descanso_minutos:Number(form.descanso),p_horas_extra:Number(form.extras),p_feriado_pago_doble:form.feriado,p_observaciones:form.observaciones}):await supabase.rpc('anotar_entrada_planta',{p_trabajador_id:form.worker.id,p_entrada:at,p_cuadrilla:form.cuadrilla,p_observaciones:form.observaciones});if(result.error)throw result.error;setForm(null);await reload()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const today=day(new Date()),todays=rows.filter(r=>day(r.entrada)===today),openRows=rows.filter(r=>!r.salida)
 return <><div className="modulebar"><p>Marque la entrada y la salida de cada colaborador. Puede corregir la hora antes de guardar. Las tarifas y el cálculo de planilla se manejan en oficina.</p><button onClick={reload}>Actualizar lista</button></div>{error&&!form&&<div className="formerror" role="alert">{error}</div>}
 <div className="weekly-grid"><article><small>Asistencia de hoy · {today}</small><div><span>Entradas registradas</span><b>{todays.length}</b></div><div><span>Turnos abiertos</span><b>{openRows.length}</b></div><div><span>Salidas de hoy</span><b>{todays.filter(r=>r.salida).length}</b></div></article></div>
 <section className="panel tablepanel"><h3>Colaboradores</h3><div className="supply-tools"><label>Buscar persona<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o puesto…"/></label></div><div className="supply-operations-table"><table><thead><tr><th>Colaborador</th><th>Estado</th><th>Última entrada</th><th>Acción</th></tr></thead><tbody>{workers.filter(w=>w.activo&&`${w.nombre} ${w.puesto||''}`.toLowerCase().includes(query.toLowerCase())).map(w=>{const recent=rows.find(r=>r.trabajador_id===w.id),open=rows.find(r=>r.trabajador_id===w.id&&!r.salida);return <tr key={w.id}><td><b>{w.nombre}</b><small>{w.puesto||'Sin puesto registrado'}</small></td><td>{open?'En turno':'Sin turno abierto'}</td><td>{recent?local(recent.entrada).replace('T',' · '):'—'}</td><td><button className={open?'primary':''} onClick={()=>start(w,open)}>{open?'Anotar salida':'Anotar entrada'}</button></td></tr>})}</tbody></table></div>{loading&&<p>Cargando…</p>}</section>
 <section className="panel tablepanel"><h3>Marcaciones recientes</h3><div className="supply-operations-table"><table><thead><tr><th>Colaborador</th><th>Entrada</th><th>Salida</th><th>Cuadrilla</th><th>Descanso</th><th>Extras</th><th>Observaciones</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.id}><td>{r.nombre}</td><td>{local(r.entrada).replace('T',' · ')}</td><td>{r.salida?local(r.salida).replace('T',' · '):'Pendiente'}</td><td>{r.cuadrilla}</td><td>{r.salida?`${r.descanso_minutos} min`:'—'}</td><td>{r.salida?r.horas_extra:'—'}</td><td>{r.observaciones||'—'}</td></tr>)}</tbody></table></div>{!rows.length&&!loading&&<p>Aún no hay marcaciones.</p>}</section>
 {form&&<div className="modalwrap"><div className="modal plant-form weekly-modal"><div className="modalhead"><div><span>REGISTRO DE ASISTENCIA</span><h2>{form.row?'Anotar salida':'Anotar entrada'} · {form.worker.nombre}</h2></div><button onClick={()=>setForm(null)} aria-label="Cerrar"><X/></button></div><div className="formgrid"><label>{form.row?'Fecha y hora de salida':'Fecha y hora de entrada'} *<input type="datetime-local" value={form.at} onChange={e=>setForm({...form,at:e.target.value})}/></label>{form.row?<><p className="wide">Entrada: <b>{local(form.row.entrada).replace('T',' · ')}</b></p><label>Descanso sin labor (minutos)<input type="number" min="0" step="1" value={form.descanso} onChange={e=>setForm({...form,descanso:e.target.value})}/></label><label>Horas extra dentro del turno<input type="number" min="0" step="0.01" value={form.extras} onChange={e=>setForm({...form,extras:e.target.value})}/></label><label className="checklabel"><input type="checkbox" checked={form.feriado} onChange={e=>setForm({...form,feriado:e.target.checked})}/> Feriado con pago doble aplicable</label></>:<label>Cuadrilla<select value={form.cuadrilla} onChange={e=>setForm({...form,cuadrilla:e.target.value})}><option>Diurna</option><option>Nocturna</option></select></label>}<label className="wide">Observaciones<input value={form.observaciones} onChange={e=>setForm({...form,observaciones:e.target.value})} placeholder="Opcional"/></label></div>{error&&<div className="formerror" role="alert">{error}</div>}<div className="modalactions"><button onClick={()=>setForm(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving}>{saving?'Guardando…':`Guardar ${form.row?'salida':'entrada'}`}</button></div></div></div>}</>
}
