import React, {useEffect, useState} from 'react'
import {X} from 'lucide-react'
import {supabase} from './supabase'

const products=['Yuca','Ñampí','Cabeza de ñampí','Camote','Caña de azúcar','Jengibre','Cúrcuma','Malanga lila','Malanga blanca','Malanga taro','Papa china','Ñame','Chayote','Ayote']
const initial=()=>({fecha:new Date().toLocaleDateString('en-CA'),fecha_labor:'',boleta_campo_referencia:'',boleta_entrada_id:'',proveedor_id:'',productor_nombre:'',productor_direccion:'',productor_telefono:'',productor_cedula:'',producto:'',cantidad_comprada:'',cantidad_recibida:'',unidad:'Quintales (46 kg)',tipo_compra:'A rendimiento',precio_europa:'',precio_eeuu:'',precio_segunda_gruesa:'',precio_segunda_menuda:'',precio_rechazo:'',precio_campo:'',precio_en_pie:'',flete:'',cuadrilla_arranca:'',adelanto:'',chofer:'',transportista:'',placa:'',observaciones:''})

export default function PurchaseOrderModal({order,close,onSaved,userId}){
  const [form,setForm]=useState(()=>order?Object.fromEntries(Object.entries(initial()).map(([key,value])=>[key,order[key]??value])):initial());const [providers,setProviders]=useState([]);const [receipts,setReceipts]=useState([]);const [linkedReceipts,setLinkedReceipts]=useState([])
  const [newProducer,setNewProducer]=useState(null)
  const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{let active=true;supabase.from('proveedores').select('id,nombre,telefono,residencia,cedula,zona,tipo,productos').eq('activo',true).order('nombre').then(({data,error:loadError})=>{if(!active)return;if(loadError)setError('No se pudieron cargar los productores registrados.');else setProviders(data||[])});return()=>{active=false}},[])
  useEffect(()=>{let active=true;supabase.from('boletas_entrada').select('id,codigo,producto,fecha_hora,orden_compra_id').order('fecha_hora',{ascending:false}).limit(100).then(({data})=>{if(!active)return;setReceipts((data||[]).filter(item=>!item.orden_compra_id));setLinkedReceipts((data||[]).filter(item=>item.orden_compra_id===order?.id))});return()=>{active=false}},[order?.id])
  const change=(name,value)=>setForm(current=>({...current,[name]:value}))
  const chooseProvider=value=>{const provider=providers.find(item=>item.id===value);setForm(current=>({...current,proveedor_id:value,productor_nombre:provider?.nombre||'',productor_direccion:provider?.residencia||'',productor_telefono:provider?.telefono||'',productor_cedula:provider?.cedula||''}))}
  const createProducer=async()=>{
    if(!newProducer.nombre.trim()){setError('Escriba el nombre del productor.');return}
    setSaving(true);setError('')
    const {data,error:producerError}=await supabase.from('proveedores').insert({nombre:newProducer.nombre.trim(),cedula:newProducer.cedula.trim()||null,telefono:newProducer.telefono.trim()||null,residencia:newProducer.residencia.trim()||null,zona:newProducer.zona.trim()||null,tipo:newProducer.tipo,productos:newProducer.productos.trim()?newProducer.productos.split(',').map(x=>x.trim()).filter(Boolean):[]}).select('id,nombre,telefono,residencia,cedula,zona,tipo,productos').single()
    setSaving(false);if(producerError){setError(`No se pudo guardar el productor: ${producerError.message}`);return}
    setProviders(current=>[...current,data].sort((a,b)=>a.nombre.localeCompare(b.nombre,'es')));setNewProducer(null);chooseProviderFrom(data)
  }
  const chooseProviderFrom=provider=>setForm(current=>({...current,proveedor_id:provider.id,productor_nombre:provider.nombre,productor_direccion:provider.residencia||'',productor_telefono:provider.telefono||'',productor_cedula:provider.cedula||''}))
  const save=async()=>{
    if(!form.fecha||!form.producto||(!form.proveedor_id&&!order?.productor_nombre)){setError('Seleccione productor y producto, o agregue un productor nuevo.');return}
    const bought=form.cantidad_comprada===''?null:Number(form.cantidad_comprada)
    const arrived=form.cantidad_recibida===''?null:Number(form.cantidad_recibida)
    if((bought!==null&&(!Number.isFinite(bought)||bought<0))||(arrived!==null&&(!Number.isFinite(arrived)||arrived<0))){setError('Las cantidades deben ser números iguales o mayores que cero.');return}
    const moneyFields=['precio_europa','precio_eeuu','precio_segunda_gruesa','precio_segunda_menuda','precio_rechazo','precio_campo','precio_en_pie','flete','cuadrilla_arranca','adelanto']
    if(moneyFields.some(key=>form[key]!==''&&(!Number.isFinite(Number(form[key]))||Number(form[key])<0))){setError('Los precios y adelantos deben ser números iguales o mayores que cero.');return}
    setSaving(true);setError('')
    const prices=Object.fromEntries(moneyFields.map(key=>[key,form[key]===''?null:Number(form[key])]))
    const payload={fecha:form.fecha,fecha_labor:form.fecha_labor||null,boleta_campo_referencia:form.boleta_campo_referencia.trim()||null,proveedor_id:form.proveedor_id||null,productor_nombre:form.productor_nombre.trim(),productor_direccion:form.productor_direccion.trim()||null,productor_telefono:form.productor_telefono.trim()||null,productor_cedula:form.productor_cedula.trim()||null,producto:form.producto,cantidad_comprada:bought,cantidad_recibida:arrived,unidad:form.unidad,tipo_compra:form.tipo_compra,...prices,chofer:form.chofer.trim()||null,transportista:form.transportista.trim()||null,placa:form.placa.trim()||null,observaciones:form.observaciones.trim()||null}
    const {data:savedOrder,error:saveError}=await (order?supabase.from('ordenes_compra').update(payload).eq('id',order.id):supabase.from('ordenes_compra').insert({...payload,codigo:`OC-${Date.now()}`,creado_por:userId})).select('id').single()
    if(saveError){setSaving(false);setError(`No se pudo guardar la orden: ${saveError.message}`);return}
    if(form.boleta_entrada_id){const {data:linked,error:linkError}=await supabase.from('boletas_entrada').update({orden_compra_id:savedOrder.id}).eq('id',form.boleta_entrada_id).is('orden_compra_id',null).select('id').single();if(linkError||!linked){setSaving(false);setError('La orden se guardó, pero no se pudo enlazar la boleta. Revise si otro usuario la enlazó primero.');return}}
    setSaving(false);onSaved()
  }
  return <div className="modalwrap"><div className="modal purchaseform"><div className="modalhead"><div><span>{order?'EDITAR REGISTRO':'NUEVO REGISTRO'}</span><h2>Orden de compra</h2></div><button onClick={close} aria-label="Cerrar"><X/></button></div>
    <div className="formsection"><h3>Fechas y boletas</h3><div className="formgrid"><label>Fecha de la orden *<input type="date" value={form.fecha} onChange={e=>change('fecha',e.target.value)}/></label><label>Fecha de labor del producto<input type="date" value={form.fecha_labor} onChange={e=>change('fecha_labor',e.target.value)}/></label><label className="wide">Boleta de campo (referencia)<input value={form.boleta_campo_referencia} onChange={e=>change('boleta_campo_referencia',e.target.value)} placeholder="Número o referencia de la boleta"/></label>{linkedReceipts.length>0&&<p className="purchasehint wide">Boletas de planta enlazadas: {linkedReceipts.map(r=>r.codigo).join(', ')}</p>}<label className="wide">Enlazar otra boleta de entrada de planta<select value={form.boleta_entrada_id} onChange={e=>change('boleta_entrada_id',e.target.value)}><option value="">Enlazar después, cuando planta registre la entrada</option>{receipts.map(r=><option key={r.id} value={r.id}>{r.codigo} · {r.producto} · {new Date(r.fecha_hora).toLocaleDateString('es-CR')}</option>)}</select></label></div></div>
    <div className="formsection"><h3>Productor</h3><div className="formgrid"><label className="wide">Productor *<select value={form.proveedor_id} onChange={e=>chooseProvider(e.target.value)}><option value="">Seleccione un productor</option>{providers.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label>{!form.proveedor_id&&order?.productor_nombre&&<p className="purchasehint wide">Productor registrado anteriormente: {order.productor_nombre}. Puede seleccionar su ficha para vincularlo.</p>}<button className="purchase-new-producer" type="button" onClick={()=>setNewProducer({nombre:'',cedula:'',residencia:'',telefono:'',zona:'',tipo:'Agricultor',productos:''})}>+ Nuevo productor</button></div>{newProducer&&<div className="producer-card"><strong>Ficha del productor nuevo</strong><div className="formgrid"><label>Nombre completo *<input value={newProducer.nombre} onChange={e=>setNewProducer({...newProducer,nombre:e.target.value})}/></label><label>Cédula<input value={newProducer.cedula} onChange={e=>setNewProducer({...newProducer,cedula:e.target.value})}/></label><label>Dirección o residencia<input value={newProducer.residencia} onChange={e=>setNewProducer({...newProducer,residencia:e.target.value})}/></label><label>Teléfono<input type="tel" value={newProducer.telefono} onChange={e=>setNewProducer({...newProducer,telefono:e.target.value})}/></label><label>Zona<input value={newProducer.zona} onChange={e=>setNewProducer({...newProducer,zona:e.target.value})}/></label><label>Tipo<select value={newProducer.tipo} onChange={e=>setNewProducer({...newProducer,tipo:e.target.value})}><option>Agricultor</option><option>Intermediario</option><option>Propio</option></select></label><label className="wide">Productos que entrega (separados por coma)<input value={newProducer.productos} onChange={e=>setNewProducer({...newProducer,productos:e.target.value})}/></label></div><div className="producer-actions"><button type="button" onClick={()=>setNewProducer(null)}>Cancelar</button><button type="button" className="primary" disabled={saving} onClick={createProducer}>Guardar productor</button></div></div>}</div>
    <div className="formsection"><h3>Producto y cantidades</h3><div className="formgrid"><label>Producto *<select value={form.producto} onChange={e=>change('producto',e.target.value)}><option value="">Seleccione un producto</option>{products.map(p=><option key={p} value={p}>{p}</option>)}</select></label><label>Unidad<select value={form.unidad} onChange={e=>change('unidad',e.target.value)}>{['Kilogramos','Quintales (46 kg)','Cajas','Sacos','Unidades'].map(u=><option key={u}>{u}</option>)}</select></label><label>Cantidad de producto comprado<input type="number" min="0" step="0.01" inputMode="decimal" value={form.cantidad_comprada} onChange={e=>change('cantidad_comprada',e.target.value)}/></label><label>Cantidad de producto que llegó<input type="number" min="0" step="0.01" inputMode="decimal" value={form.cantidad_recibida} onChange={e=>change('cantidad_recibida',e.target.value)}/></label></div></div>
    <div className="formsection"><h3>Acuerdo de compra y precios</h3><div className="formgrid"><label className="wide">Modalidad de compra<select value={form.tipo_compra} onChange={e=>change('tipo_compra',e.target.value)}>{['A rendimiento','Puesto en camión','En campo','En pie','Cosecha propia','Otra'].map(x=><option key={x}>{x}</option>)}</select></label><p className="purchasehint wide">Precios acordados editables en colones por quintal de 46 kg. En compras por rendimiento, el pago final queda pendiente de la boleta y del rendimiento de planta.</p>{[['precio_europa','Yuca europea (₡/quintal)'],['precio_eeuu','Yuca estadounidense o genérica (₡/quintal)'],['precio_segunda_gruesa','Segunda gruesa (₡/quintal)'],['precio_segunda_menuda','Segunda menuda, cuando se paga (₡/quintal)'],['precio_rechazo','Rechazo (₡/quintal)'],['precio_campo','Precio en campo (₡/quintal)'],['precio_en_pie','Precio en pie (₡ por lote)'],['flete','Flete acordado (₡)'],['cuadrilla_arranca','Cuadrilla de arranca (₡)'],['adelanto','Adelanto entregado (₡)']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="0.01" inputMode="decimal" value={form[key]} onChange={e=>change(key,e.target.value)} placeholder="Opcional"/></label>)}</div></div>
    <div className="formsection"><h3>Transporte</h3><div className="formgrid"><label>Chofer<input value={form.chofer} onChange={e=>change('chofer',e.target.value)}/></label><label>Transportista<input value={form.transportista} onChange={e=>change('transportista',e.target.value)}/></label><label>Placa<input value={form.placa} onChange={e=>change('placa',e.target.value)}/></label><label className="wide">Observaciones<textarea rows="3" value={form.observaciones} onChange={e=>change('observaciones',e.target.value)}/></label></div></div>
    {error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={close} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving||!!newProducer}>{saving?'Guardando…':order?'Guardar cambios':'Guardar orden'}</button></div>
  </div></div>
}
