import React, {useEffect, useState} from 'react'
import {Plus,X} from 'lucide-react'
import {supabase} from './supabase'

const productOptions=['Yuca','Ñampí','Cabeza de ñampí','Camote','Caña de azúcar','Jengibre','Cúrcuma','Malanga lila','Malanga blanca','Malanga taro','Papa china','Ñame','Chayote','Ayote']
const countries=['Estados Unidos','Canadá','Costa Rica','España','Francia','Países Bajos','Alemania','Italia','Reino Unido','Portugal','Bélgica','Panamá','Otro']
const emptyLine=(positions=[1])=>({producto:'Yuca',presentacion_kg:'18',paletas:String(positions.length),cajas_por_paleta:'60',precio_caja:'',carton_id:'',carton_marca:'',posiciones:positions})
const usd=new Intl.NumberFormat('es-CR',{style:'currency',currency:'USD',minimumFractionDigits:2})
const numeric=v=>Number(String(v).replace(',','.'))
const boxes=line=>numeric(line.paletas)*numeric(line.cajas_por_paleta)
const chooseFree=(lines,count)=>{const used=new Set(lines.flatMap(l=>l.posiciones));return Array.from({length:22},(_,i)=>i+1).filter(n=>!used.has(n)).slice(0,count)}

export default function SalesOrderModal({order,close,onSaved}){
  const [form,setForm]=useState(()=>({fecha:order?.fecha||new Date().toLocaleDateString('en-CA'),fecha_salida:order?.fecha_salida||'',cliente_id:order?.cliente_id||'',mercado:order?.mercado||'Estados Unidos',pais_destino:order?.pais_destino||'Estados Unidos',contenedor:order?.contenedor||'',observaciones:order?.observaciones||''}))
  const [lines,setLines]=useState(order?[]:[emptyLine()]);const [clients,setClients]=useState([]);const [cartons,setCartons]=useState([]);const [reserved,setReserved]=useState({});const [loaded,setLoaded]=useState(!order)
  const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{let active=true;Promise.all([supabase.from('clientes').select('id,nombre').eq('activo',true).order('nombre'),supabase.from('inventario_cartones').select('id,marca,descripcion,existencia,minimo_alerta,presentacion_kg').eq('activo',true).order('marca'),supabase.from('ordenes_venta_lineas').select('orden_venta_id,carton_id,cantidad_cajas').not('carton_id','is',null)]).then(([c,boxesResult,r])=>{if(!active)return;if(c.error||boxesResult.error||r.error){setError('No se pudieron cargar clientes o cartones.');return}setClients(c.data||[]);setCartons(boxesResult.data||[]);const count={};for(const row of r.data||[]){if(row.orden_venta_id===order?.id)continue;count[row.carton_id]=(count[row.carton_id]||0)+row.cantidad_cajas}setReserved(count)});return()=>{active=false}},[order?.id])
  useEffect(()=>{if(!order)return;let active=true;Promise.all([supabase.from('ordenes_venta_lineas').select('*').eq('orden_venta_id',order.id).order('id'),supabase.from('ordenes_venta_paletas').select('linea_id,posicion').eq('orden_venta_id',order.id)]).then(([a,b])=>{if(!active)return;if(a.error||b.error){setError('No se pudieron cargar los productos de la orden.');return}const assigned=new Set();setLines((a.data||[]).map(row=>{let positions=(b.data||[]).filter(p=>p.linea_id===row.id).map(p=>p.posicion).sort((x,y)=>x-y);if(!positions.length){positions=Array.from({length:22},(_,i)=>i+1).filter(n=>!assigned.has(n)).slice(0,row.paletas||1)}positions.forEach(n=>assigned.add(n));return {...row,paletas:String(positions.length),presentacion_kg:String(row.presentacion_kg||''),cajas_por_paleta:String(row.cajas_por_paleta||''),precio_caja:String(row.precio_caja||''),carton_id:row.carton_id||'',carton_marca:row.carton_marca||'',posiciones:positions}}));setLoaded(true)});return()=>{active=false}},[order?.id])
  const change=(field,value)=>setForm(current=>({...current,[field]:value}))
  const changeLine=(index,field,value)=>setLines(current=>current.map((line,i)=>i===index?{...line,[field]:value,...(field==='carton_id'?{carton_marca:cartons.find(c=>c.id===value)?.marca||line.carton_marca}:{})}:line))
  const changePallets=(index,value)=>{const qty=Number(value);if(!Number.isInteger(qty)||qty<1||qty>22)return;setLines(current=>{const others=current.filter((_,i)=>i!==index);const old=current[index].posiciones;const free=chooseFree(others,22);if(qty>free.length)return current;const positions=qty<=old.length?old.slice(0,qty):[...old,...free.filter(n=>!old.includes(n)).slice(0,qty-old.length)];return current.map((line,i)=>i===index?{...line,paletas:String(qty),posiciones:positions}:line)})}
  const togglePosition=(index,pos)=>setLines(current=>{if(current.some((line,i)=>i!==index&&line.posiciones.includes(pos)))return current;return current.map((line,i)=>{if(i!==index)return line;const positions=line.posiciones.includes(pos)?line.posiciones.filter(n=>n!==pos):[...line.posiciones,pos].sort((a,b)=>a-b);return {...line,posiciones,paletas:String(positions.length)}})})
  const addLine=()=>{const free=chooseFree(lines,1);if(!free.length){setError('El contenedor ya tiene sus 22 posiciones ocupadas.');return}setError('');setLines(current=>[...current,emptyLine(free)])}
  const totalBoxes=lines.reduce((sum,line)=>sum+boxes(line),0)
  const total=lines.reduce((sum,line)=>sum+boxes(line)*numeric(line.precio_caja),0)
  const demands={};for(const line of lines){if(line.carton_id)demands[line.carton_id]=(demands[line.carton_id]||0)+boxes(line)}
  const shortages=cartons.filter(c=>demands[c.id]>c.existencia-(reserved[c.id]||0))
  const save=async()=>{
    if(!form.cliente_id||!form.fecha||!form.fecha_salida||!form.pais_destino.trim()){setError('Seleccione cliente, ambas fechas y país de destino.');return}
    if(!lines.length||lines.some(l=>!l.producto||!Number.isFinite(numeric(l.presentacion_kg))||numeric(l.presentacion_kg)<=0||!Number.isInteger(numeric(l.cajas_por_paleta))||numeric(l.cajas_por_paleta)<=0||!Number.isFinite(numeric(l.precio_caja))||numeric(l.precio_caja)<=0||!l.posiciones.length||l.posiciones.length!==Number(l.paletas))){setError('Complete producto, peso, cajas por paleta, precio y posiciones de cada línea.');return}
    if(lines.flatMap(l=>l.posiciones).length>22||new Set(lines.flatMap(l=>l.posiciones)).size!==lines.flatMap(l=>l.posiciones).length){setError('Cada posición del contenedor debe usarse una sola vez (máximo 22).');return}
    setSaving(true);setError('')
    const payload=lines.map(l=>({producto:l.producto,presentacion_kg:numeric(l.presentacion_kg),paletas:l.posiciones.length,cajas_por_paleta:numeric(l.cajas_por_paleta),cantidad_cajas:boxes(l),precio_caja:numeric(l.precio_caja),carton_id:l.carton_id||null,carton_marca:l.carton_marca.trim()||null,posiciones:l.posiciones}))
    const {error:saveError}=await supabase.rpc('guardar_orden_venta',{p_orden_id:order?.id||null,p_codigo:order?.codigo||`OV-${Date.now()}`,p_fecha:form.fecha,p_fecha_salida:form.fecha_salida,p_cliente_id:form.cliente_id,p_mercado:form.mercado,p_pais_destino:form.pais_destino.trim(),p_contenedor:form.contenedor.trim()||null,p_observaciones:form.observaciones.trim()||null,p_lineas:payload})
    setSaving(false);if(saveError){setError(`No se pudo guardar la orden: ${saveError.message}`);return}onSaved()
  }
  const available=carton=>carton.existencia-(reserved[carton.id]||0)
  return <div className="modalwrap"><div className="modal salesform"><div className="modalhead"><div><span>{order?'EDITAR REGISTRO':'NUEVO REGISTRO'}</span><h2>Orden de venta</h2></div><button onClick={close} aria-label="Cerrar"><X/></button></div>
    <div className="formsection"><h3>Cliente y destino</h3><div className="formgrid"><label>Fecha del pedido *<input type="date" value={form.fecha} onChange={e=>change('fecha',e.target.value)}/></label><label>Fecha de salida del contenedor *<input type="date" value={form.fecha_salida} onChange={e=>change('fecha_salida',e.target.value)}/></label><label>Cliente *<select value={form.cliente_id} onChange={e=>change('cliente_id',e.target.value)}><option value="">Seleccione un cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Número de contenedor<input value={form.contenedor} onChange={e=>change('contenedor',e.target.value)} placeholder="Se puede agregar después"/></label><label>Mercado<select value={form.mercado} onChange={e=>change('mercado',e.target.value)}>{['Estados Unidos','Europa','Canadá','Costa Rica','Otro'].map(m=><option key={m}>{m}</option>)}</select></label><label>País de destino *<select value={countries.includes(form.pais_destino)?form.pais_destino:'Otro'} onChange={e=>change('pais_destino',e.target.value==='Otro'?'':e.target.value)}>{countries.map(c=><option key={c}>{c}</option>)}</select></label>{(!countries.includes(form.pais_destino)||form.pais_destino==='Otro')&&<label className="wide">Escriba el país de destino<input value={form.pais_destino==='Otro'?'':form.pais_destino} onChange={e=>change('pais_destino',e.target.value)} placeholder="País"/></label>}</div></div>
    <div className="formsection"><h3>Productos, cartones y paletas</h3><p className="sale-help">Cada línea puede llevar otro producto, peso, precio y marca de cartón. Seleccione posiciones del 1 al 22.</p></div>
    {!loaded?<p className="sale-help">Cargando productos y paletas…</p>:<><div className="sale-lines">{lines.map((line,index)=><section className="sale-line" key={index}><div className="linehead"><b>Línea {index+1}</b>{lines.length>1&&<button className="remove" type="button" onClick={()=>setLines(current=>current.filter((_,i)=>i!==index))}>Quitar línea</button>}</div><div className="formgrid"><label>Producto<select value={line.producto} onChange={e=>changeLine(index,'producto',e.target.value)}>{productOptions.map(p=><option key={p}>{p}</option>)}</select></label><label>Peso por caja (kg)<input type="number" min="0.01" step="0.01" inputMode="decimal" value={line.presentacion_kg} onChange={e=>changeLine(index,'presentacion_kg',e.target.value)}/></label><label>Paletas<select value={line.paletas} onChange={e=>changePallets(index,e.target.value)}>{Array.from({length:22},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label><label>Cajas por paleta<input type="number" min="1" step="1" inputMode="numeric" value={line.cajas_por_paleta} onChange={e=>changeLine(index,'cajas_por_paleta',e.target.value)}/></label><label>Precio por caja (USD)<input type="number" min="0.01" step="0.01" inputMode="decimal" value={line.precio_caja} onChange={e=>changeLine(index,'precio_caja',e.target.value)} placeholder="4.50"/></label><label>Cartón del inventario<select value={line.carton_id} onChange={e=>changeLine(index,'carton_id',e.target.value)}><option value="">Sin cartón registrado</option>{cartons.map(c=><option key={c.id} value={c.id}>{c.marca} · {c.descripcion} · disponibles {available(c)}</option>)}</select></label><label className="wide">Marca de cartón<input value={line.carton_marca} onChange={e=>changeLine(index,'carton_marca',e.target.value)} placeholder="Ejemplo: Marielita, tapa rosada"/></label></div><div className="pallet-picker"><b>Posición de cada paleta ({line.posiciones.length} seleccionadas)</b><div>{Array.from({length:22},(_,i)=>i+1).map(pos=>{const taken=lines.some((other,j)=>j!==index&&other.posiciones.includes(pos));return <button key={pos} type="button" disabled={taken} className={line.posiciones.includes(pos)?'selected':''} onClick={()=>togglePosition(index,pos)} aria-label={`Posición ${pos}`}>{pos}</button>})}</div></div><div className="line-total"><span><small>PALLETAS {line.posiciones.join(', ')||'sin asignar'}</small><b>{Number.isFinite(boxes(line))?boxes(line).toLocaleString('es-CR'):0} cajas · {line.paletas} paletas</b></span><strong>Subtotal: {usd.format(boxes(line)*numeric(line.precio_caja)||0)}</strong></div></section>)}</div><button className="addline" type="button" onClick={addLine}><Plus size={18}/>Agregar producto o presentación</button></>}
    {shortages.length>0&&<div className="stock-alert">Cartón insuficiente para {shortages.map(c=>`${c.marca} (${demands[c.id]} solicitados; ${available(c)} disponibles)`).join(', ')}. Puede guardar la orden, pero debe reponer cartones antes de preparar el contenedor.</div>}
    <label className="notes">Observaciones<textarea value={form.observaciones} onChange={e=>change('observaciones',e.target.value)} rows="3"/></label><div className="order-total"><span>{totalBoxes.toLocaleString('es-CR')} cajas · {lines.reduce((n,l)=>n+l.posiciones.length,0)}/22 paletas</span><b>Total de la orden: {usd.format(total)}</b></div><p className="sale-help">Total previsto para cuentas por cobrar. El cobro se registrará al emitir la factura; los cartones se reservan aquí y se descuentan de la existencia física al despachar.</p>
    {error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={close} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving||!loaded}>{saving?'Guardando…':order?'Guardar cambios':'Guardar orden'}</button></div>
  </div></div>
}
