import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
import {costaRicaToday} from './weekly-model'
import {packageEquivalent} from './supply-packages'
import {X} from 'lucide-react'
const fmt=n=>Number(n||0).toLocaleString('es-CR',{maximumFractionDigits:3})
export default function SupplyOperations({go,role}){
  const [items,setItems]=useState([]),[pending,setPending]=useState([]),[receipts,setReceipts]=useState([]),[filter,setFilter]=useState(''),[modal,setModal]=useState(null),[form,setForm]=useState({}),[error,setError]=useState(''),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true)
  const load=async()=>{const [a,b,c]=await Promise.all([supabase.from('inventario_insumos_operacion').select('*').order('nombre'),supabase.from('pendientes_insumos_operacion').select('*').order('fecha').limit(500),supabase.from('boletas_entrada').select('id,codigo,producto,fecha_labor').order('creado_en',{ascending:false}).limit(200)]);setLoading(false);if(a.error||b.error||c.error){setError((a.error||b.error||c.error).message);return}setItems(a.data||[]);setPending(b.data||[]);setReceipts(c.data||[])}
  useEffect(()=>{load()},[])
  const open=(kind,item)=>{setModal({kind,item});setForm({cantidad:'',fecha:costaRicaToday(),boleta_id:'',referencia:'',observaciones:''});setError('')}
  const save=async()=>{const n=Number(form.cantidad);if(!form.fecha||!Number.isFinite(n)||n<=0||Math.round(n*1000)!==n*1000){setError('Indique fecha y cantidad positiva con hasta tres decimales.');return}
    if(modal.kind==='consumo'&&n>Number(modal.item.existencia)||modal.kind==='recepcion'&&n>Number(modal.item.pendiente_presentaciones)){setError('La cantidad supera la disponible o pendiente.');return}
    setSaving(true);setError('');const args=modal.kind==='consumo'?{p_insumo_id:modal.item.id,p_cantidad:n,p_fecha:form.fecha,p_boleta_id:form.boleta_id||null,p_referencia:form.referencia.trim()||null,p_observaciones:form.observaciones.trim()||null}:{p_linea_id:modal.item.linea_id,p_cantidad:n,p_fecha:form.fecha,p_referencia:form.referencia.trim()||null}
    const {error:e}=await supabase.rpc(modal.kind==='consumo'?'consumir_insumo_operacion':'recibir_insumo_operacion',args);setSaving(false);if(e){setError(e.message);return}setModal(null);load()}
  return <><div className="modulebar"><div><p>Busque el material, revise cuánto hay y registre lo que ingresó o se utilizó. Los importes se calculan en administración.</p></div>{['administrador','oficina'].includes(role)&&<div className="cost-buttons"><button onClick={()=>go('Catálogo de insumos')}>Catálogo y precios</button><button className="primary" onClick={()=>go('Órdenes de insumos')}>Compras y recepciones</button></div>}</div><div className="bank-note">Comprar y recibir son dos pasos: la orden guarda las cajas y su precio; al confirmar la recepción, el inventario suma los kilos. Parafina y cera se compran en cajas de 25 kg.</div><div className="supply-tools"><label>Buscar insumo<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Parafina, cloro, desinfectante…"/></label><span>{items.length} insumos</span></div>{error&&!modal&&<div className="formerror" role="alert">{error}</div>}
  {loading?<div className="empty">Cargando inventario…</div>:<><section className="panel tablepanel"><h3>Inventario de insumos</h3><div className="supply-operations-table"><table><thead><tr><th>Insumo</th><th>Existencia</th><th>Unidad</th><th>Mínimo</th><th>Acciones</th></tr></thead><tbody>{items.filter(x=>x.activo&&`${x.nombre} ${x.categoria}`.toLowerCase().includes(filter.toLowerCase())).map(x=><tr key={x.id}><td><b>{x.nombre}</b><small>{x.categoria}</small></td><td><strong>{fmt(x.existencia)}</strong>{packageEquivalent(x)&&<small className="supply-equivalent">{packageEquivalent(x)}</small>}</td><td>{x.unidad}</td><td>{fmt(x.minimo)}</td><td><button type="button" disabled={Number(x.existencia)<=0} onClick={()=>open('consumo',x)}>Anotar uso</button>{pending.filter(p=>p.nombre===x.nombre).map(p=><button key={p.linea_id} type="button" onClick={()=>open('recepcion',p)}>Recibir {fmt(p.pendiente_presentaciones)} × {p.presentacion}</button>)}</td></tr>)}</tbody></table></div></section><div className="bank-note">Si se usa parafina durante una boleta, seleccione esa boleta al anotar el consumo. Para cloro, jabón o desinfectante puede dejarla sin boleta y describir la limpieza.</div></>}
  {modal&&<div className="modalwrap"><div className="modal plant-form weekly-modal"><div className="modalhead"><div><span>INVENTARIO DE INSUMOS</span><h2>{modal.kind==='consumo'?'Anotar uso':'Recibir material'} · {modal.item.nombre}</h2></div><button onClick={()=>setModal(null)} aria-label="Cerrar"><X/></button></div><p>{modal.kind==='consumo'?`Existencia actual: ${fmt(modal.item.existencia)} ${modal.item.unidad}`:`Pendiente: ${fmt(modal.item.pendiente_presentaciones)} ${modal.item.presentacion} de ${fmt(modal.item.unidades_por_presentacion)} ${modal.item.unidad}`}</p><div className="supply-equivalent">{modal.kind==='consumo'&&packageEquivalent(modal.item)}</div><div className="formgrid"><label>Fecha *<input type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></label><label>Cantidad ({modal.kind==='consumo'?modal.item.unidad:modal.item.presentacion}) *<input type="number" min="0.001" step="0.001" value={form.cantidad} onChange={e=>setForm({...form,cantidad:e.target.value})}/></label>{modal.kind==='consumo'&&<label className="wide">Boleta de proceso (si corresponde)<select value={form.boleta_id} onChange={e=>setForm({...form,boleta_id:e.target.value})}><option value="">Uso general de planta / aseo</option>{receipts.map(r=><option key={r.id} value={r.id}>{r.codigo} · {r.producto} · {r.fecha_labor||''}</option>)}</select></label>}<label className="wide">{modal.kind==='recepcion'?'Factura o referencia':'Actividad o referencia'}<input value={form.referencia} onChange={e=>setForm({...form,referencia:e.target.value})} placeholder={modal.kind==='consumo'?'Limpieza de sanitarios, proceso de yuca…':'Número de entrega o factura'}/></label>{modal.kind==='consumo'&&<label className="wide">Observaciones<input value={form.observaciones} onChange={e=>setForm({...form,observaciones:e.target.value})}/></label>}</div>{error&&<div className="formerror" role="alert">{error}</div>}<div className="modalactions"><button onClick={()=>setModal(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving}>{saving?'Guardando…':'Registrar'}</button></div></div></div>}</>
}
