import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
import ProviderModal from './provider-modal'
export default function SupplyProviders(){
  const [items,setItems]=useState([]),[filter,setFilter]=useState(''),[editing,setEditing]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
  const load=async()=>{setLoading(true);const {data,error:e}=await supabase.from('proveedores').select('*').eq('tipo','Insumos').order('nombre');setLoading(false);if(e){setError(e.message);return}setItems(data||[]);setError('')}
  useEffect(()=>{load()},[])
  return <><div className="modulebar"><p>Administre las fichas que aparecen en las compras de insumos.</p><button className="primary" onClick={()=>setEditing({new:true})}>+ Agregar proveedor de insumos</button></div><div className="supply-tools"><label>Buscar proveedor<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Nombre, contacto o correo"/></label></div>{error&&<div className="formerror">{error}</div>}{loading?<div className="empty">Cargando proveedores…</div>:<div className="supply-grid">{items.filter(p=>`${p.nombre} ${p.contacto||''} ${p.correo_facturacion||''}`.toLowerCase().includes(filter.toLowerCase())).map(p=><article key={p.id} className="supply-card"><div><small>{p.activo?'Activo':'Inactivo'}</small><h3>{p.nombre}</h3><p>Identificación: {p.cedula||'Sin registrar'}</p><p>Contacto: {p.contacto||'Sin registrar'} · Teléfono: {p.telefono||'Sin registrar'}</p><p>Facturación: {p.correo_facturacion||'Sin registrar'}</p><p>Banco: {p.banco||'Sin registrar'} · {p.moneda_cuenta||'CRC'}</p><p>Cuenta / IBAN: {p.cuenta_bancaria||'Sin registrar'}</p><p>Dirección: {p.residencia||'Sin registrar'}</p><p>Pago: {p.condiciones_pago||'Sin registrar'}</p><p>Materiales: {(p.productos||[]).join(', ')||'Sin registrar'}</p></div><div className="supply-actions"><button onClick={()=>setEditing(p)}>Editar ficha</button></div></article>)}</div>}{editing&&<ProviderModal supplyOnly provider={editing.new?null:editing} close={()=>setEditing(null)} onSaved={()=>{setEditing(null);load()}}/>}</>
}
