import React,{useEffect,useState} from 'react'
import {Plus,X} from 'lucide-react'
import {supabase} from './supabase'
import {addDays,costaRicaToday,isoWeek,sundayOf,weeklyTotals} from './weekly-model'
import {periodShare} from './cost-model'

const money=(n,currency)=>new Intl.NumberFormat('es-CR',{style:'currency',currency,maximumFractionDigits:2}).format(Number(n)||0)
const labels={planilla:'Planilla',inventario:'Material consumido',servicios:'Servicios (luz, agua, gas)',contenedor:'Gasto de contenedor',transporte:'Transporte',otros:'Otro gasto'}
const blank=()=>({fecha:costaRicaToday(),categoria:'planilla',concepto:'',moneda:'CRC',monto:'',trabajador_id:'',orden_venta_id:'',unidad:'',cantidad:'',tarifa:'',referencia:'',observaciones:''})
const value=n=>n===''?null:Number(n)

export default function WeeklyClose({go}){
  const [weekStart,setWeekStart]=useState(()=>sundayOf(costaRicaToday()))
  const [records,setRecords]=useState({sales:[],purchases:[],fixedPurchases:[],freights:[],purchasePayroll:[],openStanding:[],startedStanding:[],locals:[],costs:[],notes:[],manual:[],payroll:[],productionCosts:[],cartonCosts:[],cartonMissing:[],simulatedOrders:[],outdatedPrices:[]})
  const [workers,setWorkers]=useState([]),[orders,setOrders]=useState([]),[balances,setBalances]=useState({receivables:[],payables:[]})
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[saving,setSaving]=useState(false)
  const [rate,setRate]=useState(null),[editingRate,setEditingRate]=useState(false),[rateForm,setRateForm]=useState({usd_crc:'440',fuente:'SIMULADO: valor de trabajo',simulado:true})
  const saturday=addDays(weekStart,6),next=addDays(weekStart,7),week=isoWeek(addDays(weekStart,1))
  const reload=async()=>{
    setLoading(true);setError('')
    const results=await Promise.all([
      supabase.from('ordenes_venta').select('id,codigo,monto_cxc,moneda,mercado,finalizada_en').not('finalizada_en','is',null).gte('fecha_salida',weekStart).lte('fecha_salida',saturday),
      supabase.from('boletas_entrada').select('id,codigo,monto_cxp,finalizada_en').not('finalizada_en','is',null).gte('fecha_labor',weekStart).lte('fecha_labor',saturday),
      supabase.from('ventas_locales').select('id,codigo,fecha,moneda,ventas_segundas(subtotal)').gte('fecha',weekStart).lte('fecha',saturday),
      supabase.from('costos_operativos').select('*').gte('fecha',weekStart).lte('fecha',saturday).is('anulado_en',null).order('fecha',{ascending:false}).limit(1000),
      supabase.from('trabajadores').select('id,nombre').eq('activo',true).order('nombre').limit(1000),
      supabase.from('ordenes_venta').select('id,codigo,contenedor,fecha_salida,finalizada_en').order('creado_en',{ascending:false}).limit(1000),
      supabase.from('cxp_operativa').select('origen_id,codigo,fecha,monto,etapa').in('etapa',['Puesto en camión · precio fijo','En campo · pesaje pactado']).gte('fecha',weekStart).lte('fecha',saturday).limit(1000),
      supabase.from('cxp_operativa').select('origen,origen_id,codigo,fecha,monto,contraparte').eq('origen','flete_compra').gte('fecha',weekStart).lte('fecha',saturday).limit(1000),
      supabase.from('notas_credito_ventas').select('id,fecha,monto,motivo,ordenes_venta(codigo,moneda)').gte('fecha',weekStart).lte('fecha',saturday),
      supabase.from('cuentas_manuales').select('id,codigo,fecha,tipo,monto,moneda').gte('fecha',weekStart).lte('fecha',saturday),
      supabase.from('cxc_operativa').select('origen,origen_id,codigo,fecha,fecha_salida,moneda,monto,aplicado,etapa').lte('fecha',saturday).limit(1000),
      supabase.from('cxp_operativa').select('origen,origen_id,codigo,fecha,moneda,monto,aplicado,etapa').lte('fecha',saturday).limit(1000),
      supabase.from('planillas_planta').select('id,trabajador_id,bruto,neto').eq('semana_inicio',weekStart).is('anulado_en',null).limit(1000),
      supabase.from('costos_produccion').select('id,categoria,concepto,periodo_inicio,periodo_fin,moneda,monto,producto').lte('periodo_inicio',saturday).gte('periodo_fin',weekStart).is('anulado_en',null).limit(1000),
      supabase.from('jornadas_trabajo').select('id,trabajador_id,costo_bruto,tipo_pago').gte('fecha_labor',weekStart).lte('fecha_labor',saturday).limit(2000),
      supabase.from('planillas_fijas').select('id,trabajador_id,periodo_inicio,periodo_fin,costo_total,neto').lte('periodo_inicio',saturday).gte('periodo_fin',weekStart).limit(1000),
      supabase.from('costos_cartones').select('carton_id,fecha,cantidad,precio_unitario,moneda,simulado').lte('fecha',saturday).limit(1000),
      supabase.from('ordenes_venta_lineas').select('orden_venta_id,carton_id,cantidad_cajas,presentacion_kg').limit(2000),
      supabase.from('tasas_corte_semanal').select('usd_crc,fuente,simulado').eq('semana_inicio',weekStart).maybeSingle(),
      supabase.from('cxp_operativa').select('origen_id,codigo,fecha,monto,etapa').eq('origen','planilla_compra').gte('fecha',weekStart).lte('fecha',saturday).limit(1000),
      supabase.from('pedidos_ejercicio').select('orden_venta_id').limit(1000),
      supabase.from('ordenes_compra').select('id,codigo,fecha,precio_en_pie,en_pie_finalizada_en').eq('tipo_compra','En pie').lte('fecha',saturday).neq('estado','Anulada').limit(1000),
      supabase.from('boletas_entrada').select('orden_compra_id,fecha_labor,finalizada_en').not('orden_compra_id','is',null).not('finalizada_en','is',null).limit(2000),
      supabase.from('ordenes_compra').select('id,codigo,precio_eeuu').like('codigo',`OC-EJ-${week.week}-%`).eq('producto','Yuca').eq('precio_eeuu',7000).limit(1000)
    ])
    setLoading(false)
    const failure=results.find(r=>r.error)?.error
    if(failure){setError(`No se pudo cargar el corte: ${failure.message}`);return}
    if(results[6].data?.length===1000||results[7].data?.length===1000||results[10].data?.length===1000||results[11].data?.length===1000||results[13].data?.length===1000||results[14].data?.length===2000||results[15].data?.length===1000||results[16].data?.length===1000||results[17].data?.length===2000||results[19].data?.length===1000||results[20].data?.length===1000||results[21].data?.length===1000||results[22].data?.length===2000||results[23].data?.length===1000){setError('Hay más registros que el límite de consulta; no se muestran cifras parciales.');return}
    setRate(results[18].data||null);setEditingRate(false)
    setBalances({receivables:results[10].data||[],payables:results[11].data||[]})
    const older=results[12].data||[],legacyIds=new Set(older.map(x=>x.trabajador_id))
    const hourly=[...new Set((results[14].data||[]).filter(x=>x.tipo_pago==='Por horas'&&!legacyIds.has(x.trabajador_id)).map(x=>x.trabajador_id))].map(id=>{const total=(results[14].data||[]).filter(x=>x.trabajador_id===id).reduce((v,x)=>v+Number(x.costo_bruto||0),0);return {id:`jornadas-${id}`,trabajador_id:id,bruto:total,neto:total}})
    const fixed=(results[15].data||[]).filter(x=>!legacyIds.has(x.trabajador_id)).map(x=>({id:`fijo-${x.id}`,trabajador_id:x.trabajador_id,bruto:periodShare({periodo_inicio:x.periodo_inicio,periodo_fin:x.periodo_fin,monto:x.costo_total},weekStart,saturday),neto:periodShare({periodo_inicio:x.periodo_inicio,periodo_fin:x.periodo_fin,monto:x.neto},weekStart,saturday)}))
    const allOrders=results[5].data||[],priced=results[16].data||[],cartonCosts=[],cartonMissing=[]
    for(const line of results[17].data||[]){const order=allOrders.find(o=>o.id===line.orden_venta_id);if(!line.carton_id||!order?.finalizada_en||!order.fecha_salida||order.fecha_salida<weekStart||order.fecha_salida>saturday)continue
      const candidates=priced.filter(c=>c.carton_id===line.carton_id&&c.fecha<=order.fecha_salida&&Number(c.precio_unitario)>0),prices=[...new Set(candidates.map(c=>`${c.moneda}:${c.precio_unitario}`))]
      const usedToDate=(results[17].data||[]).filter(x=>x.carton_id===line.carton_id&&allOrders.some(o=>o.id===x.orden_venta_id&&o.finalizada_en&&o.fecha_salida<=order.fecha_salida)).reduce((sum,x)=>sum+Number(x.cantidad_cajas||0),0)
      if(prices.length!==1||candidates.reduce((sum,c)=>sum+Number(c.cantidad),0)<usedToDate){cartonMissing.push({codigo:order.codigo,cantidad:line.cantidad_cajas,reason:prices.length===0?'Falta precio':prices.length>1?'Hay varios precios; falta asignar lote':'Faltan cartones con costo'});continue}
      const [currency,unit]=prices[0].split(':');cartonCosts.push({codigo:order.codigo,moneda:currency,monto:Number(line.cantidad_cajas)*Number(unit),cantidad:line.cantidad_cajas,simulado:candidates.some(c=>c.simulado)})
    }
    const standing=(results[21].data||[]).map(order=>{
      const dates=(results[22].data||[]).filter(b=>b.orden_compra_id===order.id).map(b=>b.fecha_labor||b.finalizada_en?.slice(0,10)).filter(Boolean).sort()
      return {...order,costDate:dates[0]||order.en_pie_finalizada_en?.slice(0,10)||null,started:dates.length>0}
    })
    const standingExpense=standing.filter(x=>x.costDate>=weekStart&&x.costDate<=saturday).map(x=>({origen_id:x.id,codigo:x.codigo,fecha:x.costDate,monto:x.precio_en_pie,etapa:x.started?'Compra en pie · primer lote procesado':'Compra en pie · lote finalizado'}))
    const simulatedOrders=(results[20].data||[]).map(x=>x.orden_venta_id)
    setRecords({sales:results[0].data||[],purchases:results[1].data||[],locals:results[2].data||[],costs:results[3].data||[],fixedPurchases:[...(results[6].data||[]),...standingExpense],freights:results[7].data||[],purchasePayroll:results[19].data||[],openStanding:standing.filter(x=>!x.costDate&&!x.en_pie_finalizada_en),startedStanding:standing.filter(x=>x.started&&!x.en_pie_finalizada_en&&x.costDate>=weekStart&&x.costDate<=saturday),notes:results[8].data||[],manual:results[9].data||[],payroll:[...older,...hourly,...fixed],productionCosts:(results[13].data||[]).map(row=>({...row,weekAmount:periodShare(row,weekStart,saturday)})),cartonCosts,cartonMissing,simulatedOrders,outdatedPrices:week.year===2026?results[23].data||[]:[]})
    setWorkers(results[4].data||[]);setOrders(allOrders)
  }
  useEffect(()=>{reload()},[weekStart])
  const totals=weeklyTotals(records)
  const hasPayrollEstimate=records.costs.some(row=>row.categoria==='otros'&&/EJERCICIO.*estimado de planilla/i.test(row.concepto||''))
  const resultOf=currency=>{const t=totals[currency];return t.export+t.local+t.manualIncome-t.product-t.freight-t.costs-t.credits}
  const saveRate=async()=>{const value=Number(String(rateForm.usd_crc).replace(',','.'));if(!Number.isFinite(value)||value<=0||!rateForm.fuente.trim()){setError('Ingrese una tasa positiva y su origen.');return}setSaving(true);const {error:failure}=await supabase.from('tasas_corte_semanal').upsert({semana_inicio:weekStart,usd_crc:value,fuente:rateForm.fuente.trim(),simulado:rateForm.simulado,actualizado_en:new Date().toISOString()},{onConflict:'semana_inicio'});setSaving(false);if(failure){setError(failure.message);return}setError('');setEditingRate(false);reload()}
  const outstanding=(rows,currency)=>rows.filter(row=>row.moneda===currency&&row.etapa!=='Pedido previsto'&&(row.origen!=='venta_exportacion'||!row.fecha_salida||row.fecha_salida<=saturday)).reduce((sum,row)=>sum+Math.max(0,Number(row.monto)-Number(row.aplicado)),0)
  const open=(row=null)=>{
    setError('');setEditing(row?.id||'new')
    setForm(row?Object.fromEntries(Object.keys(blank()).map(k=>[k,row[k]??''])):{...blank(),fecha:weekStart})
  }
  const change=(key,val)=>setForm(f=>{
    const updated={...f,[key]:val}
    if((key==='cantidad'||key==='tarifa')&&updated.cantidad!==''&&updated.tarifa!=='')updated.monto=String(Math.round(Number(updated.cantidad)*Number(updated.tarifa)*100)/100)
    if(key==='trabajador_id'&&!f.concepto)updated.concepto=`Planilla · ${workers.find(w=>w.id===val)?.nombre||''}`
    if(key==='categoria'&&val!=='planilla'){updated.trabajador_id=''}
    return updated
  })
  const save=async()=>{
    const amount=Number(form.monto)
    if(!form.fecha||form.fecha<weekStart||form.fecha>saturday){setError('Seleccione una fecha dentro de la semana mostrada.');return}
    if(!form.concepto.trim()||!Number.isFinite(amount)||amount<=0||Math.round(amount*100)!==amount*100){setError('Complete concepto y monto positivo con hasta dos decimales.');return}
    if(form.categoria==='planilla'&&!form.trabajador_id){setError('Seleccione el trabajador de la planilla.');return}
    if((form.cantidad!==''||form.tarifa!==''||form.unidad!=='')&&(!form.unidad.trim()||form.cantidad===''||form.tarifa===''||!Number.isFinite(Number(form.cantidad))||Number(form.cantidad)<=0||!Number.isFinite(Number(form.tarifa))||Number(form.tarifa)<0)){setError('Para calcular por unidad complete unidad, cantidad y tarifa.');return}
    const payload={fecha:form.fecha,categoria:form.categoria,concepto:form.concepto.trim(),moneda:form.moneda,monto:amount,trabajador_id:form.categoria==='planilla'?form.trabajador_id:null,orden_venta_id:form.orden_venta_id||null,unidad:form.unidad.trim()||null,cantidad:value(form.cantidad),tarifa:value(form.tarifa),referencia:form.referencia.trim()||null,observaciones:form.observaciones.trim()||null}
    setSaving(true);setError('')
    const result=editing==='new'?await supabase.from('costos_operativos').insert(payload):await supabase.from('costos_operativos').update(payload).eq('id',editing).select('id').single()
    setSaving(false)
    if(result.error){setError(`No se pudo guardar: ${result.error.message}`);return}
    setEditing(null);reload()
  }
  const voidCost=async(row)=>{
    if(!window.confirm(`¿Anular el costo «${row.concepto}» de ${money(row.monto,row.moneda)}? Quedará conservado para auditoría.`))return
    const {error:failure}=await supabase.from('costos_operativos').update({anulado_en:new Date().toISOString()}).eq('id',row.id).select('id').single()
    if(failure){setError(`No se pudo anular: ${failure.message}`);return}
    reload()
  }
  return <><div className="modulebar"><div><p>Registre costos de la semana y vea ingresos y compras finalizados. El resultado es parcial hasta completar planilla, inventario y demás gastos.</p></div><button className="primary" onClick={()=>open()}><Plus size={18}/>Registrar costo</button></div>
    <div className="weekly-nav"><button onClick={()=>setWeekStart(addDays(weekStart,-7))}>← Semana anterior</button><label>Semana {week.week} · {week.year}<input type="date" value={weekStart} onChange={e=>e.target.value&&setWeekStart(sundayOf(e.target.value))}/></label><span>Del {weekStart} al {saturday}</span><button onClick={()=>setWeekStart(next)}>Semana siguiente →</button></div>
    {error&&!editing&&<div className="formerror" role="alert">{error}</div>}
    {loading?<div className="empty">Cargando el corte semanal…</div>:<>{records.sales.some(x=>records.simulatedOrders.includes(x.id))&&<div className="bank-note"><b>EJERCICIO/SIMULADO:</b> esta semana incluye pedidos cerrados con producción y costos de prueba. Revise las boletas, precios, inventario y cobros antes de usar este resultado como cifra real.</div>}<div className="bank-note">Resultado operativo <b>parcial</b>: se asignan pedidos finalizados por fecha de salida y boletas por fecha laborada, aunque se finalicen después; las compras en pie se reconocen al procesar la primera boleta o, si no hubo proceso, al finalizar el lote. Las compras puestas en camión, en campo, los fletes y las planillas de compra se asignan a la fecha de su documento. No vuelva a registrar fletes, planilla ni consumos capturados en Control de costos como un gasto manual adicional. Los movimientos bancarios no se vuelven a sumar. Las notas de crédito descuentan en la semana de emisión. Los importes en USD y CRC permanecen separados.</div>{records.openStanding.length>0&&<div className="bank-note"><b>Compras en pie abiertas:</b> {money(records.openStanding.reduce((sum,x)=>sum+Number(x.precio_en_pie||0),0),'CRC')} pactados en {records.openStanding.length} lote(s). Se muestran como compromiso pendiente porque aún no tienen boletas finalizadas. Al procesar la primera boleta, el precio pactado se carga una sola vez al resultado.</div>}
      {records.startedStanding.length>0&&<div className="bank-note"><b>En pie con producción:</b> {money(records.startedStanding.reduce((sum,x)=>sum+Number(x.precio_en_pie||0),0),"CRC")} de precio pactado ya se descuentan esta semana porque tienen boletas finalizadas. Confirme el precio final al cerrar cada lote.</div>}
      {records.outdatedPrices.length>0&&<div className="formerror" role="alert"><b>Precio de yuca estadounidense pendiente:</b> {records.outdatedPrices.length} compras simuladas aún usan ₡7.000/quintal; el precio indicado es ₡8.500. Su cuenta por pagar y este margen están subestimados hasta que administración edite esas compras y se recalcule la boleta.</div>}
      <div className="workers-panel"><h3>Resultado consolidado provisional</h3>{rate?<><p>USD convertido a ₡{Number(rate.usd_crc).toLocaleString('es-CR',{minimumFractionDigits:2})} por dólar · {rate.fuente} · {rate.simulado?'SIMULADO':'Confirmado'}. Esta tasa queda guardada para esta semana y no cambia los documentos originales.</p><strong>{money(resultOf('CRC')+resultOf('USD')*Number(rate.usd_crc),'CRC')}</strong></>:<p>Falta guardar el tipo de cambio de esta semana para consolidar CRC y USD.</p>}<button type="button" onClick={()=>{setRateForm({usd_crc:String(rate?.usd_crc??440),fuente:rate?.fuente||'SIMULADO: valor de trabajo',simulado:rate?.simulado??true});setEditingRate(true)}}>Modificar tipo de cambio de esta semana</button>{editingRate&&<div className="formgrid"><label>₡ por USD<input type="number" min="0.01" step="0.01" value={rateForm.usd_crc} onChange={e=>setRateForm({...rateForm,usd_crc:e.target.value})}/></label><label>Origen de la tasa<input value={rateForm.fuente} onChange={e=>setRateForm({...rateForm,fuente:e.target.value})}/></label><label className="checklabel"><input type="checkbox" checked={rateForm.simulado} onChange={e=>setRateForm({...rateForm,simulado:e.target.checked})}/>Dato simulado o provisional</label><button type="button" disabled={saving} onClick={saveRate}>Guardar tasa semanal</button><button type="button" onClick={()=>setEditingRate(false)}>Cancelar</button></div>}</div>
      <div className="weekly-grid">{['CRC','USD'].map(currency=>{const t=totals[currency],result=t.export+t.local+t.manualIncome-t.product-t.freight-t.costs-t.credits;return <article key={currency}><small>{currency==='CRC'?'Colones':'Dólares'} · {currency}</small><div><span>Pedidos de exportación finalizados</span><b>{money(t.export,currency)}</b></div><div><span>Pedidos y ventas locales</span><b>{money(t.local,currency)}</b></div><div><span>Ventas y cobros manuales</span><b>{money(t.manualIncome,currency)}</b></div><div><span>Notas de crédito (pérdida)</span><b>-{money(t.credits,currency)}</b></div><div><span>Compra de producto y camiones</span><b>-{money(t.product,currency)}</b></div><div><span>Fletes de compra</span><b>-{money(t.freight,currency)}</b></div><div><span>Planilla, producción y otros gastos</span><b>-{money(t.costs,currency)}</b></div><div className="weekly-result"><span>Resultado parcial</span><strong>{money(result,currency)}</strong></div></article>})}</div>
      <div className="workers-panel"><h3>Cuentas pendientes que continúan</h3><p>Saldos actuales de documentos de esta semana o anteriores. Los abonos y las correcciones se reflejan al volver a abrir el corte. No se suman otra vez al resultado operativo.</p>{['CRC','USD'].map(currency=><article key={currency}><div><b>{currency==='CRC'?'Colones':'Dólares'}</b><span>Hasta el {saturday}</span></div><strong>Por cobrar {money(outstanding(balances.receivables,currency),currency)} · Por pagar {money(outstanding(balances.payables,currency),currency)}</strong></article>)}</div>
      <div className="workers-panel"><h3>Planilla de planta</h3><article><div><b>{records.payroll.length} colaborador(es)</b><span>{hasPayrollEstimate?'La estimación de planilla se incluye una vez en el corte.':'Costo bruto incluido en el resultado semanal.'} Neto calculado: {money(records.payroll.reduce((sum,row)=>sum+Number(row.neto),0),'CRC')}</span></div><strong>{money(records.payroll.reduce((sum,row)=>sum+Number(row.bruto),0),'CRC')}</strong></article></div>
      <div className="workers-panel"><h3>Costos de producción y servicios</h3>{['CRC','USD'].map(currency=><article key={currency}><div><b>{currency}</b><span>{records.productionCosts.filter(x=>x.moneda===currency).length} movimiento(s) distribuidos según su período de consumo</span></div><strong>{money(records.productionCosts.filter(x=>x.moneda===currency).reduce((sum,x)=>sum+x.weekAmount,0),currency)}</strong></article>)}</div>
      <div className="workers-panel"><h3>Cartón utilizado en pedidos finalizados</h3><p>Se incluye en el resultado cuando la marca tiene un único precio registrado y existen suficientes cartones con costo. Si hay varios precios, asigne el lote antes de considerar el margen definitivo.</p>{records.cartonCosts.map((x,i)=><article key={`${x.codigo}-${i}`}><div><b>{x.codigo} · {x.cantidad} cartones{x.simulado?' · SIMULADO':''}</b></div><strong>{money(x.monto,x.moneda)}</strong></article>)}{records.cartonMissing.map((x,i)=><article key={`missing-${i}`}><div><b>{x.codigo} · {x.cantidad} cartones</b><span>{x.reason}. Costo excluido del resultado.</span></div><button type="button" onClick={()=>go('Inventario de cartones')}>Revisar costo</button></article>)}</div>
      <div className="workers-panel"><h3>Gastos por categoría</h3>{Object.entries(labels).map(([category,name])=>{const parts=records.costs.filter(x=>x.categoria===category);return <article key={category}><div><b>{name}</b><span>{parts.length} registro(s)</span></div><strong>{['CRC','USD'].filter(currency=>parts.some(x=>x.moneda===currency)).map(currency=>`${money(parts.filter(x=>x.moneda===currency).reduce((sum,x)=>sum+Number(x.monto),0),currency)}`).join(' · ')||'Sin registrar'}</strong></article>})}</div>
      {records.costs.some(x=>x.orden_venta_id)&&<div className="workers-panel"><h3>Gastos asociados a pedidos</h3>{orders.filter(order=>records.costs.some(x=>x.orden_venta_id===order.id)).map(order=>{const parts=records.costs.filter(x=>x.orden_venta_id===order.id);return <article key={order.id}><div><b>{order.codigo} · {order.contenedor||'Sin contenedor'}</b><span>{parts.length} gasto(s) asociados</span></div><strong>{['CRC','USD'].filter(currency=>parts.some(x=>x.moneda===currency)).map(currency=>money(parts.filter(x=>x.moneda===currency).reduce((sum,x)=>sum+Number(x.monto),0),currency)).join(' · ')}</strong></article>})}</div>}
      <div className="workers-panel"><h3>Otros costos manuales de la semana</h3>{records.costs.map(row=><article key={row.id}><div><b>{row.fecha} · {labels[row.categoria]} · {row.concepto}</b><span>{row.trabajador_id?`${workers.find(w=>w.id===row.trabajador_id)?.nombre||'Trabajador'} · `:''}{row.orden_venta_id?`${orders.find(o=>o.id===row.orden_venta_id)?.codigo||'Pedido'} · `:''}{row.cantidad?`${row.cantidad} ${row.unidad} × ${money(row.tarifa,row.moneda)} · `:''}{row.referencia||'Sin referencia'}</span></div><strong>{money(row.monto,row.moneda)}</strong><button type="button" onClick={()=>open(row)}>Editar</button><button type="button" onClick={()=>voidCost(row)}>Anular</button></article>)}{!records.costs.length&&<p>No hay otros costos manuales en esta semana.</p>}</div>
      <div className="weekly-sources"><details><summary>Documentos que alimentan el corte</summary><p>{records.sales.length} pedidos finalizados · {records.locals.length} ventas locales · {records.purchases.length} boletas finalizadas · {records.fixedPurchases.length} compras de pago pactado · {records.freights.length} fletes · {records.purchasePayroll.length} planillas de compra.</p>{records.sales.map(x=><p key={x.id}>{x.mercado==='Costa Rica'?'Venta local':'Exportación'} {x.codigo} · {money(x.monto_cxc,x.moneda||'USD')}</p>)}{records.locals.map(x=><p key={x.id}>Venta local {x.codigo} · {money((x.ventas_segundas||[]).reduce((sum,l)=>sum+Number(l.subtotal),0),x.moneda)}</p>)}{records.purchases.filter(x=>Number(x.monto_cxp)>0).map(x=><p key={x.id}>Compra {x.codigo} · {money(x.monto_cxp,'CRC')}</p>)}{records.fixedPurchases.map(x=><p key={x.origen_id}>{x.etapa} · {x.codigo} · {money(x.monto,'CRC')}</p>)}{records.freights.map(x=><p key={x.origen_id}>Flete {x.codigo} · {x.contraparte} · {money(x.monto,'CRC')}</p>)}{records.purchasePayroll.map(x=><p key={x.origen_id}>Planilla de compra {x.codigo} · {money(x.monto,'CRC')}</p>)}</details></div>
    </>}
    {editing&&<div className="modalwrap"><div className="modal plant-form weekly-modal"><div className="modalhead"><div><span>CORTE SEMANAL</span><h2>{editing==='new'?'Registrar costo':'Editar costo'}</h2></div><button onClick={()=>setEditing(null)} aria-label="Cerrar"><X/></button></div><div className="formgrid"><label>Fecha de gasto<input type="date" value={form.fecha} min={weekStart} max={saturday} onChange={e=>change('fecha',e.target.value)}/></label><label>Categoría<select value={form.categoria} onChange={e=>change('categoria',e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{form.categoria==='planilla'&&<label className="wide">Trabajador<select value={form.trabajador_id} onChange={e=>change('trabajador_id',e.target.value)}><option value="">Seleccione un trabajador</option>{workers.map(w=><option key={w.id} value={w.id}>{w.nombre}</option>)}</select></label>}<label className="wide">Concepto<input value={form.concepto} onChange={e=>change('concepto',e.target.value)} placeholder="Ejemplo: planilla de empaque, electricidad, gas…"/></label><label>Moneda<select value={form.moneda} onChange={e=>change('moneda',e.target.value)}><option value="CRC">Colones</option><option value="USD">Dólares</option></select></label><label>Monto<input type="number" min="0.01" step="0.01" inputMode="decimal" value={form.monto} onChange={e=>change('monto',e.target.value)}/></label><label>Unidad (opcional)<input value={form.unidad} onChange={e=>change('unidad',e.target.value)} placeholder="días, horas, cajas, kg…"/></label><label>Cantidad<input type="number" min="0.001" step="0.001" inputMode="decimal" value={form.cantidad} onChange={e=>change('cantidad',e.target.value)}/></label><label>Tarifa por unidad<input type="number" min="0" step="0.0001" inputMode="decimal" value={form.tarifa} onChange={e=>change('tarifa',e.target.value)}/></label><label>Pedido o contenedor (opcional)<select value={form.orden_venta_id} onChange={e=>change('orden_venta_id',e.target.value)}><option value="">Gasto general de la semana</option>{orders.map(o=><option key={o.id} value={o.id}>{o.codigo} · {o.contenedor||'Contenedor pendiente'}</option>)}</select></label><label className="wide">Referencia o factura<input value={form.referencia} onChange={e=>change('referencia',e.target.value)}/></label><label className="wide">Observaciones<input value={form.observaciones} onChange={e=>change('observaciones',e.target.value)}/></label></div><p className="plant-help">Para material consumido registre aquí su costo; la cantidad física se registra por separado en Inventario de insumos. Registrar un pago bancario no duplica este costo.</p>{error&&<div className="formerror" role="alert">{error}</div>}<div className="modalactions"><button onClick={()=>setEditing(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar costo'}</button></div></div></div>}
  </>
}
