import React,{useEffect,useState} from 'react'
import {Plus,X} from 'lucide-react'
import {supabase} from './supabase'

const empty=()=>({nombre:'',genero:'Hombres',tipo_documento:'Cédula',identificacion:'',fecha_nacimiento:'',direccion:'',residencia:'',telefono:'',contacto_emergencia:'',telefono_emergencia:'',activo:true})
export default function Workers(){
  const [workers,setWorkers]=useState([]);const [form,setForm]=useState(empty);const [editing,setEditing]=useState(null);const [error,setError]=useState('');const [saving,setSaving]=useState(false)
  const reload=()=>supabase.from('trabajadores').select('*').order('nombre').then(({data,error:loadError})=>{if(loadError)setError('No se pudieron cargar los colaboradores.');else setWorkers(data||[])})
  useEffect(reload,[])
  const open=worker=>{setEditing(worker?.id||'new');setForm(worker?Object.fromEntries(Object.entries(empty()).map(([key,value])=>[key,worker[key]??value])):empty());setError('')}
  const save=async()=>{
    if(!form.nombre.trim()||!form.genero){setError('Escriba nombre y seleccione hombres o mujeres.');return}
    setSaving(true);setError('')
    const payload={...form,nombre:form.nombre.trim()};for(const key of Object.keys(payload))if(payload[key]==='')payload[key]=null
    const {error:saveError}=editing==='new'?await supabase.from('trabajadores').insert(payload):await supabase.from('trabajadores').update(payload).eq('id',editing).select('id').single()
    setSaving(false);if(saveError){setError(`No se pudo guardar el colaborador: ${saveError.message}`);return}setEditing(null);reload()
  }
  return <><div className="modulebar"><div><p>Ficha de colaboradores y selección por hombres y mujeres para las labores de planta.</p></div><button className="primary" onClick={()=>open(null)}><Plus size={18}/>Nuevo colaborador</button></div>{['Hombres','Mujeres'].map(g=><section className="workers-panel" key={g}><h3>{g}</h3>{workers.filter(w=>w.genero===g).length?workers.filter(w=>w.genero===g).map(w=><article key={w.id}><div><b>{w.nombre}</b><span>{w.residencia||'Sin residencia registrada'} · {w.activo?'Activo':'Inactivo'}</span></div><button onClick={()=>open(w)}>Editar ficha</button></article>):<p>Sin colaboradores registrados.</p>}</section>)}
  {editing&&<div className="modalwrap"><div className="modal workers-modal"><div className="modalhead"><div><span>{editing==='new'?'NUEVO REGISTRO':'EDITAR REGISTRO'}</span><h2>Ficha del colaborador</h2></div><button onClick={()=>setEditing(null)} aria-label="Cerrar"><X/></button></div><div className="formsection"><h3>Identificación</h3><div className="formgrid"><label>Nombre completo *<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Lista<select value={form.genero} onChange={e=>setForm({...form,genero:e.target.value})}><option>Hombres</option><option>Mujeres</option></select></label><label>Tipo de documento<select value={form.tipo_documento||''} onChange={e=>setForm({...form,tipo_documento:e.target.value})}><option value="">Seleccione</option><option>Cédula</option><option>Pasaporte</option><option>Permiso</option></select></label><label>Número de documento<input value={form.identificacion} onChange={e=>setForm({...form,identificacion:e.target.value})}/></label><label>Fecha de nacimiento<input type="date" value={form.fecha_nacimiento} onChange={e=>setForm({...form,fecha_nacimiento:e.target.value})}/></label><label>Teléfono<input type="tel" value={form.telefono} onChange={e=>setForm({...form,telefono:e.target.value})}/></label><label className="wide">Dirección<input value={form.direccion} onChange={e=>setForm({...form,direccion:e.target.value})}/></label><label>Residencia<input value={form.residencia} onChange={e=>setForm({...form,residencia:e.target.value})}/></label></div></div><div className="formsection"><h3>Emergencia y estado</h3><div className="formgrid"><label>Contacto de emergencia<input value={form.contacto_emergencia} onChange={e=>setForm({...form,contacto_emergencia:e.target.value})}/></label><label>Teléfono de emergencia<input type="tel" value={form.telefono_emergencia} onChange={e=>setForm({...form,telefono_emergencia:e.target.value})}/></label><label className="checklabel"><input type="checkbox" checked={form.activo} onChange={e=>setForm({...form,activo:e.target.checked})}/> Colaborador activo</label></div></div>{error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={()=>setEditing(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar colaborador'}</button></div></div></div>}{!editing&&error&&<div className="formerror">{error}</div>}</>
}
