import React,{useEffect,useState} from 'react'
import {Plus,X} from 'lucide-react'
import {supabase} from './supabase'

const empty=()=>({nombre:'',genero:'Hombres',tipo_documento:'',identificacion:'',vencimiento_documento:'',nacionalidad:'',fecha_nacimiento:'',direccion:'',residencia:'',telefono:'',telefono_alternativo:'',correo:'',contacto_emergencia:'',parentesco_emergencia:'',telefono_emergencia:'',puesto:'',categoria:'Operativo',encargado_planta:false,modalidad_pago:'Por horas',fecha_ingreso:'',observaciones:'',activo:true})
const field=(form,setForm,key,label,type='text',wide=false)=><label className={wide?'wide':''} key={key}>{label}<input type={type} value={form[key]||''} onChange={e=>setForm(current=>({...current,[key]:e.target.value}))}/></label>
export default function Workers(){
  const [category,setCategory]=useState('Operativo')
  const [workers,setWorkers]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[batch,setBatch]=useState(false),[names,setNames]=useState(''),[batchGender,setBatchGender]=useState('Hombres')
  const reload=async()=>{setLoading(true);const {data,error:loadError}=await supabase.from('trabajadores').select('*').order('nombre');setLoading(false);if(loadError)setError(`No se pudieron cargar los colaboradores: ${loadError.message}`);else setWorkers(data||[])}
  useEffect(()=>{reload()},[])
  const open=worker=>{setEditing(worker?.id||'new');const values=worker?Object.fromEntries(Object.entries(empty()).map(([key,value])=>[key,worker[key]??value])):empty();setForm(values);setError('')}
  const save=async()=>{
    if(!form.nombre.trim()||!form.genero){setError('Escriba el nombre completo y seleccione la lista.');return}
    setSaving(true);setError('')
    const payload={...form,nombre:form.nombre.trim()}
    for(const key of Object.keys(payload))if(typeof payload[key]==='string'&&payload[key].trim()==='')payload[key]=null
    const {error:saveError}=editing==='new'?await supabase.from('trabajadores').insert(payload):await supabase.from('trabajadores').update(payload).eq('id',editing).select('id').single()
    setSaving(false);if(saveError){setError(`No se pudo guardar el colaborador: ${saveError.message}`);return}setEditing(null);reload()
  }
  const saveBatch=async()=>{
    const entries=[...new Map(names.split(/\r?\n/).map(name=>name.trim().replace(/\s+/g,' ')).filter(Boolean).map(name=>[name.toLocaleLowerCase('es'),name])).values()]
    if(!entries.length){setError('Escriba un nombre por línea.');return}
    const existing=new Set(workers.map(w=>w.nombre.trim().toLocaleLowerCase('es')))
    const fresh=entries.filter(name=>!existing.has(name.toLocaleLowerCase('es')))
    if(!fresh.length){setError('Todos esos nombres ya están registrados.');return}
    setSaving(true);setError('')
    const {error:saveError}=await supabase.from('trabajadores').insert(fresh.map(nombre=>({nombre,genero:batchGender,categoria:category==='Administrativo'?'Administrativo':'Operativo',activo:true})))
    setSaving(false)
    if(saveError){setError(`No se pudo registrar la lista: ${saveError.message}`);return}
    setBatch(false);setNames('');reload()
  }
  return <><div className="modulebar"><div><p>Expedientes de colaboradores para administración y labores de planta.</p></div><div className="workers-actions"><button onClick={()=>{setBatch(true);setError('')}}>Agregar varios</button><button className="primary" onClick={()=>open(null)}><Plus size={18}/>Nuevo colaborador</button></div></div>
  <div className="workers-search"><label>Grupo <select value={category} onChange={e=>setCategory(e.target.value)}><option value="Operativo">Colaboradores normales</option><option value="Administrativo">Colaboradores administrativos</option><option value="Encargados">Encargados de planta</option><option value="Inactivos">Personal inactivo</option></select></label><input aria-label="Buscar colaborador" placeholder="Buscar por nombre o documento…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  {loading&&<p>Cargando colaboradores…</p>}{!loading&&['Hombres','Mujeres'].map(g=>{const list=workers.filter(w=>w.genero===g&&(category==='Encargados'?w.activo&&w.encargado_planta:category==='Inactivos'?!w.activo:w.activo&&(w.categoria||'Operativo')===category)&&`${w.nombre} ${w.identificacion||''}`.toLowerCase().includes(search.toLowerCase()));return <section className="workers-panel" key={g}><h3>{g} ({list.length})</h3>{list.length?list.map(w=><article key={w.id}><div><b>{w.nombre}</b><span>{w.puesto||'Puesto pendiente'} · {w.residencia||'Sin residencia'} · {w.activo?'Activo':'Inactivo'}</span></div><button onClick={()=>open(w)}>Ver / editar ficha</button></article>):<p>Sin colaboradores en esta lista.</p>}</section>})}
  {batch&&<div className="modalwrap"><div className="modal workers-modal"><div className="modalhead"><div><span>REGISTRO EN GRUPO</span><h2>Agregar colaboradores</h2></div><button onClick={()=>setBatch(false)} aria-label="Cerrar"><X/></button></div><div className="formsection"><p>Escriba un nombre completo por línea. Luego puede abrir la ficha de cada persona y completar sus datos.</p><div className="formgrid"><label>Lista<select value={batchGender} onChange={e=>setBatchGender(e.target.value)}><option>Hombres</option><option>Mujeres</option></select></label><label className="wide">Nombres completos<textarea rows="10" value={names} onChange={e=>setNames(e.target.value)} placeholder={'Nombre Apellido\nNombre Apellido'}/></label></div></div>{error&&<div className="formerror">{error}</div>}<div className="modalactions"><button onClick={()=>setBatch(false)}>Cancelar</button><button className="primary" onClick={saveBatch} disabled={saving}>{saving?'Guardando…':'Guardar lista'}</button></div></div></div>}
  {editing&&<div className="modalwrap"><div className="modal workers-modal"><div className="modalhead"><div><span>{editing==='new'?'NUEVO REGISTRO':'EXPEDIENTE'}</span><h2>Ficha del colaborador</h2></div><button onClick={()=>setEditing(null)} aria-label="Cerrar"><X/></button></div>
    <div className="formsection"><h3>Identificación y documentos</h3><div className="formgrid">{field(form,setForm,'nombre','Nombre completo *') }<label>Lista<select value={form.genero} onChange={e=>setForm({...form,genero:e.target.value})}><option>Hombres</option><option>Mujeres</option></select></label>{field(form,setForm,'nacionalidad','Nacionalidad')}<label>Documento principal<select value={form.tipo_documento||''} onChange={e=>setForm({...form,tipo_documento:e.target.value})}><option value="">Pendiente de confirmar</option><option>Cédula</option><option>Pasaporte</option><option>Permiso de trabajo</option></select></label>{field(form,setForm,'identificacion','Número del documento')}{field(form,setForm,'vencimiento_documento','Vencimiento del documento (si aplica)','date')}{field(form,setForm,'fecha_nacimiento','Fecha de nacimiento','date')}</div></div>
    <div className="formsection"><h3>Contacto y domicilio</h3><div className="formgrid">{field(form,setForm,'telefono','Teléfono personal','tel')}{field(form,setForm,'telefono_alternativo','Otro teléfono','tel')}{field(form,setForm,'correo','Correo electrónico','email')}{field(form,setForm,'residencia','Residencia / localidad')}{field(form,setForm,'direccion','Dirección completa','text',true)}</div></div>
    <div className="formsection"><h3>En caso de emergencia</h3><div className="formgrid">{field(form,setForm,'contacto_emergencia','Nombre del contacto')}{field(form,setForm,'parentesco_emergencia','Parentesco o relación')}{field(form,setForm,'telefono_emergencia','Teléfono de emergencia','tel')}</div></div>
    <div className="formsection"><h3>Datos laborales</h3><div className="formgrid"><label>Grupo de personal<select value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}><option value="Operativo">Colaboradores normales</option><option value="Administrativo">Colaboradores administrativos</option></select></label><label>Forma de pago<select value={form.modalidad_pago} onChange={e=>setForm({...form,modalidad_pago:e.target.value})}><option>Por horas</option><option>Salario fijo</option></select></label>{field(form,setForm,'puesto','Puesto o función')}<label className="checklabel"><input type="checkbox" checked={form.encargado_planta} onChange={e=>setForm({...form,encargado_planta:e.target.checked})}/> Encargado de planta (aparece en boletas)</label>{field(form,setForm,'fecha_ingreso','Fecha de ingreso','date')}<label className="wide">Observaciones<textarea rows="3" value={form.observaciones||''} onChange={e=>setForm({...form,observaciones:e.target.value})}/></label><label className="checklabel"><input type="checkbox" checked={form.activo} onChange={e=>setForm({...form,activo:e.target.checked})}/> Colaborador activo</label></div></div>
    {error&&<div className="formerror" role="alert">{error}</div>}<div className="modalactions"><button onClick={()=>setEditing(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar ficha'}</button></div></div></div>}{!editing&&error&&<div className="formerror" role="alert">{error}</div>}</>
}
