import React,{useEffect,useState} from 'react'
import {supabase} from './supabase'
import {costaRicaToday} from './weekly-model'

const fmt=n=>Number(n||0).toLocaleString('es-CR',{maximumFractionDigits:2})
const fresh=q=>({calidad:q==='Europa'?'Exportable Europa':'Exportable estadounidense',cajas:'',peso_kg:'18',kg:'',linea_id:'',posicion:''})
const weight=x=>Number(x.cajas)>0?Number(x.cajas)*Number(x.peso_kg):Number(x.kg)
const grades=['Exportable Europa','Exportable estadounidense','Segunda gruesa','Segunda menuda','Desperdicio']
export default function YucaReprocess({lot,available,onClose,onSaved}){
 const [fecha,setFecha]=useState(costaRicaToday),[cajas,setCajas]=useState(String(available)),[outputs,setOutputs]=useState(()=>[fresh(lot.calidad)]),[gasto,setGasto]=useState('0'),[notas,setNotas]=useState(''),[lines,setLines]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[request]=useState(()=>crypto.randomUUID())
 useEffect(()=>{let active=true;const load=async()=>{try{const [o,l,r]=await Promise.all([supabase.from('ordenes_venta').select('id,codigo,mercado,fecha_salida,numero_cliente,clientes(nombre)').is('finalizada_en',null).is('anulada_en',null).neq('estado','Anulada').limit(1000),supabase.from('ordenes_venta_lineas').select('id,orden_venta_id,producto,presentacion_kg,cantidad_cajas,carton_marca').eq('producto','Yuca').limit(2000),supabase.from('boleta_rendimientos').select('orden_venta_linea_id,cajas').not('orden_venta_linea_id','is',null).limit(5000)]);if(o.error||l.error||r.error)throw o.error||l.error||r.error;if(o.data.length>=1000||l.data.length>=2000||r.data.length>=5000)throw new Error('Hay demasiados registros para calcular pedidos completos.');const used={};for(const x of r.data)used[x.orden_venta_linea_id]=(used[x.orden_venta_linea_id]||0)+Number(x.cajas);if(active)setLines(l.data.map(x=>({...x,order:o.data.find(y=>y.id===x.orden_venta_id),pending:Number(x.cantidad_cajas)-Number(used[x.id]||0)})).filter(x=>x.order&&x.pending>0))}catch(e){if(active)setError(e.message)}finally{if(active)setLoading(false)}};load();return()=>{active=false}},[])
 const input=Number(cajas)*Number(lot.kg_por_caja),total=outputs.reduce((n,x)=>n+(Number.isFinite(weight(x))?weight(x):0),0),diff=input-total
 const change=(i,key,value)=>setOutputs(xs=>xs.map((x,j)=>{if(i!==j)return x;const next={...x,[key]:value};if(key==='calidad'){next.linea_id='';next.posicion='';if(value==='Desperdicio'){next.cajas='';next.peso_kg=''}}if(key==='linea_id'){const line=lines.find(l=>l.id===value);if(line)next.peso_kg=String(line.presentacion_kg)}return next}))
 const save=async e=>{e.preventDefault();setError('');if(!fecha||!Number.isInteger(Number(cajas))||Number(cajas)<1||Number(cajas)>available){setError('Revise la fecha y las cajas retiradas del saldo.');return}if(outputs.some(x=>!Number.isFinite(weight(x))||weight(x)<=0||(Number(x.cajas)>0&&!Number.isInteger(Number(x.cajas)))||(x.calidad.startsWith('Exportable')&&Number(x.cajas)<=0))){setError('Complete cantidades positivas en todos los resultados. La primera se registra en cajas.');return}if(Math.abs(diff)>0.01){setError('Los resultados deben sumar exactamente los kilos de entrada.');return}if(!Number.isFinite(Number(gasto))||Number(gasto)<0){setError('Revise el gasto adicional.');return}setSaving(true);try{const {error:e}=await supabase.rpc('reprocesar_saldo_yuca',{p_saldo_id:lot.id,p_fecha:fecha,p_cajas:Number(cajas),p_partidas:outputs.map(x=>({...x,cajas:Number(x.cajas)||0,peso_kg:Number(x.peso_kg)||null,kg:Number(x.kg)||null,linea_id:x.linea_id||null,posicion:x.posicion?Number(x.posicion):null})),p_gasto_crc:Number(gasto),p_observaciones:notas.trim()||null,p_solicitud:request});if(e)throw e;onSaved()}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="modalwrap"><form className="modal plant-form" onSubmit={save}><div className="modalhead"><h2>Reprocesar yuca {lot.calidad}</h2><button type="button" disabled={saving} onClick={onClose}>Cerrar</button></div><p><b>{lot.productor} · {lot.boleta_codigo}</b><br/>Código original {lot.codigo_trazabilidad} · {fmt(available)} cajas disponibles de {fmt(lot.kg_por_caja)} kg.</p><div className="formgrid"><label>Fecha del reproceso<input type="date" required value={fecha} onChange={e=>setFecha(e.target.value)}/></label><label>Cajas que retiro del saldo<input type="number" min="1" max={available} step="1" required value={cajas} onChange={e=>setCajas(e.target.value)}/></label></div><p><b>Entrada: {fmt(input)} kg</b> · quedan {fmt(available-Number(cajas||0))} cajas en la partida original.</p>
 <h3>Lo que salió de la selección</h3>{outputs.map((x,i)=>{const first=x.calidad.startsWith('Exportable'),loss=x.calidad==='Desperdicio',market=x.calidad==='Exportable Europa'?'Europa':'Estados Unidos';const candidates=lines.filter(l=>l.order.mercado===market&&l.order.fecha_salida>=fecha);return <section key={i} style={{border:'1px solid #cad8e8',padding:8,margin:'6px 0',borderRadius:6}}><div className="formgrid"><label>Calidad<select value={x.calidad} onChange={e=>change(i,'calidad',e.target.value)}>{grades.map(g=><option key={g}>{g}</option>)}</select></label>{!loss&&<label>Cajas {first?'':'(opcional)'}<input type="number" min={first?'1':'0'} step="1" value={x.cajas} onChange={e=>change(i,'cajas',e.target.value)}/></label>}{Number(x.cajas)>0?<label>Kilos por caja<input type="number" min="0.01" step="0.01" value={x.peso_kg} onChange={e=>change(i,'peso_kg',e.target.value)} readOnly={!!x.linea_id}/></label>:!first&&<label>{loss?'Pérdida en kilos':'Kilos de segunda'}<input type="number" min="0.01" step="0.01" value={x.kg} onChange={e=>change(i,'kg',e.target.value)}/></label>}{first&&<><label>Pedido destino<select value={x.linea_id} disabled={loading} onChange={e=>change(i,'linea_id',e.target.value)}><option value="">Dejar primera en planta</option>{candidates.map(l=><option key={l.id} value={l.id}>{l.order.clientes?.nombre||'Cliente'}{l.order.numero_cliente?' '+l.order.numero_cliente:''} · {l.order.codigo} · {l.order.fecha_salida} · {l.presentacion_kg} kg · faltan {l.pending} cajas</option>)}</select></label>{x.linea_id&&<label>Paleta inicial (opcional)<input type="number" min="1" max="22" step="1" value={x.posicion} onChange={e=>change(i,'posicion',e.target.value)}/></label>}</>}</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:5}}><b>{fmt(weight(x))} kg{!first&&!loss?' · disponible para venta local':''}</b>{outputs.length>1&&<button type="button" disabled={saving} onClick={()=>setOutputs(xs=>xs.filter((_,j)=>j!==i))}>Quitar</button>}</div></section>})}
 <button type="button" disabled={saving||outputs.length>=30} onClick={()=>setOutputs(xs=>[...xs,{...fresh(lot.calidad),calidad:'Segunda gruesa',cajas:'',peso_kg:'30'}])}>+ Agregar resultado</button><p><b>Clasificado: {fmt(total)} kg · Diferencia: {fmt(diff)} kg</b></p><div className="formgrid"><label>Gasto adicional de este reproceso (₡)<input type="number" min="0" step="0.01" value={gasto} onChange={e=>setGasto(e.target.value)}/></label><label>Observaciones<input value={notas} maxLength={1000} onChange={e=>setNotas(e.target.value)}/></label></div><p className="sale-help">Conserva la compra y el código originales. El resultado asignado completa el pedido y su mapa de carga; las segundas quedan para venta local. El costo del saldo pasa al resultado y la pérdida afecta el corte. El gasto adicional se registra una sola vez.</p>{error&&<p className="formerror" role="alert">{error}</p>}<div className="modalactions"><button type="button" disabled={saving} onClick={onClose}>Cancelar</button><button className="primary" disabled={saving||loading||Math.abs(diff)>0.01}>{saving?'Guardando…':'Guardar reproceso'}</button></div></form></div>
}
