import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from './supabase'
import {costaRicaToday} from './weekly-model'

const num=n=>Number(n||0).toLocaleString('es-CR',{maximumFractionDigits:2})
const freshSale=()=>({fecha:costaRicaToday(),cajas:'',comprador:'',moneda:'CRC',precio_estimado_qq:'',referencia:'',observaciones:''})
const freshSettlement=s=>({kg_primera:String(s.kg_primera??''),kg_rechazo:String(s.kg_rechazo_devuelto??''),kg_merma:String(s.kg_merma??''),precio_final_qq:String(s.precio_final_qq??s.precio_estimado_qq??''),referencia:s.referencia||''})

export default function YucaBalance({profile}){
  const canSell=['administrador','oficina'].includes(profile?.rol)
  const [quality,setQuality]=useState(null)
  const [lots,setLots]=useState([]),[moves,setMoves]=useState([]),[sales,setSales]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(freshSale),[settling,setSettling]=useState(null),[result,setResult]=useState(null),[saving,setSaving]=useState(false),[reload,setReload]=useState(0)
  useEffect(()=>{let active=true;setLoading(true);Promise.all([
    supabase.from('saldos_yuca_eeuu').select('*').order('fecha_origen',{ascending:true}).order('id',{ascending:true}).limit(1000),
    supabase.from('salidas_saldo_yuca_eeuu').select('*').order('creado_en',{ascending:false}).limit(5000),
    canSell?supabase.from('ventas_saldo_yuca_eeuu').select('*').order('creado_en',{ascending:false}).limit(1000):Promise.resolve({data:[],error:null})
  ]).then(([a,b,c])=>{if(!active)return;setLoading(false);if(a.error||b.error||c.error){setError(`No se pudo cargar el saldo: ${(a.error||b.error||c.error).message}`);return}if(a.data.length===1000||b.data.length===5000||c.data.length===1000){setError('Hay más movimientos que el límite de consulta. No se puede calcular un saldo completo.');return}setLots(a.data);setMoves(b.data);setSales(c.data);setError('')}).catch(e=>{if(active){setLoading(false);setError(e.message)}});return()=>{active=false}},[reload,canSell])
  const used=useMemo(()=>{const byId={};for(const m of moves)byId[m.saldo_id]=(byId[m.saldo_id]||0)+Number(m.cajas);return byId},[moves])
  const qualityLots=lots.filter(l=>l.calidad===quality)
  const available=qualityLots.reduce((sum,l)=>sum+Number(l.cajas_origen)-Number(used[l.id]||0),0)
  const preview=useMemo(()=>{let left=Number(form.cajas),kg=0;const parts=[];if(!Number.isInteger(left)||left<=0)return {parts,kg:0,left:0};for(const lot of qualityLots){const take=Math.min(left,Number(lot.cajas_origen)-Number(used[lot.id]||0));if(take>0){parts.push({lot,cajas:take,kg:take*Number(lot.kg_por_caja)});kg+=take*Number(lot.kg_por_caja);left-=take}if(!left)break}return {parts,kg,left}},[form.cajas,qualityLots,used])
  const save=async()=>{setSaving(true);setError('');const {error:e}=await supabase.rpc('vender_saldo_yuca_por_calidad',{p_calidad:quality,p_fecha:form.fecha,p_cajas:Number(form.cajas),p_comprador:form.comprador,p_moneda:form.moneda,p_precio_estimado_qq:Number(form.precio_estimado_qq),p_referencia:form.referencia||null,p_observaciones:form.observaciones||null});setSaving(false);if(e){setError(e.message);return}setOpen(false);setReload(n=>n+1)}
  const settle=async()=>{setSaving(true);setError('');const {error:e}=await supabase.rpc('liquidar_venta_saldo_yuca_eeuu',{p_venta_id:settling.id,p_kg_primera:Number(result.kg_primera),p_kg_rechazo:Number(result.kg_rechazo),p_kg_merma:Number(result.kg_merma),p_precio_final_qq:Number(result.precio_final_qq),p_referencia:result.referencia||null});setSaving(false);if(e){setError(e.message);return}setSettling(null);setReload(n=>n+1)}
  const difference=settling&&result?Number(settling.kg_enviados)-Number(result.kg_primera||0)-Number(result.kg_rechazo||0)-Number(result.kg_merma||0):0
  const weeks=[...new Set(qualityLots.map(x=>x.lunes_destino))].sort().reverse()
  const qualitySales=sales.filter(s=>s.calidad===quality)
  return <><div className="modulebar"><p>Yuca sin pedido proveniente de boletas finalizadas. Separe el saldo Europa del saldo Estados Unidos; las ventas locales conservan el código de cada boleta.</p>{canSell&&quality&&<button className="primary" disabled={loading||!!error||available<=0} onClick={()=>{setForm(freshSale());setOpen(true)}}>Vender yuca del saldo {quality}</button>}</div>{error&&<p className="formerror" role="alert">{error}</p>}{!quality&&<div className="module-hub">{['Estados Unidos','Europa'].map(q=><button key={q} type="button" onClick={()=>setQuality(q)}><span>Saldo de yuca {q}</span><strong>{num(lots.filter(l=>l.calidad===q).reduce((sum,l)=>sum+Number(l.cajas_origen)-Number(used[l.id]||0),0))} cajas disponibles</strong></button>)}</div>}{quality&&<button type="button" onClick={()=>setQuality(null)}>← Ver ambas calidades</button>}{loading?<p>Cargando saldos…</p>:quality&&<><section className="panel"><h3>Inventario disponible · {quality}</h3><strong>{num(available)} cajas</strong></section>{weeks.map(week=>{const entries=qualityLots.filter(x=>x.lunes_destino===week),remaining=entries.reduce((sum,x)=>sum+Number(x.cajas_origen)-Number(used[x.id]||0),0);return <section className="panel balance-week" key={week}><h3>Lunes {week} · {num(remaining)} cajas disponibles</h3>{entries.map(x=><article className="balance-item" key={x.id}><div><b>{x.productor} · {x.boleta_codigo}</b><small>Código {x.codigo_trazabilidad} · {num(x.kg_por_caja)} kg/caja</small><small>{num(x.cajas_origen)} cajas de origen · {num(used[x.id])} salidas · <strong>{num(Number(x.cajas_origen)-Number(used[x.id]||0))} disponibles</strong></small></div></article>)}</section>})}{canSell&&<section className="panel"><h3>Ventas y liquidaciones</h3>{qualitySales.length?qualitySales.map(s=>{const parts=moves.filter(m=>m.venta_id===s.id);const diff=s.kg_primera==null?null:Number(s.kg_enviados)-Number(s.kg_primera)-Number(s.kg_rechazo_devuelto)-Number(s.kg_merma);return <article className="balance-item" key={s.id}><div><b>{s.comprador} · {s.fecha}</b><small>{num(s.cajas)} cajas · {num(s.kg_enviados)} kg enviados · {s.codigo}</small><small>{s.liquidada_en?`Liquidada · primera ${num(s.kg_primera)} kg · rechazo devuelto ${num(s.kg_rechazo_devuelto)} kg · merma ${num(s.kg_merma)} kg · ${s.moneda} ${num(Number(s.kg_primera)/46*Number(s.precio_final_qq))}`:diff==null?'Pendiente de rendimiento y cobro':`Diferencia pendiente: ${num(diff)} kg`}</small><details><summary>Boletas utilizadas</summary>{parts.map(m=>{const l=lots.find(x=>x.id===m.saldo_id);return <small key={m.id}>{l?.boleta_codigo||'Boleta'} · {l?.codigo_trazabilidad} · {num(m.cajas)} cajas × {num(l?.kg_por_caja)} kg = {num(Number(m.cajas)*Number(l?.kg_por_caja))} kg</small>})}</details></div>{!s.liquidada_en&&<button onClick={()=>{setSettling(s);setResult(freshSettlement(s))}}>Registrar rendimiento y devolución</button>}</article>}):<p>No hay ventas del saldo registradas.</p>}</section>}</>}
    {open&&<div className="modalwrap"><div className="modal plant-form"><div className="modalhead"><h2>Vender yuca del saldo {quality}</h2><button onClick={()=>setOpen(false)}>Cerrar</button></div><div className="formgrid"><label>Fecha de salida<input type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></label><label>Comprador o empacadora<input value={form.comprador} onChange={e=>setForm({...form,comprador:e.target.value})}/></label><label>Cajas enviadas<input type="number" min="1" max={available} step="1" value={form.cajas} onChange={e=>setForm({...form,cajas:e.target.value})}/></label><label>Moneda<select value={form.moneda} onChange={e=>setForm({...form,moneda:e.target.value})}><option value="CRC">Colones</option><option value="USD">Dólares</option></select></label><label>Precio estimado por quintal de primera (46 kg)<input type="number" min="0" step="0.01" value={form.precio_estimado_qq} onChange={e=>setForm({...form,precio_estimado_qq:e.target.value})}/></label><label>Referencia de envío<input value={form.referencia} onChange={e=>setForm({...form,referencia:e.target.value})}/></label><label className="wide">Observaciones<input value={form.observaciones} onChange={e=>setForm({...form,observaciones:e.target.value})}/></label></div>{error&&<p className="formerror" role="alert">{error}</p>}<h3>Partidas de {quality}, por fecha de ingreso</h3>{preview.parts.map(p=><p key={p.lot.id}>{p.lot.boleta_codigo} · {p.lot.codigo_trazabilidad}: {num(p.cajas)} cajas × {num(p.lot.kg_por_caja)} kg = {num(p.kg)} kg</p>)}<p><b>Total: {num(preview.kg)} kg ({num(preview.kg/46)} qq)</b>{preview.left>0?` · Faltan ${preview.left} cajas en inventario`:''}</p><p>El precio es una referencia. La cuenta por cobrar se crea cuando se concilien los kilos y se registre el precio final.</p><div className="modalactions"><button onClick={()=>setOpen(false)} disabled={saving}>Cancelar</button><button className="primary" onClick={save} disabled={saving||!form.fecha||!form.comprador.trim()||!Number.isInteger(Number(form.cajas))||Number(form.cajas)<1||preview.left>0||form.precio_estimado_qq===''||Number(form.precio_estimado_qq)<0}>{saving?'Guardando…':'Registrar salida y venta'}</button></div></div></div>}
    {settling&&result&&<div className="modalwrap"><div className="modal plant-form"><div className="modalhead"><h2>Rendimiento de {settling.comprador}</h2><button onClick={()=>setSettling(null)}>Cerrar</button></div><p>{num(settling.cajas)} cajas · <b>{num(settling.kg_enviados)} kg enviados</b>. Ingrese los datos que entregue la empacadora.</p><div className="formgrid"><label>Kilos de primera empacada<input type="number" min="0" step="0.01" value={result.kg_primera} onChange={e=>setResult({...result,kg_primera:e.target.value})}/></label><label>Kilos de rechazo devueltos<input type="number" min="0" step="0.01" value={result.kg_rechazo} onChange={e=>setResult({...result,kg_rechazo:e.target.value})}/></label><label>Kilos de merma justificada<input type="number" min="0" step="0.01" value={result.kg_merma} onChange={e=>setResult({...result,kg_merma:e.target.value})}/></label><label>Precio final por quintal de primera ({settling.moneda})<input type="number" min="0" step="0.01" value={result.precio_final_qq} onChange={e=>setResult({...result,precio_final_qq:e.target.value})}/></label><label className="wide">Referencia de liquidación<input value={result.referencia} onChange={e=>setResult({...result,referencia:e.target.value})}/></label></div>{error&&<p className="formerror" role="alert">{error}</p>}<p><b>Diferencia por aclarar: {num(difference)} kg</b> · Primera + rechazo + merma = {num(Number(result.kg_primera||0)+Number(result.kg_rechazo||0)+Number(result.kg_merma||0))} kg.</p><p>Importe de primera: {settling.moneda} {num(Number(result.kg_primera||0)/46*Number(result.precio_final_qq||0))}. Si la diferencia supera 0,01 kg, se guardan los datos y la venta permanece pendiente de cobro.</p><div className="modalactions"><button onClick={()=>setSettling(null)} disabled={saving}>Cancelar</button><button className="primary" onClick={settle} disabled={saving||[result.kg_primera,result.kg_rechazo,result.kg_merma,result.precio_final_qq].some(v=>v===''||!Number.isFinite(Number(v))||Number(v)<0)}>{saving?'Guardando…':Math.abs(difference)>0.01?'Guardar comparativo pendiente':'Liquidar y generar cuenta por cobrar'}</button></div></div></div>}</>
}
