-- Ciclos agrícolas: conserva las operaciones anteriores sin atribuirlas automáticamente.
create table public.ciclos_finca(
 id uuid primary key default gen_random_uuid(), lote_id uuid not null references public.lotes_finca,
 nombre text not null check(length(btrim(nombre))>0), producto text not null,
 fecha_siembra date not null, fecha_cosecha_estimada date, area_ha numeric(12,3) check(area_ha>0),
 porcentaje_propietario numeric(5,2) not null default 0 check(porcentaje_propietario between 0 and 100),
 propietario text, estado text not null default 'Abierto' check(estado in('Abierto','Cerrado')),
 observaciones text, creado_en timestamptz not null default now(), unique(lote_id,nombre)
);
create index ciclos_finca_lote_idx on public.ciclos_finca(lote_id);
alter table public.costos_finca add column ciclo_id uuid references public.ciclos_finca;
alter table public.ordenes_compra add column ciclo_finca_id uuid references public.ciclos_finca;
create index costos_finca_ciclo_idx on public.costos_finca(ciclo_id);
create index ordenes_compra_ciclo_idx on public.ordenes_compra(ciclo_finca_id);
create table public.movimientos_cosecha_finca(
 id uuid primary key default gen_random_uuid(), solicitud uuid not null unique,
 ciclo_id uuid not null references public.ciclos_finca, fecha date not null,
 tipo text not null check(tipo in('Cosecha','Venta en campo','Entrega a exportadora','Pérdida','Uso como semilla','Arrastre recibido','Arrastre enviado')),
 producto text not null check(length(btrim(producto))>0), calidad text not null check(length(btrim(calidad))>0),
 unidad text not null check(unidad in('kg','Unidades')), cantidad numeric(16,3) not null check(cantidad>0),
 cantidad_comercial numeric(16,3) check(cantidad_comercial>0), unidad_comercial text,
 precio_unitario numeric(16,2) check(precio_unitario>=0), moneda text not null default 'CRC' check(moneda in('CRC','USD')),
 tipo_cambio numeric(12,4) not null default 1 check(tipo_cambio>0),
 comprador text, orden_compra_id uuid references public.ordenes_compra,
 movimiento_origen_id uuid unique references public.movimientos_cosecha_finca,
 observaciones text, motivo_correccion text, registrado_por uuid default auth.uid(), creado_en timestamptz not null default now(),
 check(tipo<>'Venta en campo' or (cantidad_comercial is not null and precio_unitario>0 and length(btrim(comprador))>0)),
 check(tipo<>'Entrega a exportadora' or orden_compra_id is not null),
 check(moneda<>'CRC' or tipo_cambio=1)
);
create index movimientos_cosecha_ciclo_idx on public.movimientos_cosecha_finca(ciclo_id);
create index movimientos_cosecha_orden_idx on public.movimientos_cosecha_finca(orden_compra_id);
create table public.repartos_costos_finca(
 costo_id uuid not null references public.costos_finca, ciclo_id uuid not null references public.ciclos_finca,
 monto numeric(16,2) not null check(monto>0), primary key(costo_id,ciclo_id)
);
create index repartos_ciclo_idx on public.repartos_costos_finca(ciclo_id);
create table public.arrastres_costos_finca(
 id uuid primary key default gen_random_uuid(), movimiento_id uuid not null unique references public.movimientos_cosecha_finca,
 origen_ciclo_id uuid not null references public.ciclos_finca, destino_ciclo_id uuid not null references public.ciclos_finca,
 monto numeric(16,2) not null check(monto>=0), check(origen_ciclo_id<>destino_ciclo_id)
);
create table public.liquidaciones_dueno_finca(
 id uuid primary key default gen_random_uuid(), ciclo_id uuid not null unique references public.ciclos_finca,
 fecha date not null, ventas_brutas_crc numeric(16,2) not null check(ventas_brutas_crc>=0),
 porcentaje numeric(5,2) not null check(porcentaje between 0 and 100),
 monto numeric(16,2) not null check(monto>=0), propietario text not null, actualizado_en timestamptz not null default now()
);
alter table public.cuentas_manuales add column movimiento_cosecha_id uuid unique references public.movimientos_cosecha_finca;
alter table public.cuentas_manuales add column liquidacion_dueno_id uuid references public.liquidaciones_dueno_finca;
alter table public.cuentas_manuales add constraint liquidacion_tipo_unico unique(liquidacion_dueno_id,tipo);
-- A zero balance generated by a corrected liquidation is retained for its payment history.
do $$declare r record;begin
 for r in select conname from pg_constraint where conrelid='public.cuentas_manuales'::regclass and contype='c' and pg_get_constraintdef(oid) ~ 'monto >' loop
 execute format('alter table public.cuentas_manuales drop constraint %I',r.conname);end loop;
end$$;
alter table public.cuentas_manuales add constraint cuentas_monto_valido check(monto>0 or (monto=0 and liquidacion_dueno_id is not null));
create table public.cierres_ciclo_finca(
 id uuid primary key default gen_random_uuid(), ciclo_id uuid not null references public.ciclos_finca,
 accion text not null check(accion in('Cierre','Reapertura')), fecha timestamptz not null default now(),
 motivo text not null check(length(btrim(motivo))>0), resumen jsonb not null, registrado_por uuid default auth.uid()
);
create index cierres_ciclo_idx on public.cierres_ciclo_finca(ciclo_id);

do $$declare t text;begin
 foreach t in array array['ciclos_finca','movimientos_cosecha_finca','repartos_costos_finca','arrastres_costos_finca','liquidaciones_dueno_finca','cierres_ciclo_finca'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on public.%I from anon,authenticated',t);
 execute format('grant select,insert,update,delete on public.%I to authenticated',t);
 execute format('create policy gestion_oficina on public.%I for all to authenticated using(exists(select 1 from public.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in (''administrador'',''oficina''))) with check(exists(select 1 from public.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in (''administrador'',''oficina'')))',t);
 end loop;
end$$;

create function public.verificar_ciclo_abierto(p_id uuid) returns void language plpgsql security invoker set search_path='' as $$
declare s text;begin
 select estado into s from public.ciclos_finca where id=p_id for update;
 if s is distinct from 'Abierto' then raise exception 'Cultivo cerrado o no disponible. Reabra el cultivo antes de corregirlo.';end if;
end$$;
create function public.validar_movimiento_cosecha() returns trigger language plpgsql set search_path='' as $$
declare saldo numeric;o record;begin
 if tg_op='DELETE' then raise exception 'Conserve el historial de la cosecha';end if;
 if tg_op='UPDATE' then
 perform public.verificar_ciclo_abierto(old.ciclo_id);
 if old.tipo in('Arrastre recibido','Arrastre enviado') then raise exception 'El arrastre conserva su registro de origen y destino';end if;
 if new.ciclo_id<>old.ciclo_id or new.tipo<>old.tipo or new.producto<>old.producto or new.calidad<>old.calidad or new.unidad<>old.unidad or new.orden_compra_id is distinct from old.orden_compra_id or new.solicitud<>old.solicitud then raise exception 'La corrección conserva cultivo, producto, calidad, unidad y tipo del movimiento';end if;
 if nullif(btrim(new.motivo_correccion),'') is null then raise exception 'Indique el motivo de la corrección';end if;
 end if;
 perform public.verificar_ciclo_abierto(new.ciclo_id);
 if new.tipo in('Arrastre recibido','Arrastre enviado') and new.observaciones is null then raise exception 'Indique el motivo del arrastre';end if;
 if new.tipo not in('Cosecha','Arrastre recibido') or tg_op='UPDATE' then
 select coalesce(sum(case when tipo in('Cosecha','Arrastre recibido') then cantidad else -cantidad end),0) into saldo
 from public.movimientos_cosecha_finca where ciclo_id=new.ciclo_id and producto=new.producto and calidad=new.calidad and unidad=new.unidad and id<>new.id;
 if (new.tipo in('Cosecha','Arrastre recibido') and saldo+new.cantidad<0) or(new.tipo not in('Cosecha','Arrastre recibido') and new.cantidad>saldo) then raise exception 'La cantidad corregida deja un saldo negativo. Disponible: % %',saldo,new.unidad;end if;
 end if;
 if new.tipo in('Pérdida','Uso como semilla') and nullif(btrim(new.observaciones),'') is null then raise exception 'Indique el motivo de la pérdida o uso';end if;
 if new.tipo='Entrega a exportadora' then
 select oc.*,p.tipo proveedor_tipo into o from public.ordenes_compra oc join public.proveedores p on p.id=oc.proveedor_id where oc.id=new.orden_compra_id for update of oc;
 if o.id is null or o.estado='Anulada' or o.tipo_compra<>'Cosecha propia' or o.proveedor_tipo<>'Propio'
 or o.finca_lote_id<>(select lote_id from public.ciclos_finca where id=new.ciclo_id) or (o.ciclo_finca_id is not null and o.ciclo_finca_id<>new.ciclo_id) then
 raise exception 'Seleccione una compra de cosecha propia del mismo lote y cultivo';end if;
 update public.ordenes_compra set ciclo_finca_id=new.ciclo_id where id=o.id;
 elsif new.orden_compra_id is not null then raise exception 'Sólo la entrega a exportadora lleva orden de compra';end if;
 return new;
end$$;
create trigger validar_movimiento_cosecha before insert or update or delete on public.movimientos_cosecha_finca for each row execute function public.validar_movimiento_cosecha();
create function public.cobro_venta_cosecha() returns trigger language plpgsql set search_path='' as $$begin
 if new.tipo='Venta en campo' then
 insert into public.cuentas_manuales(codigo,tipo,fecha,fecha_vencimiento,contraparte,moneda,monto,concepto,empresa,movimiento_cosecha_id,categoria)
 values('FINCA-'||new.id,'cobrar',new.fecha,new.fecha,new.comprador,new.moneda,round(new.cantidad_comercial*new.precio_unitario,2),new.producto||' · '||new.calidad||' · venta en campo','agro_solano',new.id,'Venta en campo') on conflict(movimiento_cosecha_id) do update set fecha=excluded.fecha,contraparte=excluded.contraparte,moneda=excluded.moneda,monto=excluded.monto,concepto=excluded.concepto;
 end if;return new;
end$$;
create trigger cobro_venta_cosecha after insert or update on public.movimientos_cosecha_finca for each row execute function public.cobro_venta_cosecha();

create view public.saldos_cosecha_finca with(security_invoker=true) as
 select ciclo_id,producto,calidad,unidad,sum(case when tipo in('Cosecha','Arrastre recibido') then cantidad else -cantidad end)::numeric(16,3) saldo,
 sum(case when tipo='Cosecha' then cantidad else 0 end)::numeric(16,3) cosechado,
 sum(case when tipo='Pérdida' then cantidad else 0 end)::numeric(16,3) perdido
 from public.movimientos_cosecha_finca group by ciclo_id,producto,calidad,unidad;
-- Field value is taken BEFORE deductions, never from export selling prices.
create view public.ventas_campo_ciclo with(security_invoker=true) as
 select m.ciclo_id, 'Venta en campo'::text origen,m.id origen_id,round(m.cantidad_comercial*m.precio_unitario*m.tipo_cambio,2) bruto_crc
 from public.movimientos_cosecha_finca m where m.tipo='Venta en campo'
 union all
 select o.ciclo_finca_id,'Entrega a exportadora',o.id,
 round(coalesce((select sum(b.monto_cxp) from public.boletas_entrada b where b.orden_compra_id=o.id and b.finalizada_en is not null),0)+
 coalesce((select sum((case when e.unidad='Sacos' then e.cantidad*e.peso_saco_kg else e.cantidad*46 end)/46*o.precio_campo) from public.ventas_externas_boleta e join public.boletas_entrada b on b.id=e.boleta_id where b.orden_compra_id=o.id),0),2)
 from public.ordenes_compra o where o.ciclo_finca_id is not null and o.tipo_compra='Cosecha propia' and o.estado is distinct from 'Anulada';
create view public.resumen_ciclos_finca with(security_invoker=true) as
 select c.*,l.finca_id,l.nombre lote_nombre,l.propiedad_id,
 coalesce((select sum(v.bruto_crc) from public.ventas_campo_ciclo v where v.ciclo_id=c.id),0)::numeric(16,2) ventas_brutas_crc,
 (coalesce((select sum(k.monto) from public.costos_finca k where k.ciclo_id=c.id),0)+
 coalesce((select sum(r.monto) from public.repartos_costos_finca r where r.ciclo_id=c.id),0)+
 coalesce((select sum(o.cuadrilla_arranca+o.flete) from public.ordenes_compra o where o.ciclo_finca_id=c.id and o.estado is distinct from 'Anulada'),0)+
 coalesce((select sum(a.monto) from public.arrastres_costos_finca a where a.destino_ciclo_id=c.id),0)-
 coalesce((select sum(a.monto) from public.arrastres_costos_finca a where a.origen_ciclo_id=c.id),0))::numeric(16,2) costos_crc,
 (coalesce((select sum(k.monto) from public.costos_finca k where k.ciclo_id=c.id and k.incluir_en_inversion),0)+
 coalesce((select sum(r.monto) from public.repartos_costos_finca r join public.costos_finca k on k.id=r.costo_id where r.ciclo_id=c.id and k.incluir_en_inversion),0)+
 coalesce((select sum(o.cuadrilla_arranca+o.flete) from public.ordenes_compra o where o.ciclo_finca_id=c.id and o.estado is distinct from 'Anulada'),0)+
 coalesce((select sum(a.monto) from public.arrastres_costos_finca a where a.destino_ciclo_id=c.id),0)-
 coalesce((select sum(a.monto) from public.arrastres_costos_finca a where a.origen_ciclo_id=c.id),0))::numeric(16,2) inversion_crc,
 round(coalesce((select sum(v.bruto_crc) from public.ventas_campo_ciclo v where v.ciclo_id=c.id),0)*c.porcentaje_propietario/100,2) dueno_crc,
 (select count(*) from public.ordenes_compra o where o.ciclo_finca_id=c.id and o.estado is distinct from 'Anulada' and (exists(select 1 from public.boletas_entrada b where b.orden_compra_id=o.id and b.finalizada_en is null) or not exists(select 1 from public.cxp_operativa p where p.origen='compra_campo' and p.origen_id=o.id))) compras_pendientes,
 (select count(*) from public.costos_finca k where k.lote_id=l.id and k.ciclo_id is null and k.fecha>=c.fecha_siembra) gastos_sin_ciclo
 from public.ciclos_finca c join public.lotes_finca l on l.id=c.lote_id;
grant select on public.saldos_cosecha_finca,public.ventas_campo_ciclo,public.resumen_ciclos_finca to authenticated;

create function public.validar_costo_ciclo() returns trigger language plpgsql set search_path='' as $$declare f uuid;l uuid;s numeric;begin
 if tg_op<>'INSERT' and old.ciclo_id is not null then perform public.verificar_ciclo_abierto(old.ciclo_id);end if;
 if tg_op='DELETE' then return old;end if;
 if new.ciclo_id is not null then
 perform public.verificar_ciclo_abierto(new.ciclo_id);
 if new.categoria='Participación del propietario' and exists(select 1 from public.ciclos_finca where id=new.ciclo_id and porcentaje_propietario>0) then raise exception 'La participación del dueño ya se calcula en la liquidación; no vuelva a registrarla como gasto';end if;
 select c.lote_id,lf.finca_id into l,f from public.ciclos_finca c join public.lotes_finca lf on lf.id=c.lote_id where c.id=new.ciclo_id;
 if new.lote_id is distinct from l or (new.finca_id is not null and new.finca_id<>f) then raise exception 'El costo debe corresponder al lote del cultivo';end if;
 if exists(select 1 from public.repartos_costos_finca where costo_id=new.id) then raise exception 'El gasto ya tiene un reparto. Corrija el reparto primero.';end if;
 end if;
 select coalesce(sum(monto),0) into s from public.repartos_costos_finca where costo_id=new.id;
 if s>new.monto or (s>0 and new.lote_id is not null) then raise exception 'El gasto está repartido; conserve su monto y administración';end if;
 return new;
end$$;
create trigger validar_costo_ciclo before insert or update or delete on public.costos_finca for each row execute function public.validar_costo_ciclo();
create function public.validar_reparto_ciclo() returns trigger language plpgsql set search_path='' as $$declare k record;f uuid;s numeric;begin
 if tg_op<>'INSERT' then perform public.verificar_ciclo_abierto(old.ciclo_id);end if;
 if tg_op='DELETE' then return old;end if;
 select * into k from public.costos_finca where id=new.costo_id for update;
 perform public.verificar_ciclo_abierto(new.ciclo_id);
 select l.finca_id into f from public.ciclos_finca c join public.lotes_finca l on l.id=c.lote_id where c.id=new.ciclo_id;
 if k.lote_id is not null or k.ciclo_id is not null or k.finca_id is distinct from f then raise exception 'Reparta un gasto general de la misma administración';end if;
 select coalesce(sum(monto),0) into s from public.repartos_costos_finca where costo_id=new.costo_id and ciclo_id<>new.ciclo_id;
 if s+new.monto>k.monto then raise exception 'El reparto supera el gasto original';end if;
 return new;
end$$;
create trigger validar_reparto_ciclo before insert or update or delete on public.repartos_costos_finca for each row execute function public.validar_reparto_ciclo();
create function public.repartir_gasto_finca(p_costo uuid,p_partes jsonb) returns void language plpgsql security invoker set search_path='' as $$declare r jsonb;begin
 perform 1 from public.costos_finca where id=p_costo for update;
 delete from public.repartos_costos_finca where costo_id=p_costo;
 for r in select value from jsonb_array_elements(p_partes) loop
 insert into public.repartos_costos_finca(costo_id,ciclo_id,monto) values(p_costo,(r->>'ciclo_id')::uuid,(r->>'monto')::numeric);
 end loop;
end$$;
create function public.liquidar_dueno_finca(p_ciclo uuid,p_fecha date) returns uuid language plpgsql security invoker set search_path='' as $$
declare c record;lid uuid;pay numeric;refund numeric;due numeric;owed numeric;begin
 perform public.verificar_ciclo_abierto(p_ciclo);
 select * into c from public.resumen_ciclos_finca where id=p_ciclo;
 if c.porcentaje_propietario<=0 or nullif(btrim(c.propietario),'') is null then raise exception 'Complete el propietario y porcentaje del cultivo';end if;
 insert into public.liquidaciones_dueno_finca(ciclo_id,fecha,ventas_brutas_crc,porcentaje,monto,propietario)
 values(c.id,p_fecha,c.ventas_brutas_crc,c.porcentaje_propietario,c.dueno_crc,c.propietario)
 on conflict(ciclo_id) do update set fecha=excluded.fecha,ventas_brutas_crc=excluded.ventas_brutas_crc,porcentaje=excluded.porcentaje,monto=excluded.monto,propietario=excluded.propietario,actualizado_en=now() returning id into lid;
 select coalesce(sum(a.monto) filter(where m.tipo='pagar'),0),coalesce(sum(a.monto) filter(where m.tipo='cobrar'),0) into pay,refund from public.cuentas_manuales m left join public.aplicaciones_bancarias a on a.origen_id=m.id and a.origen=case when m.tipo='pagar' then 'cuenta_manual_pagar' else 'cuenta_manual_cobrar' end where m.liquidacion_dueno_id=lid;
 owed:=c.dueno_crc;due:=greatest(0,owed-pay+refund);
 insert into public.cuentas_manuales(codigo,tipo,fecha,fecha_vencimiento,contraparte,moneda,monto,concepto,empresa,liquidacion_dueno_id,categoria)
 values('DUEÑO-P-'||lid,'pagar',p_fecha,p_fecha,c.propietario,'CRC',pay+due,'Participación sobre venta bruta EN CAMPO · '||c.nombre,'agro_solano',lid,'Participación del propietario')
 on conflict(liquidacion_dueno_id,tipo) do update set monto=excluded.monto,contraparte=excluded.contraparte,concepto=excluded.concepto,fecha_vencimiento=excluded.fecha_vencimiento;
 insert into public.cuentas_manuales(codigo,tipo,fecha,fecha_vencimiento,contraparte,moneda,monto,concepto,empresa,liquidacion_dueno_id,categoria)
 values('DUEÑO-C-'||lid,'cobrar',p_fecha,p_fecha,c.propietario,'CRC',refund+greatest(0,pay-refund-owed),'Reintegro por corrección de liquidación · '||c.nombre,'agro_solano',lid,'Reintegro propietario')
 on conflict(liquidacion_dueno_id,tipo) do update set monto=excluded.monto,contraparte=excluded.contraparte,concepto=excluded.concepto;
 return lid;
end$$;
create function public.cambiar_estado_ciclo_finca(p_ciclo uuid,p_cerrar boolean,p_motivo text) returns void language plpgsql security invoker set search_path='' as $$declare r record;begin
 if nullif(btrim(p_motivo),'') is null then raise exception 'Indique el motivo del cierre o reapertura';end if;
 perform 1 from public.ciclos_finca where id=p_ciclo for update;
 select * into r from public.resumen_ciclos_finca where id=p_ciclo;
 if r.id is null then raise exception 'Cultivo no disponible';end if;
 if (p_cerrar and r.estado<>'Abierto') or (not p_cerrar and r.estado<>'Cerrado') then raise exception 'El cultivo ya tiene ese estado';end if;
 if p_cerrar then
 if exists(select 1 from public.saldos_cosecha_finca where ciclo_id=p_ciclo and saldo<>0) then raise exception 'Queda producto disponible. Registre venta, pérdida, semilla o arrastre antes de cerrar.';end if;
 if r.compras_pendientes>0 then raise exception 'Hay entregas a exportadora pendientes de liquidar';end if;
 if r.gastos_sin_ciclo>0 then raise exception 'Asigne los gastos del lote al cultivo correspondiente antes de cerrar';end if;
 if r.porcentaje_propietario>0 then perform public.liquidar_dueno_finca(p_ciclo,current_date);end if;
 end if;
 insert into public.cierres_ciclo_finca(ciclo_id,accion,motivo,resumen) values(p_ciclo,case when p_cerrar then 'Cierre' else 'Reapertura' end,p_motivo,to_jsonb(r));
 update public.ciclos_finca set estado=case when p_cerrar then 'Cerrado' else 'Abierto' end where id=p_ciclo;
end$$;
create function public.validar_edicion_ciclo() returns trigger language plpgsql set search_path='' as $$begin
 if tg_op='DELETE' then raise exception 'Conserve el historial del cultivo';end if;
 if tg_op='UPDATE' then
 if old.estado<>new.estado and not exists(select 1 from public.cierres_ciclo_finca where ciclo_id=new.id and fecha>=transaction_timestamp() and accion=case when new.estado='Cerrado' then 'Cierre' else 'Reapertura' end) then raise exception 'Use Cerrar cultivo o Reabrir con motivo';end if;
 if old.estado='Cerrado' and new.estado='Cerrado' then raise exception 'Reabra el cultivo para editar';end if;
 if old.lote_id<>new.lote_id then raise exception 'El lote del cultivo conserva su historial';end if;
 end if;return new;
end$$;
create trigger validar_edicion_ciclo before update or delete on public.ciclos_finca for each row execute function public.validar_edicion_ciclo();
create function public.validar_orden_ciclo() returns trigger language plpgsql set search_path='' as $$begin
 if tg_op<>'INSERT' and old.ciclo_finca_id is not null then perform public.verificar_ciclo_abierto(old.ciclo_finca_id);end if;
 if tg_op='DELETE' then return old;end if;
 if new.ciclo_finca_id is not null then
 perform public.verificar_ciclo_abierto(new.ciclo_finca_id);
 if new.tipo_compra<>'Cosecha propia' or new.finca_lote_id is distinct from (select lote_id from public.ciclos_finca where id=new.ciclo_finca_id) or not exists(select 1 from public.proveedores where id=new.proveedor_id and tipo='Propio') then raise exception 'El cultivo corresponde a cosecha propia de ese lote';end if;
 end if;return new;
end$$;
create trigger validar_orden_ciclo before insert or update or delete on public.ordenes_compra for each row execute function public.validar_orden_ciclo();
create function public.arrastrar_cosecha_finca(p_solicitud uuid,p_origen uuid,p_destino uuid,p_producto text,p_calidad text,p_unidad text,p_cantidad numeric,p_costo numeric,p_fecha date,p_motivo text) returns uuid language plpgsql security invoker set search_path='' as $$declare mid uuid;f1 uuid;f2 uuid;r record;begin
 select id into mid from public.movimientos_cosecha_finca where solicitud=p_solicitud;if mid is not null then return mid;end if;
 if p_origen=p_destino then raise exception 'Seleccione otro cultivo para el arrastre';end if;
 -- Stable lock order for two cycles.
 perform 1 from public.ciclos_finca where id in(p_origen,p_destino) order by id for update;
 perform public.verificar_ciclo_abierto(p_origen);perform public.verificar_ciclo_abierto(p_destino);
 select l.finca_id into f1 from public.ciclos_finca c join public.lotes_finca l on l.id=c.lote_id where c.id=p_origen;
 select l.finca_id into f2 from public.ciclos_finca c join public.lotes_finca l on l.id=c.lote_id where c.id=p_destino;
 if f1 is distinct from f2 then raise exception 'El arrastre debe ser de la misma administración';end if;
 select * into r from public.resumen_ciclos_finca where id=p_origen;
 if p_costo<0 or p_costo>greatest(0,r.costos_crc) then raise exception 'El costo arrastrado supera la inversión registrada';end if;
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad,observaciones) values(p_solicitud,p_origen,p_fecha,'Arrastre enviado',p_producto,p_calidad,p_unidad,p_cantidad,p_motivo) returning id into mid;
 insert into public.movimientos_cosecha_finca(solicitud,ciclo_id,fecha,tipo,producto,calidad,unidad,cantidad,observaciones,movimiento_origen_id) values(gen_random_uuid(),p_destino,p_fecha,'Arrastre recibido',p_producto,p_calidad,p_unidad,p_cantidad,p_motivo,mid);
 insert into public.arrastres_costos_finca(movimiento_id,origen_ciclo_id,destino_ciclo_id,monto) values(mid,p_origen,p_destino,p_costo);
 return mid;
end$$;
-- Make generated farm documents read-only in the general account editor.
create function public.validar_cuenta_finca_generada() returns trigger language plpgsql set search_path='' as $$begin
 if tg_op='UPDATE' and old.movimiento_cosecha_id is distinct from new.movimiento_cosecha_id then raise exception 'Conserve el vínculo del cobro con su venta';end if;
 if new.movimiento_cosecha_id is not null and not exists(select 1 from public.movimientos_cosecha_finca where id=new.movimiento_cosecha_id and tipo='Venta en campo' and moneda=new.moneda and round(cantidad_comercial*precio_unitario,2)=new.monto and comprador=new.contraparte) then raise exception 'El cobro debe coincidir con la venta en campo';end if;
 if new.liquidacion_dueno_id is not null and (new.empresa<>'agro_solano' or new.moneda<>'CRC') then raise exception 'La liquidación agrícola se lleva en Agrosolano, CRC';end if;
 return new;
end$$;
create trigger validar_cuenta_finca_generada before insert or update on public.cuentas_manuales for each row execute function public.validar_cuenta_finca_generada();

-- One tractor identity for operational records and investment valuation.
alter table public.activos_finca add column tractor_operativo_id uuid unique references public.tractores_finca;
create function public.sincronizar_ficha_tractor() returns trigger language plpgsql set search_path='' as $$declare tid uuid;begin
 if pg_trigger_depth()>1 then return new;end if;
 if tg_table_name='activos_finca' then
 if new.tipo='Tractor' then
 if new.tractor_operativo_id is null then
 insert into public.tractores_finca(finca_id,nombre,marca,modelo,caballaje,serie,activo) values(new.finca_id,new.nombre,new.marca,new.modelo,new.caballaje,new.codigo,new.estado<>'Retirado') returning id into new.tractor_operativo_id;
 else update public.tractores_finca set finca_id=new.finca_id,nombre=new.nombre,marca=new.marca,modelo=new.modelo,caballaje=new.caballaje,serie=new.codigo,activo=new.estado<>'Retirado' where id=new.tractor_operativo_id;end if;
 elsif new.tractor_operativo_id is not null then raise exception 'Conserve el tipo Tractor de esta ficha';end if;
 else
 update public.activos_finca set finca_id=new.finca_id,nombre=new.nombre,marca=new.marca,modelo=new.modelo,caballaje=new.caballaje,codigo=new.serie where tractor_operativo_id=new.id;
 if not found then insert into public.activos_finca(finca_id,tipo,nombre,marca,modelo,caballaje,codigo,tractor_operativo_id,observaciones) values(new.finca_id,'Tractor',new.nombre,new.marca,new.modelo,new.caballaje,new.serie,new.id,'Valoración pendiente; ficha enlazada al historial de trabajo.');end if;
 end if;return new;
end$$;
create trigger sincronizar_ficha_tractor before insert or update on public.activos_finca for each row execute function public.sincronizar_ficha_tractor();
create trigger sincronizar_activo_tractor after insert or update on public.tractores_finca for each row execute function public.sincronizar_ficha_tractor();
update public.activos_finca set nombre=nombre where tipo='Tractor' and tractor_operativo_id is null;
update public.tractores_finca t set nombre=t.nombre where not exists(select 1 from public.activos_finca a where a.tractor_operativo_id=t.id);
-- Keep historical activity editable after a tractor is transferred.
do $$declare d text;begin
 select pg_get_functiondef('public.sincronizar_actividad_tractor()'::regprocedure) into d;
 d:=replace(d,'if new.tractor_id is not null and not exists','if new.tractor_id is not null and (tg_op=''INSERT'' or new.tractor_id is distinct from old.tractor_id or new.finca_id is distinct from old.finca_id) and not exists');
 execute d;
end$$;
-- Restrict execute permission on newly exposed RPCs and trigger helpers.
do $$declare r record;begin
 for r in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('verificar_ciclo_abierto','validar_movimiento_cosecha','cobro_venta_cosecha','validar_costo_ciclo','validar_reparto_ciclo','repartir_gasto_finca','liquidar_dueno_finca','cambiar_estado_ciclo_finca','validar_edicion_ciclo','validar_orden_ciclo','arrastrar_cosecha_finca','validar_cuenta_finca_generada','sincronizar_ficha_tractor') loop
 execute format('revoke all on function %s from public,anon',r.signature);execute format('grant execute on function %s to authenticated',r.signature);
 end loop;
end$$;
-- Prevent a plant correction from silently changing a closed farm result.
create function public.validar_boleta_ciclo_cerrado() returns trigger language plpgsql set search_path='' as $$declare oid uuid;cid uuid;begin
 if tg_table_name='boletas_entrada' then oid:=case when tg_op='DELETE' then old.orden_compra_id else new.orden_compra_id end;
 else select orden_compra_id into oid from public.boletas_entrada where id=case when tg_op='DELETE' then old.boleta_id else new.boleta_id end;end if;
 select ciclo_finca_id into cid from public.ordenes_compra where id=oid;
 if cid is not null then perform public.verificar_ciclo_abierto(cid);end if;
 if tg_op='DELETE' then return old;end if;return new;
end$$;
create trigger validar_boleta_ciclo_cerrado before insert or update or delete on public.boletas_entrada for each row execute function public.validar_boleta_ciclo_cerrado();
create trigger validar_externa_ciclo_cerrado before insert or update or delete on public.ventas_externas_boleta for each row execute function public.validar_boleta_ciclo_cerrado();
revoke all on function public.validar_boleta_ciclo_cerrado() from public,anon;
grant execute on function public.validar_boleta_ciclo_cerrado() to authenticated;
-- Guard linked aggregate rows against inconsistent direct writes.
create function public.validar_liquidacion_finca() returns trigger language plpgsql set search_path='' as $$declare c record;begin
 if tg_op='DELETE' then raise exception 'Conserve la liquidación y sus pagos';end if;
 perform public.verificar_ciclo_abierto(new.ciclo_id);
 select * into c from public.resumen_ciclos_finca where id=new.ciclo_id;
 if new.ventas_brutas_crc<>c.ventas_brutas_crc or new.porcentaje<>c.porcentaje_propietario or new.monto<>c.dueno_crc or new.propietario is distinct from c.propietario then raise exception 'La liquidación debe coincidir con las ventas brutas en campo y el porcentaje pactado';end if;
 return new;
end$$;
create trigger validar_liquidacion_finca before insert or update or delete on public.liquidaciones_dueno_finca for each row execute function public.validar_liquidacion_finca();
create function public.validar_arrastre_costos() returns trigger language plpgsql set search_path='' as $$begin
 if tg_op<>'INSERT' then raise exception 'Conserve el historial del arrastre';end if;
 perform public.verificar_ciclo_abierto(new.origen_ciclo_id);perform public.verificar_ciclo_abierto(new.destino_ciclo_id);
 if not exists(select 1 from public.movimientos_cosecha_finca m join public.movimientos_cosecha_finca d on d.movimiento_origen_id=m.id where m.id=new.movimiento_id and m.ciclo_id=new.origen_ciclo_id and d.ciclo_id=new.destino_ciclo_id and m.tipo='Arrastre enviado' and d.tipo='Arrastre recibido' and m.producto=d.producto and m.calidad=d.calidad and m.unidad=d.unidad and m.cantidad=d.cantidad) then raise exception 'El costo debe acompañar un arrastre de producto registrado';end if;
 if new.monto>(select greatest(0,costos_crc) from public.resumen_ciclos_finca where id=new.origen_ciclo_id) then raise exception 'El costo arrastrado supera la inversión';end if;
 return new;
end$$;
create trigger validar_arrastre_costos before insert or update or delete on public.arrastres_costos_finca for each row execute function public.validar_arrastre_costos();
revoke all on function public.validar_liquidacion_finca(),public.validar_arrastre_costos() from public,anon;
grant execute on function public.validar_liquidacion_finca(),public.validar_arrastre_costos() to authenticated;
alter table public.movimientos_cosecha_finca add constraint venta_campos_obligatorios check(tipo<>'Venta en campo' or(cantidad_comercial is not null and precio_unitario is not null and comprador is not null and unidad_comercial is not null));
alter table public.movimientos_cosecha_finca add constraint conversion_comercial_valida check(tipo<>'Venta en campo' or (unidad_comercial not in('kg','Quintales','Unidades')) or (unidad_comercial='kg' and unidad='kg' and cantidad=cantidad_comercial) or(unidad_comercial='Quintales' and unidad='kg' and abs(cantidad-cantidad_comercial*46)<=0.023) or(unidad_comercial='Unidades' and unidad='Unidades' and cantidad=cantidad_comercial));

create table public.correcciones_cosecha_finca(
 id uuid primary key default gen_random_uuid(), movimiento_id uuid not null references public.movimientos_cosecha_finca,
 fecha timestamptz not null default now(), anterior jsonb not null, corregido jsonb not null,
 motivo text not null, registrado_por uuid default auth.uid()
);
create index correcciones_cosecha_mov_idx on public.correcciones_cosecha_finca(movimiento_id);
alter table public.correcciones_cosecha_finca enable row level security;
grant select,insert on public.correcciones_cosecha_finca to authenticated;
create policy gestion_oficina on public.correcciones_cosecha_finca for all to authenticated
 using(exists(select 1 from public.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in('administrador','oficina')))
 with check(exists(select 1 from public.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in('administrador','oficina')));
create function public.historial_correccion_cosecha() returns trigger language plpgsql set search_path='' as $$begin
 insert into public.correcciones_cosecha_finca(movimiento_id,anterior,corregido,motivo) values(new.id,to_jsonb(old),to_jsonb(new),new.motivo_correccion);return new;
end$$;
create trigger historial_correccion_cosecha after update on public.movimientos_cosecha_finca for each row execute function public.historial_correccion_cosecha();
revoke all on function public.historial_correccion_cosecha() from public,anon;
grant execute on function public.historial_correccion_cosecha() to authenticated;
